### ISSUE TITLE
Test failure: test_psm3::test_get_psm3_tmy

### ISSUE THREAD

**Issue by kanderso-nrel** [pvlib/pvlib-python#1005]
The test data file we use for the NSRDB TMY API test is out of date.  In particular, it seems that the temperature, wind speed and direction, and albedo values have changed to some extent.  The various Test_conda_linux azure checks have been failing because of this. 

This dataset (tmy-2017) is intended to be static over time, but the version the API had been serving until recently was apparently a preliminary version that has now been replaced with the official version.  So hopefully this issue won't be recurring if we update our test file to match the API data, which is what I suggest doing.  Acceptable?

See https://github.com/NREL/developer.nrel.gov/issues/159 for further details.

**Comment by wholmgren** [comment]
+1

Would be great to get the CI running cleanly again.
