### ISSUE TITLE
change whats new API section names

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#1009]
I put an API change in the wrong section of the whats new file in #1008. In case it's a more common misreading, I thought I should check how other packages label these sections. 

pvlib:
* API Changes with Deprecations
* API Changes

Pandas:
* Backwards incompatible API changes
* Deprecations

Numpy:
* Expired deprecations
* Compatibility notes
* Deprecations
* C API changes
* Changes

xarray:
* Breaking changes
* Deprecations

For pvlib, I think xarray's pattern is most appropriate. I don't like the similarity of pvlib's sections.

**Comment by cwhanse** [comment]
I'm OK with the xarray pattern for changes to function signatures and module content.

We may want a third category, for changes which cause functions to produce different results, either from fixing bugs or changing algorithms, e.g., filtering a clearsky model for unreasonable values and replacing with NaN.
