### ISSUE TITLE
doc: add variables

### ISSUE THREAD

**Issue by dacoex** [pvlib/pvlib-python#102]
Hello,

anything against adding
https://github.com/pvlib/pvlib-python/wiki/Variables-and-style-rules
to the sphinx docs?

this way, I have them with me also when offline.

**Comment by wholmgren** [comment]
Sure, that makes sense now that the names have stabilized. Can you make a pr?

**Comment by dacoex** [comment]
sure.

I suggest to use 
http://docutils.sourceforge.net/docs/ref/rst/directives.html#csv-table

Do you agree?

**Comment by wholmgren** [comment]
Why do you prefer this to the standard sphinx table format? I think the sphinx format is easier to read in the doc source code.

**Comment by dacoex** [comment]
Was fastest to implement.
Additionally, the csv values can be reused, e.g. to assign variables or translate variables into descriptions.

**Comment by wholmgren** [comment]
Ok, well I am confused about the status since you closed your PR and deleted your branch. Please provide a link to rtd's rendering your branch when you (re)open your PR.

**Comment by dacoex** [comment]
I am definitly not a git pro. But I tried to pack my 3 commits together. So maybe github closed it through the commands.
The link is here:
https://github.com/dacoex/pvlib-python/pull/2
Thanks.

**Comment by dacoex** [comment]
Shall we also compare the parameter names with [IEC 61724](https://law.resource.org/pub/in/bis/S05/is.iec.61724.1998.pdf)

**Comment by wholmgren** [comment]
You'll have to be more specific for me to understand what you're really proposing.

**Comment by dacoex** [comment]
See:
https://github.com/pvlib/pvlib-python/commit/e6dea98a855bb93e325ef95c632b407d01c6ceed#diff-01c51400deeacb229d692d6a21e7af79R17

**Comment by wholmgren** [comment]
I'm ok with adding a symbol column, but I don't think we should tie it to the IEC document. I would default to the PVPMC symbols.

**Comment by dacoex** [comment]
> I would default to the PVPMC symbols.

sure, the other one is just for reference.

But it's good in the case one performs performance evaluation with usually bases on the IEC or the contractual formulas.

**Comment by wholmgren** [comment]
My preference is for a simple table that is focused on the pvlib-python standards. A handful of links to documents such as the IEC's and PVPMC website could be useful below the table.

**Comment by dacoex** [comment]
mmh.

**Comment by wholmgren** [comment]
I don't know what that means.

**Comment by dacoex** [comment]
Let's start with your proposal. 
Ideally, I'd love to have variables, units and refernce to standard side-by-side.

**Comment by dacoex** [comment]
Comment https://github.com/pvlib/pvlib-python/issues/102#issuecomment-172568309 implemented in 
https://github.com/pvlib/pvlib-python/pull/103

2 items I find strange:

* RTD stylesheet / template does not support bulleted lists, see the test list below.
* RTD stylesheet / template does not support line wrapping in CSV table directive.

I tested these 2 items with a fresh sphinx project and there it worked.

Looking forward to your feedback to be able to close this issue ;-)

**Comment by dacoex** [comment]
Clsong since the PR #103 was merged.
