### ISSUE TITLE
stable doc badge is broken

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#1058]
**Describe the bug**
stable: ![stable](https://readthedocs.org/projects/pvlib-python/badge/?version=stable)
latest: ![latest](https://readthedocs.org/projects/pvlib-python/badge/?version=latest)
v0.8.0: ![v0.8.0](https://readthedocs.org/projects/pvlib-python/badge/?version=v0.8.0)

**To Reproduce**
look at the readme

**Expected behavior**
says passing in green

**Screenshots**
stable: ![stable](https://readthedocs.org/projects/pvlib-python/badge/?version=stable)

**Versions:**
 - ``pvlib.__version__``: v0.8.0

**Additional context**
latest: ![latest](https://readthedocs.org/projects/pvlib-python/badge/?version=latest)
v0.8.0: ![v0.8.0](https://readthedocs.org/projects/pvlib-python/badge/?version=v0.8.0)

**Comment by mikofski** [comment]
should we restart the stable build? Or just ignore it? I don't understand why it says the v0.8.0 passes but not stable. bizarre.

**Comment by wholmgren** [comment]
Weird. It did point to the right thing though. In any case, I restarted the build, it passed, and now the badge is green.
