### ISSUE TITLE
add NREL API to SUNY international weather data to iotools

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#1088]
**Problem**
There's less international weather data

**Solution**
Add `get_nrel_suny()`, `read_`, & `parse_` to use the the [SUNY international data API from NREL](https://developer.nrel.gov/docs/solar/nsrdb/suny-india-data-download/)

**Additional context**
Check out the NREL NSRDB docs and developer network:
* [NREL dev docs - Solar](https://developer.nrel.gov/docs/solar/)
* [NREL dev docs - NSRDB](https://developer.nrel.gov/docs/solar/nsrdb/)
* [NREL dev docs - SUNY international data](https://developer.nrel.gov/docs/solar/nsrdb/suny-india-data-download/)
* info about [NSRDB international data](https://nsrdb.nrel.gov/about/international-data.html)
* [NREL dev docs - dataset download](https://developer.nrel.gov/docs/solar/solar-resource-v1/) - returns average monthly output at location
* [NREL dev docs - dataset query](https://developer.nrel.gov/docs/solar/data-query-v1/) - returns list of sites near location

**Comment by AdamRJensen** [comment]
I believe that "SUNY India" and "SUNY International" are the same datasets.

As the most recent data seems to be from 2014, I vote that we do not make a dedicated function for this dataset and close this issue. @mikofski thoughts?
