### ISSUE TITLE
PVlib pvlib.solarposition.get_solarposition datetime issue

### ISSUE THREAD

**Issue by yangangky** [pvlib/pvlib-python#1105]
**Describe the bug**
When use solarpostion.get_solarposition to get a dataframe, I found the date information have some erron. 
1, The timezone is not consistant, including +8:00 and +9:00,  although I set up the timezone=+8:00.
2. An hour information is missed and anohter hour information is duplication.

**To Reproduce**
tz = 'Asia/Shanghai'
lat, lon = 31.2304, 121.4737

times = pd.date_range('1990-01-01 00:00:00', '1991-01-01', closed='left', freq='H', tz=tz)
solpos = solarposition.get_solarposition(times, lat, lon)

solpos_reset = solpos.reset_index(inplace=False)
solpos_reset.rename(columns={'index': 'date'}, inplace = True)
solpos_reset['hour'] = solpos.index.hour

df1=solpos_reset.iloc[2495:2501]

![image](https://user-images.githubusercontent.com/74975184/101853939-7abb5880-3b9b-11eb-9360-f3c517d0f41c.png)

df2=solpos_reset.iloc[6190:6196]

![image](https://user-images.githubusercontent.com/74975184/101854015-9d4d7180-3b9b-11eb-8576-39b86a8dab9c.png)

**Versions:**
 - ``pvlib.__version__``: 0.8
 - ``pandas.__version__``: 0.24.2
 - python: V3.7.3

**Comment by wholmgren** [comment]
Looks like daylight savings to me. Scroll to the bottom of https://timezonedb.com/time-zones/Asia/Shanghai

**Comment by yangangky** [comment]
Thanks a lot. I have finised simulation comparison with PVsyst  for monofacial module/fixed rack system yeasterday. The MBE/RMSE is so good.  Thanks a lot for you help and this amazing software.
