### ISSUE TITLE
Add link to ASV pvlib-benchmarker in documentation

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#1124]
**Problem**
I can't find any reference or links to the ASV benchmarker in the documentation

**Solution**
I think a small section with a link to the ASV benchmarker and some discussion about why we benchmark pvlib, how to use read the results, and whatever

**Alternatives**
There are links in the pull request #1049 

**Additional context**
The benchmarks are really cool, and it's impressive that we have them, so we should advertise and help people use them and solicit their feedback on how we can improve, what's useful, what's not, etc.

**Comment by kanderso-nrel** [comment]
ICYMI, there technically is a trail of breadcrumbs that gets you to the benchmark graphs page, but it's a little roundabout:
- https://pvlib-python.readthedocs.io/en/stable/contributing.html#benchmarking
- https://github.com/pvlib/pvlib-python/blob/master/benchmarks/README.md

But it's not very discoverable and can certainly be made more useful.

**Comment by mikofski** [comment]
Agh! I searched different variations of benchmark(s) and benchmarker, but not "benchmarking" and evidently the sphinx/rtd search engine is very picky.

**Comment by wholmgren** [comment]
How about adding to the table of badges in the main readme?

**Comment by Naman-Priyadarshi** [comment]
Working on this issue @mikofski

**Comment by Naman-Priyadarshi** [comment]
> 

opened pull request for this recommendation

**Comment by wholmgren** [comment]
closed by #1427
