### ISSUE TITLE
alarm "too many indices for array" when use pvfactors_timeseries

### ISSUE THREAD

**Issue by yangangky** [pvlib/pvlib-python#1125]
**Describe the bug**

When I run the following code, it will alarm "too many indices for array" . I think there is only one index was input, why it alarm that? please help. [Thanks.]

**Screenshots**

![image](https://user-images.githubusercontent.com/74975184/103753539-1e3a4480-5046-11eb-974b-964251342b18.png)

**Versions:**
 - ``pvlib.__version__``:  0.8.0
 - ``pandas.__version__``: 0.24.2
 - python: V3.7.3

**Comment by cwhanse** [comment]
@yangangky Could you post this issue to https://groups.google.com/g/pvlib-python ? It would help if you can also post the code. The screenshot isn't enough to understand the error python is reporting.

**Comment by yangangky** [comment]
@cwhanse , Cliff, thanks a lot for your response. My google account can not be allowed to send a meesage. It alarmed "Error while posting message".  I have joined the pvlib-python groups. If it need a permission before I can post a message?

![image](https://user-images.githubusercontent.com/74975184/103841399-79b01500-50ce-11eb-9b06-1b52cf10afc9.png)
![image](https://user-images.githubusercontent.com/74975184/103841457-98161080-50ce-11eb-8421-97f39e61c750.png)

**Comment by yangangky** [comment]
The issue has been solved by change the surface_azimuth and surface_tilt to a list. like surface_azimuth = [180 , 180]...

**Comment by cwhanse** [comment]
@yangangky reports an opportunity to improve `pvlib.bifacial.pvfactors`.  Opening a new issue to describe the improvement.
