### ISSUE TITLE
Docs: use internal linking of python objects

### ISSUE THREAD

**Issue by dacoex** [pvlib/pvlib-python#113]
Reference
http://wholmgren-pvlib-python-new.readthedocs.org/en/pvsystem/classes.html#pvsystem

using the Sphinx python domain would make the docs more interactive when finalising #93 

```See the :py:class:`LocalizedPVSystem` class for an object model that describes an installed PV system.```

http://www.sphinx-doc.org/en/stable/domains.html#the-python-domain

**Comment by wholmgren** [comment]
Ok. I am going to close for now and you can reopen it if it's an issue once the PR is merged. Alternatively, you can comment on the specific line in the PR.
