### ISSUE TITLE
numpy intersphinx object inventory changed

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#1130]
**Describe the bug**
the new url is https://numpy.org/doc/stable/

**To Reproduce**

https://github.com/pvlib/pvlib-python/blob/b0d29f550ea14d49499a97d60fa80c32a2a883d6/docs/sphinx/source/conf.py#L319

this goes to the main scipy docs page, not NumPy

**Expected behavior**
where ever numpy functions, classes, etc are used, they should be automatically linked, but they are not

**Screenshots**
I didn't look for one

**Versions:**
- 0.8.1

**Additional context**
I wonder if we really even need this, and we don't have an intersphinx mapping for scipy

**Comment by kanderso-nrel** [comment]
Relevant log output from the most recent `latest` [RTD build](https://readthedocs.org/api/v2/build/12713455.txt):
```
intersphinx inventory has moved: https://docs.scipy.org/doc/numpy/objects.inv -> https://numpy.org/doc/stable/objects.inv
```

>  I wonder if we really even need this, and we don't have an intersphinx mapping for scipy

I think the intersphinx links are nice to have and and worth keeping as long as they aren't much effort to maintain.  Especially in the example gallery I imagine it is convenient for some users to have wikipedia-style cross-links as they read ("what does np.unique do again?")
