### ISSUE TITLE
Add doc page describing content of CEC databases read by pvlib.pvsystem.retrieve_sam

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvlib-python#1131]
Descriptions of the databases read by `pvlib.pvsystem.retrieve_sam` aren't found in documentation or in function docstrings. The provided link to SAM pages leads to a bibliography of NREL publications, and it isn't clear which publication contains a description of the SAM CEC files.  

As an alternative to adding to pvlib documentation, documentation could be added to the SAM project but it is not clear where (SAM provides pdf reports rather than documentation pages).

**Comment by wholmgren** [comment]
duplicate of #838?

**Comment by wholmgren** [comment]
#964 also relevant

**Comment by cwhanse** [comment]
Closed, duplicate of #838
