### ISSUE TITLE
Remove outdated and possibly unused `environment.yaml`

### ISSUE THREAD

**Issue by Peque** [pvlib/pvlib-python#1133]
The file `docs/environment.yaml` seems to be outdated as it is not possible to generate the documentation with a virtualenvironment created based on that file. It is currently missing `dataclasses` (since it declares use of Python 3.6), `sphinx-gallery`, `sphinx-toggleprompt` and `Pillow`.

Since all those dependencies and the `dataclasses` requirement for Python 3.6 is already handled in `setup.py`, I think the `docs/environment.yaml` could be simply removed to avoid confusion and duplicated dependencies declaration.

**Comment by wholmgren** [comment]
correct, the doc build uses an environment specified by `pip install pvlib[doc]`
