### ISSUE TITLE
pvsyst cell temp docs for eta_m arg missing "area" from definition

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#1151]
**Describe the bug**
the definition for `eta_m` says:
![image](https://user-images.githubusercontent.com/1385621/106188516-e82b4480-615b-11eb-9b6f-239a67c7b74c.png)

But I think this should actually be: `(total DC power) / (poa_global * (total active module area))`

**To Reproduce**
1. Go to https://pvlib-python.readthedocs.io/en/latest/generated/pvlib.temperature.pvsyst_cell.html#pvlib.temperature.pvsyst_cell
2. Look at `pvlib.temperature.pvsyst_cell` parameters
3. Scroll down to `eta_m`
4. See definition

**Expected behavior**
I think this should actually be: `(total DC power) / (poa_global * (total active module area))`

**Screenshots**
![image](https://user-images.githubusercontent.com/1385621/106188516-e82b4480-615b-11eb-9b6f-239a67c7b74c.png)

**Versions:**
 - ``pvlib.__version__``: v0.8.1
 - ``pandas.__version__``: na
 - python: na

**Additional context**
see https://www.pvsyst.com/help/thermal_loss.htm
>`Effic`  is the PV efficiency (related to the module area), i.e. the energy removed from the module. When possible, the PV efficiency is calculated according to the operating conditions of the module. Otherwise it is taken as 10%.

Does this mean that the `Uc` and `Uv` coefficients already take into account the active module area? but then `eta_m` will not be a number less than one, so I don't think so.

**Comment by cwhanse** [comment]
> I think this should actually be: (total DC power) / (poa_global * (total active module area))

Agree. Good catch.  Maybe "number of cells x cell area" would be more clear than "total active module area"

**Comment by KushalBeniwal** [comment]
@mikofski can I work on this issue?

**Comment by mikofski** [comment]
Yes, of course! thanks so much. If you need any help getting started check the [contribution guide](https://pvlib-python.readthedocs.io/en/stable/contributing.html) or you can at me here too.
