### ISSUE TITLE
AttributeError: module 'pvlib' has no attribute 'shading'

### ISSUE THREAD

**Issue by flxzmmrmnn** [pvlib/pvlib-python#1161]
I am trying to model the self shading of the diffuse radiation with pvlib.shading.masking_angle_passias() and pvlib.shading.sky_diffuse_passias(). When I try to run the modell I get the following error:

AttributeError: module 'pvlib' has no attribute 'shading'

**Versions:**
 - ``pvlib.__version__``: 0.8.0
 - ``pandas.__version__``: 1.2.1
 - python: 3.8.5

**Comment by kanderso-nrel** [comment]
Hi @flxzmmrmnn, thanks for the report.  This was fixed in #1103 -- you can work around this problem either by using `from pvlib import shading; shading.masking_angle_passias()` or by upgrading to pvlib 0.8.1.
