### ISSUE TITLE
bifacial.pvfactors_timeseries() TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by flxzmmrmnn** [pvlib/pvlib-python#1166]
Hey there,

I am trying to run the function bifacial.pvfactors_timeseries(), but I get the error: TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'. I am not sure which of my imput values is wrong. Bellow you can see the function how I have written it and afterwards all the input values. 

            bifacial = pvlib.bifacial.pvfactors_timeseries(solar_azimuth=
                                                           interim_weather_df[cf.name_solar_azimuth_column],
                                                           solar_zenith=
                                                           interim_weather_df[cf.name_solar_zenith_column],
                                                           surface_azimuth=
                                                           interim_weather_df[cf.name_surface_azimuth_column],
                                                           surface_tilt=interim_weather_df[cf.name_surface_tilt_column],
                                                           axis_azimuth=self.axis_azimuth,
                                                           timestamps=interim_weather_df.index,
                                                           dni=interim_weather_df[cf.name_dni_column],
                                                           dhi=interim_weather_df[cf.name_dhi_column],
                                                           gcr=self.gcr,
                                                           pvrow_height=model.input_values.pv_row_height,
                                                           pvrow_width=model.input_values.pv_row_width,
                                                           albedo=model.input_values.albedo,
                                                           n_pvrows=3,
                                                           index_observed_pvrow=1,
                                                           rho_front_pvrow=0.03,
                                                           rho_back_pvrow=0.05,
                                                           horizon_band_angle=15.0)

INPUT:

solar_azimuth:
DateTime
2021-01-01 00:00:00     97.187197
2021-01-01 01:00:00    101.540512
2021-01-01 02:00:00    106.110145
2021-01-01 03:00:00    111.243075
2021-01-01 04:00:00    117.309691
                          ...    
2021-12-31 19:00:00    267.819165
2021-12-31 20:00:00    275.138902
2021-12-31 21:00:00     16.368075
2021-12-31 22:00:00     85.702389
2021-12-31 23:00:00     92.570576
Name: SolarAzimuth [degrees], Length: 8760, dtype: float64
<class 'pandas.core.series.Series'>

solar_zenith:
DateTime
2021-01-01 00:00:00    138.523400
2021-01-01 01:00:00    125.107246
2021-01-01 02:00:00    111.902032
2021-01-01 03:00:00     99.016647
2021-01-01 04:00:00     86.614106
                          ...    
2021-12-31 19:00:00    153.132110
2021-12-31 20:00:00    166.720097
2021-12-31 21:00:00    178.042055
2021-12-31 22:00:00    165.635180
2021-12-31 23:00:00    152.043372
Name: SolarZenith [degrees], Length: 8760, dtype: float64
<class 'pandas.core.series.Series'>

surface_azimuth:
DateTime
2021-01-01 00:00:00     NaN
2021-01-01 01:00:00     NaN
2021-01-01 02:00:00     NaN
2021-01-01 03:00:00     NaN
2021-01-01 04:00:00    90.0
                       ... 
2021-12-31 19:00:00     NaN
2021-12-31 20:00:00     NaN
2021-12-31 21:00:00     NaN
2021-12-31 22:00:00     NaN
2021-12-31 23:00:00     NaN
Name: SurfaceAzimuth [degrees], Length: 8760, dtype: float64
<class 'pandas.core.series.Series'>

surface_til:
DateTime
2021-01-01 00:00:00     NaN
2021-01-01 01:00:00     NaN
2021-01-01 02:00:00     NaN
2021-01-01 03:00:00     NaN
2021-01-01 04:00:00    90.0
                       ... 
2021-12-31 19:00:00     NaN
2021-12-31 20:00:00     NaN
2021-12-31 21:00:00     NaN
2021-12-31 22:00:00     NaN
2021-12-31 23:00:00     NaN
Name: SurfaceAzimuth [degrees], Length: 8760, dtype: float64
<class 'pandas.core.series.Series'>

axis_azimuth:
DateTime
2021-01-01 00:00:00          NaN
2021-01-01 01:00:00          NaN
2021-01-01 02:00:00          NaN
2021-01-01 03:00:00          NaN
2021-01-01 04:00:00    15.601643
                         ...    
2021-12-31 19:00:00          NaN
2021-12-31 20:00:00          NaN
2021-12-31 21:00:00          NaN
2021-12-31 22:00:00          NaN
2021-12-31 23:00:00          NaN
Name: SurfaceTilt [degrees], Length: 8760, dtype: float64
<class 'pandas.core.series.Series'>

timestamps:
[Timestamp('2021-01-01 00:00:00'), Timestamp('2021-01-01 01:00:00'), Timestamp('2021-01-01 02:00:00'), Timestamp('2021-01-01 03:00:00'), Timestamp('2021-01-01 04:00:00'), Timestamp('2021-01-01 05:00:00'), Timestamp('2021-01-01 06:00:00'), Timestamp('2021-01-01 07:00:00'), Timestamp('2021-01-01 08:00:00'), Timestamp('2021-01-01 09:00:00'), Timestamp('2021-01-01 10:00:00'), Timestamp('2021-01-01 11:00:00'), Timestamp('2021-01-01 12:00:00'), Timestamp('2021-01-01 13:00:00'), Timestamp('2021-01-01 14:00:00'), Timestamp('2021-01-01 15:00:00'), Timestamp('2021-01-01 16:00:00'), Timestamp('2021-01-01 17:00:00'), Timestamp('2021-01-01 18:00:00'), Timestamp('2021-01-01 19:00:00'), ...]
<class 'list'>

dni:
DateTime
2021-01-01 00:00:00    0
2021-01-01 01:00:00    0
2021-01-01 02:00:00    0
2021-01-01 03:00:00    0
2021-01-01 04:00:00    0
                      ..
2021-12-31 19:00:00    0
2021-12-31 20:00:00    0
2021-12-31 21:00:00    0
2021-12-31 22:00:00    0
2021-12-31 23:00:00    0
Name: DNI [W/m^2], Length: 8760, dtype: int64
<class 'pandas.core.series.Series'>

dhi:
DateTime
2021-01-01 00:00:00    0
2021-01-01 01:00:00    0
2021-01-01 02:00:00    0
2021-01-01 03:00:00    0
2021-01-01 04:00:00    0
                      ..
2021-12-31 19:00:00    0
2021-12-31 20:00:00    0
2021-12-31 21:00:00    0
2021-12-31 22:00:00    0
2021-12-31 23:00:00    0
Name: DHI [W/m^2], Length: 8760, dtype: int64
<class 'pandas.core.series.Series'>

all other inputs are float and int

I also tried one simulation with droping all NaN rows in the input data frames and got the same error. I also tried to only use numerical data as input, as can be seen below and I still got the same error.

            bifacial = pvlib.bifacial.pvfactors_timeseries(solar_azimuth=235.7,
                                                           solar_zenith=75.6,
                                                           surface_azimuth=270,
                                                           surface_tilt=72.8,
                                                           axis_azimuth=180,
                                                           timestamps=datetime.datetime.strptime('01-01-2021  13:00:00', '%d-%m-%Y %H:%M:%S'),
                                                           dni=29,
                                                           dhi=275,
                                                           gcr=0.2,
                                                           pvrow_height=2,
                                                           pvrow_width=2,
                                                           albedo=0.1,
                                                           n_pvrows=3,
                                                           index_observed_pvrow=1,
                                                           rho_front_pvrow=0.03,
                                                           rho_back_pvrow=0.05,
                                                           horizon_band_angle=15.0)

python version: 3.8.5
pvlib version: 0.8.0
pv factors version: 1.5.0
pandas version: 1.2.1

Thank you very much for your help!

**Comment by cwhanse** [comment]
Hi @flxzmmrmnn could you repost your issue on either Stackoverflow or Googlegroups? The links are in the Getting Support section of the pvlib-python github homepage.

I think we need a code sample to run that produces the error you are seeing.

It is possible you have found an issue in pvlib, but until we can identify and confirm an issue I am going to close this.
