### ISSUE TITLE
GFS Forecasts error

### ISSUE THREAD

**Issue by dpostolovski** [pvlib/pvlib-python#1202]
**Describe the bug**
From today, I see an error using the GFS prediction model:
```
 Server Error (400: Variable: Total_cloud_cover_low_cloud_Mixed_intervals_Average is not contained in the requested dataset)
```

The variable is indeed missing from the GFS dataset, as can be seen in the [catalog](https://thredds.ucar.edu/thredds/metadata/grib/NCEP/GFS/Global_0p25deg/Best?metadata=variableMap).

**To Reproduce**
```
model = GFS('quarter', set_type='latest')
raw_data = model.get_data(latitude, longitude, start, end)
```

**Expected behavior**
Dataframe being loaded.

**Screenshots**

**Versions:**
 - ``pvlib.__version__``:  0.8.1
 - ``pandas.__version__``: 1.1.5, irelevant
 - python: 3.8

**Additional context**

**Comment by wholmgren** [comment]
It's possible that the variables changed during a recent upgrade. Pull request welcome. I'm unlikely to fix it myself.
