### ISSUE TITLE
TypeError: num2date() got an unexpected keyword argument 'only_use_python_datetimes'

### ISSUE THREAD

**Issue by naingeet** [pvlib/pvlib-python#1207]
While running the example code from https://pvlib-python.readthedocs.io/en/stable/forecasts.html
I got TypeError: num2date() got an unexpected keyword argument 'only_use_python_datetimes'. 
In reference to previous bugs (https://github.com/pvlib/pvlib-python/blob/709daa6f8feddb50ae50b1da13f5f720d8ebb78f/pvlib/forecast.py#L409), where the reason could be for python version 3.5 or less, I confirmed my python version was 3.7.3 and still having this TypeError issue.

**Comment by kanderso-nrel** [comment]
Does updating to a newer version of `cftime` fix the issue?  See https://groups.google.com/g/pvlib-python/c/d4NDtQwj_L8/m/H1Lvt4XHBAAJ
