### ISSUE TITLE
How to obtain meteorological data 

### ISSUE THREAD

**Issue by salehi1234** [pvlib/pvlib-python#1210]
would be appreciated to know whether there are any data banks or sites to download the data of wind velocity, temperature, and cloud thickness, the most important of them all, for about two years( from 2019 to 2020).**

**Comment by cwhanse** [comment]
Hi @salehi1234 could you post this question to the pvlib [googlegroup ](https://groups.google.com/g/pvlib-python)or to [stackoverflow](https://stackoverflow.com/search?tab=newest&q=pvlib) with the pvlib tag? We try to keep github issues related to software, and discuss usage in the other forums.

I think we'd need to know which region of the world you are interested in.
