### ISSUE TITLE
GFS model server error.

### ISSUE THREAD

**Issue by m-glowacki** [pvlib/pvlib-python#1212]
**Describe the bug**
GFS model returns:
Server Error (400: Variable: Total_cloud_cover_high_cloud_Mixed_intervals_Average is not contained in the requested dataset)

**To Reproduce**
1. from pvlib.forecast import GFS, NAM, NDFD, HRRR, RAP
2. model = GFS()
    dataFrame = model.get_processed_data(latitude, longitude, start, end)

**Expected behavior**
return dataframe of weather forecasts between start and end datetime

**Screenshots**

**Versions:**
 - pvlib.__version: 0.8.1

 - python: 3.8.8

**Comment by wholmgren** [comment]
Please see https://groups.google.com/g/pvlib-python/c/9_umpFGQpXM/m/X3HlKSGKDAAJ
