### ISSUE TITLE
several iotools tests are failing

### ISSUE THREAD

**Issue by kanderso-nrel** [pvlib/pvlib-python#1217]
Just documenting some test failures that popped up on #1216:

## SRML
`test_srml.py` takes a long time to run, and eventually fails, because it repeatedly attempts and to connect to the remote server but the connection attempts time out:
`TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond`.

Maybe a temporary server issue, or maybe we need to update a URL or something, I did not check.  I guess the `@pytest.mark.flaky` decorator on those tests makes them take long enough to time out the CI entirely.

## PVGIS
`test_pvgis.py` fails because the copyright metadata string changed from `'PVGIS (c) European Communities'` to `'PVGIS (c) European Union'`, should be an easy fix

**Comment by cwhanse** [comment]
So CI jobs are going to time out until these issues are fixed?

**Comment by kanderso-nrel** [comment]
> 
> 
> So CI jobs are going to time out until the `test_srml` issue is fixed?

I think so, or at least the `conda_linux` ones anyway.  It seems like the entire solardat UOSRML website is down.  Should we temporarily replace the `flaky` mark with `xfail` on those tests?

**Comment by cwhanse** [comment]
I'll email Frank and see ask if it's temporary or permanent. @wholmgren this issue affects the Arbiter

**Comment by wholmgren** [comment]
One idea for live API tests is to only run them in scheduled nightly builds so they don't spoil PRs.
