### ISSUE TITLE
Incorrect irradiance used in pvsystem.ipynb tutorial

### ISSUE THREAD

**Issue by ejmiller2** [pvlib/pvlib-python#127]
In the tutorial pvsystem.ipynb, In [54] reads:

```
sapm_1 = pvsystem.sapm(sandia_module, irrad_data['dni']*np.cos(np.radians(aoi)),
                     irrad_data['ghi'], temps['temp_cell'], am, aoi)
```
I believe the poa_diffuse parameter should use irrad_data['dhi'] instead of irrad_data['ghi'].

**Comment by wholmgren** [comment]
Yes, thanks for pointing that out.

**Comment by dacoex** [comment]
@wholmgren will look at this when porting the tuts.
Sorry for the delay. some biz came in between.
