### ISSUE TITLE
How to organize the example gallery?

### ISSUE THREAD

**Issue by kanderso-nrel** [pvlib/pvlib-python#1271]
The [example gallery](https://pvlib-python.readthedocs.io/en/latest/auto_examples/index.html) now has 17 items and might benefit from being organized into sections.  This has been briefly discussed elsewhere:

- https://github.com/pvlib/pvlib-python/pull/1077#issuecomment-705690331
- https://github.com/pvlib/pvlib-python/pull/1266#issuecomment-892112481

I think the sphinx configuration changes to do this would be straightforward (see [here](https://sphinx-gallery.github.io/stable/configuration.html#sorting-gallery-subsections)).  The question is how the gallery should be organized.  For inspiration, here are some other packages with sections in their gallery:
- matplotlib: https://matplotlib.org/stable/gallery/index.html
- metpy: https://unidata.github.io/MetPy/latest/examples/index.html
- sunpy: https://docs.sunpy.org/en/stable/generated/gallery/index.html
- cartopy: https://scitools.org.uk/cartopy/docs/latest/gallery/index.html
- scikit-learn: https://scikit-learn.org/stable/auto_examples/index.html
- probably other ones listed here: https://sphinx-gallery.github.io/stable/projects_list.html

To get the conversation started, here are some categorizations mentioned in the above threads:
- by abstraction level: functions vs objects
- by task (or "how do I"), e.g. system modeling vs resource assessment vs ...
- by modeling topic, roughly along the lines of the pvlib module breakdown and PVPMC diagram

Input from anyone is welcome!

**Comment by mikofski** [comment]
I think I like by module? EG:
- solar position
- irradiance
- atmosphere
- clearsky
- PV modules
- inverters 
- IO
- IV curves
- PV systems
- etc

This could incorporate both topics and abstraction level, bc objects tend to aggregate several functions across topics. Each section could have both "how to's" and other less general examples
