### ISSUE TITLE
How to use the Transposition Model for locations with DST? 

### ISSUE THREAD

**Issue by UGuntupalli** [pvlib/pvlib-python#1312]
Hello, 

Thanks a lot for maintaining the pvlib pacakge. I am looking at a specific usage that follows the documentation mentioned here (https://pvlib-python.readthedocs.io/en/stable/auto_examples/plot_transposition_gain.html) 

Can the same example be demonstrated for a site affected by DST ? The chosen site is in Arizona where there is no DST. 

This could in part be linked to an issue in pandas, but pvlib offers an alternative to address it, it would be really helpful to know about it. 
```
import pandas as pd

time_zone_1 = 'America/Phoenix'
time_zone_2 = 'America/New_York'

index_1= pd.DatetimeIndex(
    data=pd.date_range(start='1990-01-01 01:00', freq='H', periods=8759),
    tz=time_zone_1
)

index_2= pd.DatetimeIndex(
    data=pd.date_range(start='1990-01-01 01:00', freq='H', periods=8759),
    tz=time_zone_2
)
```

**Comment by cwhanse** [comment]
Hi @UGuntupalli 

I can't think of a reason that example wouldn't run correctly for a location with DST. I haven't tried it.

Your question is about usage. Can you repost it at stackoverflow or the google group?  The links are [here](https://github.com/pvlib/pvlib-python#getting-support).

Cheers.
