### ISSUE TITLE
Integrate Solcast API into iotools

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#1313]
**Is your feature request related to a problem? Please describe.**
Get irradiance via Solcast API
https://solcast.com/solar-data-api/api/

**Describe the solution you'd like**
Use iotools to get irradiance data from Solcast

**Describe alternatives you've considered**
Solcast already has an API toolkit. Is irons redundant?

**Additional context**
* https://docs.solcast.com.au/#introduction
* https://solcast.com/solar-data-api/api-toolkit/
* icymi @AdamRJensen

**Comment by williamhobbs** [comment]
This could be expanded to include other APIs, such as Solargis (https://solargis.com/products/api/data-delivery-web-service/overview) and SolarAnywhere (https://developers.cleanpower.com/irradiance-and-weather-data/).

**Comment by kanderso-nrel** [comment]
A bit of relevant discussion here: https://github.com/pvlib/pvlib-python/discussions/1310

**Comment by mikofski** [comment]
Hi @kanderso-nrel is this issue superceded by the Engerer PR #1366 ?

**Comment by kanderso-nrel** [comment]
@mikofski Solcast and Engerer don't seem related to me, what's the connection?  Or maybe you meant another issue?

**Comment by mikofski** [comment]
[Nick Engerer is the CTO and a co-founders of Solcast](https://www.linkedin.com/in/dr-nick-engerer/), so I thought maybe their software uses his methods? But TBH that's just an assumption.

**Comment by kanderso-nrel** [comment]
Ha, of course!  I think #1366 does not supercede this one: decomposition function in `pvlib.irradiance` vs data fetching function in `pvlib.iotools`.
