### ISSUE TITLE
Add engerer2 decomposition model

### ISSUE THREAD

**Issue by AdamRJensen** [pvlib/pvlib-python#1316]
**Is your feature request related to a problem? Please describe.**
The [engerer2](https://aip.scitation.org/doi/full/10.1063/1.5097014) separation/decomposition model generally outperforms all of the decomposition models available in pvlib according to https://doi.org/10.1016/j.solener.2015.10.010.

**Describe the solution you'd like**
Add a Python implementation of the engerer2 model to pvlib.

**Additional context**
A Python implementation is available from the [author](https://github.com/JamieMBright/Engerer2-separation-model/blob/master/Engerer2Separation.py), though there is no license information given. @JamieMBright?

This could potentially be labeled a good first issue.

**Comment by kanderso-nrel** [comment]
Closing, see comments in #1366
