### ISSUE TITLE
pvfactors_timeseries docstring types are incorrect

### ISSUE THREAD

**Issue by kanderso-nrel** [pvlib/pvlib-python#1332]
**Describe the bug**
The [pvfactors_timeseries](https://pvlib-python.readthedocs.io/en/v0.9.0/generated/pvlib.bifacial.pvfactors_timeseries.html) docstring currently lists several parameters as "numeric", implying scalar values are acceptable ([docs](https://pvlib-python.readthedocs.io/en/stable/contributing.html#documentation)).  However, some parameters cannot actually be scalars and should be listed as "array-like" instead.

**To Reproduce**
Example showing that scalar inputs for the module orientation parameters are not acceptable:

<details>
  <summary>Click to expand!</summary>

```python
import pvlib
import pandas as pd
from pvlib.bifacial import pvfactors_timeseries

times = pd.date_range('2019-01-01', '2019-01-02', freq='15min').tz_localize('Etc/GMT+5')
location = pvlib.location.Location(40, -80)
solarpos = location.get_solarposition(times)
clearsky = location.get_clearsky(times)

kwargs = dict(
    solar_azimuth=solarpos['azimuth'],
    solar_zenith=solarpos['apparent_zenith'],
    axis_azimuth=0,
    timestamps=times,
    dni=clearsky['dni'],
    dhi=clearsky['dhi'],
    gcr=0.3,
    pvrow_height=1.5,
    pvrow_width=1.0,
    albedo=0.2
)

pvfactors_timeseries(surface_tilt=20, surface_azimuth=90, **kwargs)  # IndexError: too many indices for array
pvfactors_timeseries(surface_tilt=pd.Series(20, index=times),
                     surface_azimuth=pd.Series(90, index=times),
                     **kwargs)  # works
```
</details>

**Expected behavior**
Correct the types in the docstring to accurately reflect pvfactors' requirements. 

**Additional context**
Originally discussed here: https://github.com/pvlib/pvlib-python/discussions/1331#discussioncomment-1542801
Edit: this is more or less a duplicate of #1127

**Comment by kanderso-nrel** [comment]
Maybe this is less a docs bug and more a functionality bug.  I generally expect pvlib functions to work with scalar orientation values.  A better fix may be to allow scalar inputs and to cast scalars to arrays inside the function prior to forwarding them on to pvfactors.

**Comment by cwhanse** [comment]
> A better fix may be to allow scalar inputs and to cast scalars to arrays inside the function prior to forwarding them on to pvfactors.

+1
