### ISSUE TITLE
get_processed_data not running

### ISSUE THREAD

**Issue by alisboainegi** [pvlib/pvlib-python#1341]
Pvlib was working fine and suddenly does not.

When trying to run  get_processed_data this error appears:
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

**Versions:**
 - ``pvlib.__version__``:  0.9.0
 - ``pandas.__version__``: 1.3.4
 - python: 3.8 and 3.7

**Comment by cwhanse** [comment]
For some reason, the forecast server returned an empty response. I doubt this is a pvlib problem.

**Comment by alisboainegi** [comment]
> For some reason, the forecast server returned an empty response. I doubt this is a pvlib problem.

Thank you for your reply!

So there is not much to do, right?

**Comment by cwhanse** [comment]
Yes, I would wait and try again.
