### ISSUE TITLE
Add note to `irradiance.haydavies` docstring about projection_ratio parameter

### ISSUE THREAD

**Issue by kanderso-nrel** [pvlib/pvlib-python#1352]
Is it worthwhile to add a similar note to `irradiance.haydavies`? Something like "When supplying projection_ratio, consider constraining its values when zenith angle approaches 90 degrees. See code for details." Certainly not required here.

_Originally posted by @wholmgren in https://github.com/pvlib/pvlib-python/pull/1349#pullrequestreview-826594259_

**Comment by Carlosbogo** [comment]
Hi, if needed I would like to work on this issue.

**Comment by cwhanse** [comment]
@Carlosbogo you are welcome to do it. Thanks!
