### ISSUE TITLE
Broken link in read_midc documentation

### ISSUE THREAD

**Issue by williamhobbs** [pvlib/pvlib-python#1363]
The link to Variable Style Rules (https://pvlib-python.readthedocs.io/en/latest/variables_style_rules.html) appears to be broken:

https://github.com/pvlib/pvlib-python/blob/b3c1b5e9fba606c3a89c052d07c9e500518bba5d/pvlib/iotools/midc.py#L155-L207

![image](https://user-images.githubusercontent.com/45701090/147683451-9470e26d-6b27-43aa-9359-17b648d316bc.png)

**Comment by kanderso-nrel** [comment]
Thanks @williamhobbs, I didn't think to check for existing links when I moved those pages under `user_guide` in #1173.  Looking at the results of `$ git grep "pvlib-python\..*/en/"`, there are several links to update:

- `README.md:Please see the [Installation page](http://pvlib-python.readthedocs.io/en/stable/installation.html) of the documentation for complete instructions.`
- `docs/tutorials/irradiance.ipynb:    "http://pvlib-python.readthedocs.io/en/latest/clearsky.html\n",`
- ```pvlib/iotools/midc.py:    <https://pvlib-python.readthedocs.io/en/latest/variables_style_rules.html>`_.```
- `pvlib/modelchain.py:    See https://pvlib-python.readthedocs.io/en/stable/modelchain.html`

As an aside, is it desirable for any link like this to point to `latest`?  Maybe we should standardize to `stable` everywhere.

**Comment by cwhanse** [comment]
> we should standardize to stable everywhere.

+1
