### ISSUE TITLE
Wrong Return in documentation of cloud_covr_to_transmittance_linear

### ISSUE THREAD

**Issue by JoLo90** [pvlib/pvlib-python#1367]
In the documentation of the **pvlib.forecast.NDFD.cloud_cover_to_transmittance_linear** function, it seems the documented return is the wrong one: It shows the GHI as the return instead of the transmittance.

![image](https://user-images.githubusercontent.com/65318981/148192058-a75a0ff8-7655-4d66-833f-ef5d0c625bea.png)

Here is the function in pvlib.forecast that seems to confirm the case.

        """
        Convert cloud cover to atmospheric transmittance using a linear
        model.

        0% cloud cover returns offset.

        100% cloud cover returns 0.

        Parameters
        ----------
        cloud_cover : numeric
            Cloud cover in %.
        offset : numeric, default 0.75
            Determines the maximum transmittance.
        kwargs
            Not used.

        Returns
        -------
        ghi : numeric
            Estimated GHI.
        """
        transmittance = ((100.0 - cloud_cover) / 100.0) * offset

        return transmittance`

**Comment by AdamRJensen** [comment]
Seems like it was a mistake when the [function](https://github.com/pvlib/pvlib-python/blame/master/pvlib/forecast.py#L512-L538) was added in #180.

Should probably be updated to something like this:

    Returns
    -------
    transmittance: numeric
        Estimated transmittance.

Perhaps it's worth denoting that it is a fraction and not in percentage like the cloud cover?

**Comment by cwhanse** [comment]
> it's worth denoting that it is a fraction

Absolutely

**Comment by AdamRJensen** [comment]
@JoLo90 If you wanted to make a pull request for this issue, that would be more than welcomed.

**Comment by JoLo90** [comment]
@AdamRJensen I'll create a PR in the next days.

**Comment by kanderso-nrel** [comment]
Closed by #1370, thanks @JoLo90!
