### ISSUE TITLE
Documentation: Link to SAM CSV weather file format is broken

### ISSUE THREAD

**Issue by williamhobbs** [pvlib/pvlib-python#1377]
This reference link for SAM CSV file format in this documentation page, https://pvlib-python.readthedocs.io/en/stable/generated/pvlib.iotools.read_psm3.html, appears broken:

![image](https://user-images.githubusercontent.com/45701090/149413598-97b4a7eb-0ac8-40e1-b263-7a305b92f87d.png)

This link might be acceptable: https://sam.nrel.gov/images/web_page_files/sam-help-2020-2-29-r1_weather_file_formats.pdf

**Comment by kanderso-nrel** [comment]
That PDF likes to disappear.  In the meantime, https://github.com/NREL/developer.nrel.gov/issues/196 has a link to a copy on the internet archive.
