### ISSUE TITLE
Klucher diffuse sky docstring inconsistency

### ISSUE THREAD

**Issue by adriesse** [pvlib/pvlib-python#1405]
The equation for F' should contain DHI rather than Id0.

**Versions:**
 - ``pvlib.__version__``: 0.9 and earlier

**Comment by cwhanse** [comment]
I'm sure that Loutzenhiser's notation is `I_{d}` sky diffuse on a surface tilted at `d`, and `I_{d0}` is sky diffuse on a horizontal surface. But that's not helpful documentation here.

To do with this: add inline citations, punctuation, units in brackets, define `theta`, `theta_z`, and `beta`.

Maybe jettison the whole second paragraph that reiterates the inputs, and incorrectly adds `extraterrestrial irradiance`.

To discuss: remove "must be >=0", or change to "should be >=0". The code doesn't require this restriction, although the model certainly isn't valid outside that range. My view: model constraints on input (should be's) would be better placed in the description or in Notes, and code restrictions (must be's) in the parameter descriptions.

**Comment by kanderso-nrel** [comment]
Seems like several of those items apply to the other sky diffuse model docstrings as well. 

Also, does it make sense for the Loutzenhiser reference to be listed first?  Seems like it ought to be a secondary reference if it's included at all.

**Comment by cwhanse** [comment]
> Also, does it make sense for the Loutzenhiser reference to be listed first? Seems like it ought to be a secondary reference if it's included at all.

Although Loutzenhiser is a survey and comparison among models, it more clearly defines several models than do the source papers. That's why we chose it as the baseline reference.
