### ISSUE TITLE
Improve ``get_cams`` documentation

### ISSUE THREAD

**Issue by AdamRJensen** [pvlib/pvlib-python#1412]
**Describe the bug**
The geographical coverage of CAMS Radiation retrieved with the [``get_cams``](https://pvlib-python.readthedocs.io/en/stable/generated/pvlib.iotools.get_cams.html#pvlib.iotools.get_cams) function is not exactly ±66 degrees in latitude and longitude. Therefore, to clarify this, the word "approximate" should be added to the function documentation [here](https://github.com/pvlib/pvlib-python/blob/63c36db473ce9d7406bfb90526c37783515716c2/pvlib/iotools/sodapro.py#L59).

Also, the description has a typo - "Wordwide" should be corrected to "worldwide".

**Screenshots**
The actual CAMS Radiation coverage:
![image](https://user-images.githubusercontent.com/39184289/155616629-1c49a98f-6558-4c05-a656-9109e8f73d4a.png)

**Comment by AdamRJensen** [comment]
@soma2000-lang That would be much appreciated! :)

**Comment by soma2000-lang** [comment]
Ok working on that
