### ISSUE TITLE
Changes to PVGIS in version 5.2

### ISSUE THREAD

**Issue by AdamRJensen** [pvlib/pvlib-python#1415]
**Describe the bug**
PVGIS is releasing version 5.2 on March 1st, 2022. In the new version, the irradiance databases CMSAF and COSMO have been removed. Additionally, the ERA5 coverage has been extended to cover almost the entire globe and a new database, SARAH-2, has been added.

The full description can be found [here](https://joint-research-centre.ec.europa.eu/pvgis-photovoltaic-geographical-information-system/pvgis-releases/pvgis-52_en).

The new default databases can be seen here:
![image](https://user-images.githubusercontent.com/39184289/155888945-985b896e-5b7d-4789-9132-a51a858fc53d.png)

**Additional context**
There is nothing that indicates any changes to the API, so the pvlib.iootools functions ``get_pvgis_tmy`` and ``get_pvgis_hourly`` should continue to work.

However, some of the test files used in `test_pvgis.py` are from the CMSAF database. Since those tests seem to be either based on local files or mock tests, I do not expect test failures. However, it would probably make sense to update the tests regardless.

**Comment by cwhanse** [comment]
@AdamRJensen do you know if the content of CMSAF and COSMO are migrating to the new database? Sorry that I'm not familiar with PVGIS.

**Comment by cwhanse** [comment]
> @AdamRJensen do you know if the content of CMSAF and COSMO is migrating to the new database? Sorry that I'm not familiar with PVGIS.

I missed the link to the documentation in my quick read of your issue, the documentation answers my question. I agree it would make sense to replace the test files or (more simply) to add a note to the test code identifying the data source.

**Comment by AdamRJensen** [comment]
In order to use the new version 5.2 (which is still in beta), the URL needs to be updated, e.g.,:

    res = pvlib.iotools.get_pvgis_hourly(
        latitude=28.965734,
        longitude=117.147418,
        raddatabase='PVGIS-ERA5',
        url='https://re.jrc.ec.europa.eu/api/v5_2/',
    )

I suspect this will only be necessary temporarily until the databases are considered stable and migrated to the default URL. The retired databases CMSAF and COSMO remain available through the default URL for now, though they will be removed in the future.

**Comment by kanderso-nrel** [comment]
Probably a good idea to scrub mentions of the retired databases from the docstring as well:

https://github.com/pvlib/pvlib-python/blob/c2431832040f585969bbd1868f6acdd6ddb4e0a5/pvlib/iotools/pvgis.py#L140-L144

@AdamRJensen thoughts on tagging this issue for 0.9.1?

**Comment by AdamRJensen** [comment]
@kanderso-nrel what's the current timeline for 0.9.1? I'll be out of the office until April 5th fyi.

**Comment by kanderso-nrel** [comment]
> what's the current timeline for 0.9.1

Don't think there really is a timeline.  Next couple weeks maybe?  Depends on how long it takes us to finish or defer the remaining things in #1424...

**Comment by kanderso-nrel** [comment]
@AdamRJensen should we keep this open until we update the tests and docstrings?

**Comment by AdamRJensen** [comment]
@kanderso-nrel Sorry I got ahead of myself
