### ISSUE TITLE
v0.9.1 release planning

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvlib-python#1424]
We should get v0.9.1 released soon.

Issues to close or relabel:
- [x] #1057 
- [x] #1302 
- [ ] #1323 
- [ ] #1345
- [ ] #1405 
- [x] #1124

PRs to complete or relabel:
- [ ] #1251 
- [x] #1374 
- [ ] #1393 
- [x] #1422 
- [x] #1426
- [x] #1427
- [x] #1429
- [ ] #1433

@pvlib/pvlib-maintainer feel free to add or modify these check lists.

**Comment by kanderso-nrel** [comment]
Sure, I can tag.  Sometime next week, maybe March 29?

Given its recent progress it'd be a bit of a shame to not include #1251 IMHO. #1345 would be good too (thanks @cwhanse for pointing it out).  I've not updated that file before but I'm willing to figure it out if others are not actively excited to do it this time.

We are not addressing any part of #1403 in 0.9.1, correct?

**Comment by cwhanse** [comment]
> We are not addressing any part of https://github.com/pvlib/pvlib-python/issues/1403 in 0.9.1, correct?

I started on #1403 and got discouraged by the apparent breadth of functions and methods it would touch. Maybe it would be better to do incremental PRs for that issue.

**Comment by mikofski** [comment]
> pick a day to release

I would ❤️ to have a regular release schedule, like every 3-6 months. This is an essential component of agile

**Comment by cwhanse** [comment]
Each release leaves me with a list of open issues that I would like to see closed. More frequent releases = more motivation to work on those issues :)

**Comment by mikofski** [comment]
@kanderso-nrel and others, shall we add "auto-bot" to conda forge? Create an issue with this in the title only?
`@conda-forge-admin,please add bot automerge` I think that's it

**Comment by wholmgren** [comment]
In my experience, the conda forge bots are only ok at picking up changes to the dependencies. We could add automerge but I think we'd still want to manually review the work and possibly need to update recipes and issue new builds.

**Comment by mikofski** [comment]
>we'd still want to manually review the work and possibly need to update recipes and issue new builds

I think there's a different bot for detecting version changes, not automerge-bot, which I think pushes a new release automatically if the tests all pass. That's been my experience with the dulwich-feedstock.

I believe the one we might want then is regro/cf-autotick-bot, which I thought would automatically already be part of the pvlib python feedstock, but is it possible that pvlib predates the autotick-bot? TBH, I don't understand how to add this functionality if it's not already part of the feedstock, I think if we want this feature (which I'd advise) we should seek help on their google group? I notice that SolarForecastArbiter was forked by the autotick-bot, but pvlib is not

* https://groups.google.com/g/conda-forge/
* https://conda-forge.org/docs/maintainer/updating_pkgs.html
* https://github.com/regro/cf-scripts
* https://github.com/pulls?q=is%3Aopen+is%3Apr+author%3Aregro-cf-autotick-bot+archived%3Afalse+pvlib

**Comment by wholmgren** [comment]
From https://github.com/conda-forge/solarforecastarbiter-feedstock/pull/17#issue-1133458746

> Please note that this analysis is highly experimental. The aim here is to make maintenance easier by inspecting the package's dependencies. Importantly this analysis does not support optional dependencies, please double check those before making changes. If you do not want hinting of this kind ever please add bot: inspection: false to your conda-forge.yml. If you encounter issues with this feature please ping the bot team conda-forge/bot.

It's better than nothing, but it does require review. I don't remember anything about the pvlib feedstock setup, so best to search their docs and/or ping their bot team.
