### ISSUE TITLE
inconsistency between PVlib and PVsyst when calculating rotated plane azimuth

### ISSUE THREAD

**Issue by mayudong** [pvlib/pvlib-python#144]
When I was comparing the stimulative results of PVlib with PVsyst, I noticed that for PV panels with same configurations, the calculated rotated plane azimuth computed by pvlib.tracking.singleaxis(..)
is different from that of PVsyst. 

I did find out where the problem is, and it is related to the coordinator transformation.

Can I create a pull request to submit my fix?

**Comment by wholmgren** [comment]
@mayudong yes, that would be great.

**Comment by tafadzwalgurupira** [comment]
I also noticed different results for my POA irradiance results when I used the tutorial(tmy_to_power) and compared the results with PVSyst. Can anyone help me figure out where I am going wrong and fix it?

**Comment by wholmgren** [comment]
@tafadzwalgurupira, I believe that @mayudong is discussing a potential issue with the single axis tracker code, whereas you are discussing an issue with some part of the plane of array calculations. So, I'd prefer that you make a new issue with more details to discuss the discrepancy between the tmy_to_power tutorial and your pvsyst results. This helps keep discussions focused and on topic. Thanks.

**Comment by cwhanse** [comment]
@mayudong  could you post a summary of your fix?  If there's a code error, it's likely also present in the Matlab toolbox and I'd like to fix it there as well.  Thanks.

**Comment by mayudong** [comment]
Sure. I have summarized the issue and potential fix in the attached file.
Please double check and confirm the issue.
Best
[NEX-PVSystemModelComparison-110416-1221-2.pdf](https://github.com/pvlib/pvlib-python/files/213735/NEX-PVSystemModelComparison-110416-1221-2.pdf)

**Comment by wholmgren** [comment]
I tried to simply this part of the matlab code and it's possible that I introduced an error. I'll look at it more carefully.

**Comment by mayudong** [comment]
Actually the results calculated using Matlab are different from PVsyst too.
I will create a pull request sometime this week

**Comment by wholmgren** [comment]
I looked at the surface azimuth results more carefully and I agree that they are not correct in pvlib python for non-trivial cases. Example 3 of the python [single axis tutorial](http://nbviewer.jupyter.org/github/pvlib/pvlib-python/blob/v0.3.0/docs/tutorials/tracking.ipynb#Example-3:) and the matlab version's [documentation](https://pvpmc.sandia.gov/PVLIB_Matlab_Help/html/pvl_singleaxis_help.html) simulates a tracker with 20 deg surface tilt. I remade the matlab figure to include the surface azimuth...

![python tracker](https://cloud.githubusercontent.com/assets/4383303/14468527/dfeb736c-0094-11e6-98d3-336e9e0e4851.png)
![matlab tracker](https://cloud.githubusercontent.com/assets/4383303/14468530/e485182e-0094-11e6-83ab-44545c72dd39.png)

I'll look at the proposed fix in #145  next.

**Comment by wholmgren** [comment]
Closed by #145
