### ISSUE TITLE
Temperature model parameter translation

### ISSUE THREAD

**Issue by adriesse** [pvlib/pvlib-python#1442]
**Is your feature request related to a problem? Please describe.**
The simple temperature models in pvlib are all very similar but their parameters are not interchangeable.

**Describe the solution you'd like**
This feature will provide a means to translate parameters between these models: Faiman, SAPM, PVsyst & NOCT SAM.

**Additional context**
Details of the methods were presented at IEEE PVSC 2022.  A pre-print version of the paper can be downloaded from here:

https://www.researchgate.net/publication/361463601_PV_Module_Operating_Temperature_Model_Equivalence_and_Parameter_Translation

**Comment by mikofski** [comment]
This is an interesting idea. Does it only refer to [Faiman](https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.temperature.faiman.html) and [PVsyst](https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.temperature.pvsyst_cell.html)? Or also Fuentes or SAPM?

perhaps a write up in a new temperature section of the [user guide](https://pvlib-python.readthedocs.io/en/stable/user_guide/index.html), on the PVPMC website, or in the pvlib GH wiki would be useful to describe in more detail how these models are mathematically and scientifically similar or different would be helpful in explaining why we need a function or class to interpret them and use them interchangeably?

**Comment by adriesse** [comment]
I updated the current scope in the opening description: Faiman, SAPM, PVsyst & NOCT SAM.  The upcoming IEEE PVSC paper should answer a lot of your questions and we can see after the event how much of that content needs repeating in other forms.

**Comment by kanderso-nrel** [comment]
@adriesse I've been lead to understand that this feature and #1523 are the first of several planned additions to pvlib.  What do you think about opening (preliminary) issues for those future additions now?  For one it's just interesting to see what's coming down the pipe, but it might also be useful context for other additions in the meantime.

**Comment by adriesse** [comment]
That's a good question but hard to answer.  We're doing model development and the output can go into functions, notebooks, reports and papers and can include data files.  I could try to open PR's earlier, but that's probably not a full solution for coordinated development.
