### ISSUE TITLE
Inconsistency between PVlib and PVsyst when calculating POA irradiance

### ISSUE THREAD

**Issue by tafadzwalgurupira** [pvlib/pvlib-python#146]
I used the tutorial (tmy_to_power) to calculate the POA irradiance and compared them to a PVSyst simulation for the same conditions and settings and found the results varying significantly. 

Please assist me if I am doing something wrong, or can suggest a fix.. I am kind of new here.

screenshots of the simulations are here: https://www.dropbox.com/sh/3qtkozqde15i38c/AAA9_fERkvkxlW8gGyG3zJJja?dl=0

**Comment by cwhanse** [comment]
If you are using PVsyst v6, the default transposition model is Perez, not Hay and Davies.  The PVLib tutorial uses Hay and Davies.

Cliff

**Comment by tafadzwalgurupira** [comment]
@cwhanse , thanks for the suggestion but I had already checked it and that is not the case. I used Hay and Davies as prescribed and the results are only consistent when surface tilt is 0

**Comment by wholmgren** [comment]
you're probably going to need to post your code if we're going to get to the bottom of this.

**Comment by tafadzwalgurupira** [comment]
https://www.dropbox.com/s/9stmuuaavxdq7dp/tmy_to_power-Copy2.ipynb?dl=0

**Comment by wholmgren** [comment]
Ok, focusing on July 5...

Here's the TMY data

![download 2](https://cloud.githubusercontent.com/assets/4383303/14746647/6a2169a6-0865-11e6-9eae-177df1b06e1f.png)

The DNI reaches 800 W/m2 hr.

Next, the apparent solar zenith and the AOI for a surface_tilt=30 panel.

![download 3](https://cloud.githubusercontent.com/assets/4383303/14746787/21a700e0-0866-11e6-9c54-e22d826b60f2.png)

Finally, POA irradiances for flat and 30 degree panels.

![download 5](https://cloud.githubusercontent.com/assets/4383303/14746912/c1ebd684-0866-11e6-9d92-50e3a23493bd.png)

![download 4](https://cloud.githubusercontent.com/assets/4383303/14746845/67194584-0866-11e6-8264-28198e853bbd.png)

These pvlib results make sense to me. Here's your "PVSystPOA_surface_tilt_30" plot...

![unspecified](https://cloud.githubusercontent.com/assets/4383303/14747087/6e65baf6-0867-11e6-93db-7a22c9b94494.png)

Maybe something is mislabeled or we're using different conventions, but this does not make sense to me.

**Comment by jforbess** [comment]
I loaded Sand Point into PVsyst 6.37 and got this graph:

Is it possible you are using a non due south azimuth in PVsyst? Note that
PVsyst thinks that 0 is due south and 180 is due north. Super annoying.


​

**Comment by wholmgren** [comment]
@jforbess I think you need to use the GitHub website to include graphics in a comment.

**Comment by jforbess** [comment]
Ah, good to know. 
I loaded Sand Point into PVsyst 6.37 and got this graph:
![screen shot 2016-04-22 at 9 11 35](https://cloud.githubusercontent.com/assets/8305153/14749633/64c338da-0875-11e6-9f5b-464d46644b85.png)

**Comment by wholmgren** [comment]
@jforbess thanks! It looks reasonably consistent to me given that the pvlib tutorial's treatment of time for the hourly average modeling is going to cause some errors. I'm not sure how these PVSyst models are treating the time averaging.

**Comment by jforbess** [comment]
Yes, I think so too.

**Comment by tafadzwalgurupira** [comment]
Thanks for all your help everyone. The problem looks like it was just as @jforbess suspected: PVSyst's treatment of 0 and 180 degrees as due north and due south, respectively.
