### ISSUE TITLE
Addressing unequal times error from pvlib.temperature.prilliman with no leap day

### ISSUE THREAD

**Issue by williamhobbs** [pvlib/pvlib-python#1476]
**Is your feature request related to a problem? Please describe.**
When using `pvlib.temperature.prilliman()`, if the weather data does not include leap day (e.g., using 2020 PSM3 from `pvlib.iotools.get_psm3()` with the default `leap_day=False`), it returns:

> `NotImplementedError: algorithm does not yet support unequal times. consider resampling your data.`

This could be a common scenario and could be confusing to the user.

**Describe the solution you'd like**
There are several possible solutions:

1. Modify the error text to _always_ say something like `NotImplementedError: algorithm does not yet support unequal times. consider resampling your data. check to make sure your data includes leap day for leap year(s).`
2. Check to see if leap day is missing and tailor the error message accordingly (e.g., add `leap day is missing from your data.` to the error message).
3. Check to see if leap day is missing, automatically fill it in somehow (e.g., repeat Feb 28), then remove it from the results before returning the output time series.
4. Same as 3, but also notify the user that this has happened. Depending on time zone of the weather data, there might be a discontinuity in the resulting smoothed temperature after removing leap day (I think?).

**Describe alternatives you've considered**
Manually fill in leap day or repeat weather data query with leap day included (e.g., use `leap_day=True` with `pvlib.iotools.get_psm3()`).

**Comment by adriesse** [comment]
Interesting problem.  The missing leap day can cause problems in other functions as well.  I would suggest that the best practice would be for the user to insert the leap day into their DataFrame using a method appropriate for their situation.  

Perhaps the default should be changed to ```leap_day=True```?

**Comment by williamhobbs** [comment]
@adriesse Agreed. That's the solution I used - repeat my psm3 weather query with `leap_day=True`. But I do think that the error messaging for `pvlib.temperature.prilliman()` could better help users troubleshoot this issue.

Separately, I also like the idea of changing `pvlib.iotools.get_psm3()` so that the default is `leap_day=True`. Should that suggestion be opened as a separate issue? I wonder if there are any compelling reasons to keep it as `False`, other than the fact that other tools (e.g., NREL SAM) can't handle leap day.

**Comment by AdamRJensen** [comment]
@williamhobbs in regards to:
> Separately, I also like the idea of changing `pvlib.iotools.get_psm3()` so that the default is `leap_day=True`. Should that suggestion be opened as a separate issue? I wonder if there are any compelling reasons to keep it as `False`, other than the fact that other tools (e.g., NREL SAM) can't handle leap day.

Then I recommend that is made a separate issue.

**Comment by AdamRJensen** [comment]
It may also be worth updating the warning admonition to explicitly mention the issue with leap days.
