### ISSUE TITLE
v0.9.2 release plan

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvlib-python#1506]
We plan to release v0.9.2 in the next 3 weeks. @pvlib/pvlib-maintainer please add to the list of PRs to merge and issues to close for v0.9.2.

- ~~[ ] #1468~~  - deferred to v0.9.x
- [x] #1478 
- [x] #1502 
- [x] #1494
- [x] #1511
- [x] #1529
- [x] #1490 
- [x] #1483
- ~~[ ] #1443~~ - deferred to v0.9.x
- [x] #1495
- [x] #1507
- ~~[ ] #1524~~ - deferred to v0.9.x

**Comment by kanderso-nrel** [comment]
Can we drop python 3.6 support in this release?  GitHub Actions is dropping it in MacOS pretty soon, it's way past the NEP29 and Python end-of-life windows, and pvanalytics and rdtools have already moved to >=3.7.

**Comment by mikofski** [comment]
I’m ok to drop 3.6 ✅

**Comment by adriesse** [comment]
I guess I can't edit this myself, but I would like the spectral mismatch PR to go into this release because I would like to use the new functions in an example notebook to accompany a new open data set.

**Comment by wholmgren** [comment]
Releasing on pypi and conda-forge is a couple minutes of work. We should just do it this week whatever we have. It would be really nice to speed up the release cadence and make it less of a big deal.

**Comment by kanderso-nrel** [comment]
Unless someone already has a branch started, I will submit a PR shortly for final 0.9.2 cleanup.  Doesn't mean we can't do some last minute feature merges if the reviewing capacity is available (unfortunately I myself am unlikely to review anything else before the release); I'm just getting antsy about getting this out the door before PVPMC.

**Comment by wholmgren** [comment]
@kanderso-nrel go for it. I'm +1 on #1478 if you think it's ready.

**Comment by cwhanse** [comment]
I edited the checklist to defer PRs that aren't quite ready (either need reviews or author responses). The only one to decide is #1478

**Comment by adriesse** [comment]
As I explained above, it would be nice to have the mismatch feature released fairly soon.  If it is not in this release, how much time do we think might elapse before the next release?

**Comment by wholmgren** [comment]
@adriesse if a pre-release is acceptable then we can make that within minutes of merging the PR. ``git fetch upstream; git rebase upstream/master; git tag v0.9.3-alpha.1; git push upstream v0.9.3-alpha.1;`` wait a few minutes and then ``pip install pvlib --pre``. In principle we can make that a full release - the only complication is the build for the pvlib channel is manual and can be tedious (see the release notes wiki). Finishing the what's new is tedious when the release grows to the current size, but easy if there's only a couple of items. If you want to take on the what's new prep then it would help get the release out the door faster. So, somewhere between minutes, days, and 1-3 months depending on needs/desires/contributions.

**Comment by adriesse** [comment]
I don't think it's so critical that it warrants exceptional actions, but perhaps we could consider 9.3 in 2-3 weeks?  My temperature PR should be done then too.
