### ISSUE TITLE
update `benchmarks/tracking.py` for `SingleAxisTracker` deprecation

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#1508]
**Describe the bug**
`SingleAxisTracker` is deprecated, but the `tracking.py` benchmark still uses it:

https://github.com/pvlib/pvlib-python/blob/3f397ed44075b01f4ba535750356859195a51b2d/benchmarks/benchmarks/tracking.py#L20

**To Reproduce**
run asv tests. or look at the asv quick CI output

**Expected behavior**
no deprecation warnings in the benchmark test suite

**Screenshots**

**Versions:**
 - ``pvlib.__version__``: 0.9. https://github.com/pvlib/pvlib-python/pull/1507

**Comment by Naman-Priyadarshi** [comment]
I wanted to work on the issue! Should i just remove the `time_tracker_singleaxis` function from the benchmark file? 

Also when running `asv dev` I noticed that some of the benchmarking functions were failing, should i open a new issue regarding the same?

**Comment by wholmgren** [comment]
Thanks @Naman-Priyadarshi, that would be great. Yes to both of your questions.
