### ISSUE TITLE
sam files are not available

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#152]
https://sam.nrel.gov/sites/sam.nrel.gov/files/sam-library-cec-inverters-2015-6-30.csv

and

https://sam.nrel.gov/sites/sam.nrel.gov/files/sam-library-sandia-modules-2015-6-30.csv

return HTTP/1.1 404 - Not Found

**Comment by yotf** [comment]
yes, they seem to have change url.

Sandia module can now be found at https://sam.nrel.gov/sites/default/files/sam-library-sandia-modules-2015-6-30.csv

CEC inverters at https://sam.nrel.gov/sites/default/files/sam-library-cec-inverters-2015-6-30.csv

**Comment by wholmgren** [comment]
That's unfortunate. We'll need to fix this before the EPRI modeling workshop, so that probably means a 0.3.2 release early next week. Maybe we should take care of #52 at the same time.

**Comment by mikofski** [comment]
I'm working on a pull request to just get the data from the pvfree api. And also updating pvfree with modules from both Sandia and cec.

I think this is a better solution than static links or files.

Sunpower will host pvfree

**Comment by wholmgren** [comment]
@mikofski I'm interested in your PR, just trying to get things working again as quickly as possible. Feel free to make a new issue for the pvfree api, of course.

**Comment by uvchik** [comment]
@mikofski : A PR to get the data from pvfree is really a good idea :+1:
