### ISSUE TITLE
solarpositions benchmarking functions failing

### ISSUE THREAD

**Issue by Naman-Priyadarshi** [pvlib/pvlib-python#1526]
**Describe the bug**
`solarposition.SolarPosition.time_pyephem` , `solarPosition.time_sun_rise_set_transit_ephem` and `SolarPositionCalcTime.time_calc_time` benchmarking functions are failing, the fucntions are a part of solarposition.py

**To Reproduce**
1. Go to 'benchmarks'
2. Open in terminal
3. Run asv using 'asv dev'

**Expected behavior**
The benchmarks should run without any errors.

**Screenshots**
![solarpoisition](https://user-images.githubusercontent.com/77211855/184551627-a1c263fc-677a-4cae-aa67-21064f27b806.png)

**Versions:**
 - python: 3.8.10
 - asv: 0.5.2

**Comment by jules-ch** [comment]
you're missing pyephem to run the full benchmark.

`pip install ephem`

**Comment by kanderso-nrel** [comment]
Yeah this seems like a local problem; the nightly job seems to be running those benchmarks without trouble: https://pvlib-benchmarker.github.io/pvlib-benchmarks/#solarposition.SolarPosition.time_pyephem?x-axis-scale=date

@Naman-Priyadarshi I think you can specify `--show-stderr` to get additional info beyond just `failed`.

**Comment by Naman-Priyadarshi** [comment]
yes, the problem was because numba and pyephem was missing on my system, thank you @kanderso-nrel @jules-ch
