### ISSUE TITLE
v0.9.3 release plan

### ISSUE THREAD

**Issue by adriesse** [pvlib/pvlib-python#1545]
Do we need one of these yet?

**Comment by kanderso-nrel** [comment]
@adriesse do you have a specific deadline for this release?  I suspect that we'll drag our feet here without one. 

Seems like the main things we want to get into this release are @adriesse's two PRs:
- [ ] #1463
- [ ] #1524

Others that I'd like to see merged but are less time sensitive:
- [ ] #1468 -- This is very close, just one open [question about units](https://github.com/pvlib/pvlib-python/pull/1468#discussion_r924785711)
- [ ] #1542 

I'd be okay with bumping the other items on the 0.9.3 [milestone](https://github.com/pvlib/pvlib-python/milestone/37) to the next release.

**Comment by adriesse** [comment]
I think that Sept. 15 would make a suitable target date.  I don't want too push too hard because the reviews and discussions are important.  But if there is broad agreement that these PR's are ready then it could be earlier.

**Comment by kanderso-nrel** [comment]
@pvlib/pvlib-maintainer, is there anything else people would like to see included in 0.9.3?  Anticipating an answer of "no", I have moved all the 0.9.3 milestone items to [0.9.4](https://github.com/pvlib/pvlib-python/milestone/38).  I'll open a finalization PR shortly.

**Comment by cwhanse** [comment]
I can do it.

**Comment by mikofski** [comment]
Thanks for driving it home. I think the release is ready?
