### ISSUE TITLE
Add iam function based on Schlick 1994

### ISSUE THREAD

**Issue by adriesse** [pvlib/pvlib-python#1564]
**Is your feature request related to a problem? Please describe.**

Equation 15 in Schlick 1994 gives an efficient approximation equation for surface reflectance as a function of incidence angle that could be used as the basis for an *iam* function.

Equation 4 in Xie 2022 gives an analytical integration of the Schlick equation over the portion of an isotropic sky that is visible from a tilted surface.

Equation 6 in Xie 2022 gives an analytical integration of the Schlick equation over the portion of an isotropic ground that is visible from a tilted surface.

**Describe the solution you'd like**
A new function called ```schlick``` in the ```iam``` module.  The equation would be:

```
iam = 1 - (1 - cos(aoi)) ** 5
```
This equation has no parameters for fitting to iam measurements or to represent different types of PV module glass.

A second new function called ```schlick_diffuse``` in the ```iam``` module (similar to the function ```martin_ruiz_diffuse```) which implements Equations 4 and 6 from Xie 2022 (excluding the empirical weighting factor *w*, or in other words, with *w=1*).

**References**

Schlick, C. An inexpensive BRDF model for physically-based rendering. Computer graphics forum 13 (1994).
Xie, Y. et al. The 'Fresnel Equations' for Diffuse radiation on Inclined photovoltaic Surfaces (FEDIS). J.RSER (2022)

**Comment by adriesse** [comment]
Extinction in the glass is negligible so we can ignore that part.  The point is that when the original Schlick reflectance function is changed to a normalized iam function, the refractive index (which is only used to determine the normal incidence reflectance) drops out.  Thus to see refractive index reappear in the sky-integrated iam is, well, surprising.

**Comment by cwhanse** [comment]
> (Also, github comments [now support mathjax](https://github.blog/2022-05-19-math-support-in-markdown/)!) 

Nice!

**Comment by adriesse** [comment]
Please note that I have expanded this feature request to include a function for the diffuse iam factors.  These two functions could in fact be done in a separate PR to form a base layer for FEDIS.

I actually wrote and ran them and compared to schlick integrated with marion and they converge well.
