### ISSUE TITLE
Add in component sum equations for GHI, DHI, and DNI into the pvlib.irradiance module.

### ISSUE THREAD

**Issue by kperrynrel** [pvlib/pvlib-python#1565]
Right now, we have code for calculating GHI, DHI, and DNI via the component sum equations in pvlib/pvanalytics, and doing nighttime corrections (https://github.com/pvlib/pvanalytics/pull/163). @cwhanse and @kanderso-nrel  suggested we port over the 3 component sum equations to the pvlib.irradiance module, and call them directly in pvlib/pvanalytics before applying a nighttime filter. This would require taking the guts out of pvlib.modelchain.ModelChain._complete_irradiance and creating a new function in pvlib.irradiance.

**Comment by cwhanse** [comment]
Said differently: we're proposing to promote the `ModelChain` method [_complete_irradiance](https://github.com/pvlib/pvlib-python/blob/bdbaf4c238ce2b373d04af48193b14659662cef1/pvlib/modelchain.py#L1301) to a public function in `pvlib.irradiance`.
