### ISSUE TITLE
[ENH][DOC] add instructions to existing users how to migrate their locar repos to main branch

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#1587]
**Is your feature request related to a problem? Please describe.**
see #1584 - we plan to change the name of master branch to main, if we do, links on GH are updated, but users will have to follow directions to update their local repos

**Describe the solution you'd like**
Add a temporary section to the docs? announce on google groups

**Describe alternatives you've considered**
do nothing, just announce on g-group, point users to GH docs

**Additional context**
IMHO, I have dragged my feet too long on this, just need to do it asap. It will be confusing for a few days, then done

**Comment by mikofski** [comment]
I'm thinking something on this page: https://pvlib-python.readthedocs.io/en/stable/contributing.html

**Comment by wholmgren** [comment]
> do nothing, just announce on g-group, point users to GH docs

This. The only people that will be effected are those that can deal with it with reasonable effort. No need to reinvent GH docs.

**Comment by mikofski** [comment]
@wholmgren then I suggest just go ahead and do it now. I'll post something on google groups linking to the discussion or the GH help docs

**Comment by mikofski** [comment]
FYI: @pvlib/pvlib-core - I can't make the change, I can't see the settings tab in pvlib

**Comment by cwhanse** [comment]
@mikofski simply rename `master` branch to `main`?

**Comment by mikofski** [comment]
I believe we can follow the steps here: https://github.com/github/renaming#renaming-existing-branches

![image](https://user-images.githubusercontent.com/1385621/200657590-76c55a60-333b-498e-911e-bbc69fe31475.png)

and here: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch
![image](https://user-images.githubusercontent.com/1385621/200657709-0b4b7ffa-089c-40a6-8c7a-f193bb90fe77.png)

![image](https://user-images.githubusercontent.com/1385621/200657730-3a5507a3-de73-4834-a9db-eb5cc3ab3103.png)

then users do what it says here: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes

```bash
$ git branch -m OLD-BRANCH-NAME NEW-BRANCH-NAME
$ git fetch origin
$ git branch -u origin/NEW-BRANCH-NAME NEW-BRANCH-NAME
$ git remote set-head origin -a
$ git remote prune origin
```

**Comment by mikofski** [comment]
Here is what GH says when renaming master to main:
![image](https://user-images.githubusercontent.com/1385621/201187318-97800258-9e5b-4cf6-81bf-aa7192970035.png)
* Will update 36 pull requests targeting this branch across 23 repositories.
* Will update 1 branch protection rule that explicitly targets master.

instructions to update local environments:
```
git branch -m master <BRANCH>
git fetch origin
git branch -u origin/<BRANCH> <BRANCH>
git remote set-head origin -a
```

**Comment by mikofski** [comment]
OK, it's done. All contributors please update your local environments following GH instructions.

**Comment by mikofski** [comment]
note replace <BRANCH> with "main" so:
```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
git remote prune origin
```

**Comment by mikofski** [comment]
@pvlib/pvlib-core  here's a wrinkle, my personal fork is not auto updated, I see this lovely GH message
![image](https://user-images.githubusercontent.com/1385621/201189349-264f1d0b-21ee-4e7b-ae4f-f03da3248b1e.png)
so that's another step, to rename master branch in my personal fork as well!

**Comment by kanderso-nrel** [comment]
> git fetch origin

Probably most people will have `origin` set to their own fork, right?  I have `kanderso-nrel/pvlib-python` as `origin` and `pvlib/pvlib-python` as `upstream`.  I think people will need to rename the branch in their fork on github before these local commands are applicable.

**Comment by mikofski** [comment]
Here's what the renaming process looked like for me, with my mistakes included 😉 😜 
![image](https://user-images.githubusercontent.com/1385621/201190382-c014031d-300d-428c-af5e-742ef2ee114a.png)
anyway, not too painful and all good now 👍 😺

**Comment by mikofski** [comment]
GH really holding our hands here, saw this on upstream:
![image](https://user-images.githubusercontent.com/1385621/201190778-16642f63-bdd1-4177-b3f7-938f1f019a4e.png)

**Comment by mikofski** [comment]
@kanderso-nrel  I had one more wrinke, after updating origin and my local environment, I still had this:
![image](https://user-images.githubusercontent.com/1385621/201191625-c9346be1-08e1-4246-a517-5e349fa5279a.png)

So I reran the GH commands with "upstream" as you suggested 
![image](https://user-images.githubusercontent.com/1385621/201191737-b578bf48-4ece-4458-8fec-f447064aeccb.png)

now all good
![image](https://user-images.githubusercontent.com/1385621/201191915-b9ab0628-1745-473c-a2f1-1ef2c427b263.png)
