### ISSUE TITLE
`iotools.get_psm3` may need some updates for the new 2021 data

### ISSUE THREAD

**Issue by kandersolar** [pvlib/pvlib-python#1591]
The NSRDB team is currently rolling out data for 2021 as well as updated data for previous years using their latest and greatest methodology.  The new datasets will be served up by a new API endpoint (see https://github.com/NREL/developer.nrel.gov/pull/280#issuecomment-1285744115).  As I understand it, the old endpoints will continue to function but won't provide the new data.  It's not yet clear where the TMY et al data will live.

It seems likely that we will want to make some change to `pvlib.iotools.get_psm3` so that it can access this new endpoint, but before doing much planning on our side I think it makes sense to wait a week or two for the data deployment to complete and the API docs to reach their final state.  I just wanted to file an issue while it's still fresh from today's NSRDB webinar.  I'll label this for 0.9.4 for now but depending where we settle it might make more sense to wait for 0.10.0.

Separately from this new dataset, we should also consider adding `fill_flag` to the default list of requested fields.

cc @williamhobbs and @wholmgren

**Comment by kanderso-nrel** [comment]
>  As I understand it, the old endpoints will continue to function but won't provide the new data.

It seems this is only true for the 30/60 minute datasets; the 5-minute data endpoint already accessed by `get_psm3()` is now returning updated values (see https://github.com/NREL/developer.nrel.gov/issues/293#issuecomment-1387224054) and causing `test_psm3.py::test_get_psm3_5min` to fail: https://github.com/pvlib/pvlib-python/actions/runs/3954519076/jobs/6771938656#step:6:33

I volunteer to submit a PR to close this issue but want a clearer understanding of what data is coming from which endpoints first.
