### ISSUE TITLE
v0.9.4 release plan

### ISSUE THREAD

**Issue by kanderso-nrel** [pvlib/pvlib-python#1608]
Open candidates for inclusion:
- [x] #1558 and #1619
- [x] #1585
- [x] #1598
- [x] #1602
- [x] #1594 and #1595
- [x] #1603 and #1606
- [x] #1613 and #1615
- [x] #1617
- [x] #1618

Things to defer:

- #1323
- #1345 and #1433
- #1405
- #1443
- #1556
- #1083 and #1080
- #1591
- #1573

@pvlib/pvlib-maintainer please edit as you see fit.  Any objection to choosing the ~15th~ ~19th~ 20th as target release date?

**Comment by cwhanse** [comment]
List looks OK to me.

**Comment by adriesse** [comment]
> Should we add #1617 and #1618 to the list? They are small and easy to review but are not currently tagged with a milestone.

Only do as much as you can.  I'm trying hard to drift away...

**Comment by wholmgren** [comment]
I'm -1 on last minute API changes to well-loved functions. Seems to me that deprecation of `pvwatts` functions and introduction of `pvarray.py` might require more thought than we can put in at the last minute. I'm only now coming up for air after the end of year rush, so apologies for not engaging sooner. I'll bite my tongue if you all want to move ahead with what's already in motion.

**Comment by kanderso-nrel** [comment]
@wholmgren I don't mind revisiting any decisions here.  To clarify, are you suggesting (1) reverting #1558 and (2) adding the new functionality in #1602 to `pvsystem.py` instead of creating a new module?

**Comment by wholmgren** [comment]
That's one path forward. Another option is reverting #1558 but proceeding with #1602 as is. Another is delaying the release until we have the major API right - maybe that's a day, maybe that's a month.

**Comment by adriesse** [comment]
@wholmgren could you be more specific about what you do and don't like?  Top two scenarios for moving forward?

**Comment by wholmgren** [comment]
My recommendations are:

1. Quickly engage with Kevin's concern on module name https://github.com/pvlib/pvlib-python/issues/1544#issuecomment-1335696024 but recognizing that it's not a big deal to change this if we need to (I'd do it without deprecation going to 0.10).
2. Merge #1602
3. Do not add more functionality to `pvarray.py` (or whatever name we go with) at this time.
4. Consider if #1558 should be reverted until there is a better home for `pvwattsv5_dc` and `pvwattsv5_losses`. If the answer is "revert", then commit to finding those homes in the next month. If the answer is "keep it", then be comfortable with a second round of deprecations for those functions.
5. Release

**Comment by kanderso-nrel** [comment]
I'm okay with keeping `pvarray.py` and possibly renaming it later.  I'm also okay with reverting #1558 and will submit a PR for that shortly.

**Comment by adriesse** [comment]
Sounds like a plan!
