### ISSUE TITLE
Dynamic delta T for solar position calculation

### ISSUE THREAD

**Issue by alorenzo175** [pvlib/pvlib-python#165]
The solar position algorithm from NREL needs a delta t parameter to account for the changes in Earth's rotation. That number can change by a few seconds over many months, so maybe it is worth putting in a function to get the data from the [USNO](http://www.usno.navy.mil/USNO/earth-orientation/eo-products) or at least use [an equation](http://eclipse.gsfc.nasa.gov/SEcat5/deltatpoly.html) from NASA.

**Comment by wholmgren** [comment]
I think using only a couple of the equations would be easiest and most reliable.

**Comment by wholmgren** [comment]
@DanRiley added some delta T calculations to the matlab library in sandialabs/MATLAB_PV_LIB#1.

**Comment by wholmgren** [comment]
closed by #240
