### ISSUE TITLE
Urgent: Update project size

### ISSUE THREAD

**Issue by henrykironde** [pvlib/pvlib-python#1663]
Currently, you have "Long (350hr) or Medium (175hr) depending on student expertise,"  but Google needs us to specify either 350 or 175 for logistical purposes.

https://github.com/pvlib/pvlib-python/wiki/GSoC-2023-Projects

**Comment by AdamRJensen** [comment]
Hi @henrykironde 

To me, it seems that all of our project ideas state the length (175 or 350 hours), so I'm not quite sure what it is that you are asking?

![image](https://user-images.githubusercontent.com/39184289/218705848-d801cbf6-cbe5-4ab2-bef4-179b7b193c69.png)

**Comment by henrykironde** [comment]
Choose one.

**Comment by AdamRJensen** [comment]
Thanks for clarifying @henrykironde. I have gone ahead and updated the project ideas list.

@kanderso-nrel Please check if you agree with my changes.
