### ISSUE TITLE
Clarify f_x

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvlib-python#1677]
In some private functions of `pvlib.bifacial.infinite_sheds`, the parameter `f_x` is described as

```
    f_x : numeric
        Fraction of row slant height from the bottom that is shaded from
        direct irradiance.
```

In other public functions, the description is

```
    f_x : numeric
        Fraction of row slant height from the bottom that is shaded. [unitless]
```

For users trying to understand this algorithm, the different definitions can be confusing, because saying just "shaded" could mean shaded from diffuse irradiance by the adjacent row.

**Describe the solution you'd like**
Use the longer description for all instances of `f_x`.

**Comment by ayeankit** [comment]
hey @cwhanse , is this still open?

**Comment by cwhanse** [comment]
@ayeankit yes, it is open
