### ISSUE TITLE
get_psm3 with tmy will not ignore interval

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#1702]
**Describe the bug**
docs say if `names='tmy'` then interval is ignored, but the nrel api raises an HTTPError

**To Reproduce**
```python
d, m = pvl.iotools.get_psm3(
    latitude=38.8, longitude=-121.2,
    api_key='DEMO_KEY', email='email@example.com',
    names='tmy', interval=5)
```

**Expected behavior**
NREL API ignores interval

**Screenshots**
![image](https://user-images.githubusercontent.com/1385621/226816522-640aa577-9633-4cb7-ab85-fbfe80644ebb.png)

**Versions:**
 - ``pvlib.__version__``: 1.5.2
 - ``pandas.__version__``: 0.9.4
 - python: 3.8.15

**Additional context**
I think the documentation should be updated?

**Comment by AdamRJensen** [comment]
I can confirm this issue.

The current parameter description reads:

> interval (int, {60, 5, 15, 30}) – interval size in minutes, must be 5, 15, 30 or 60. Only used for single-year requests (i.e., it is ignored for tmy/tgy/tdy requests).

Should be updated to something along the lines of:
> interval (int, {60, 5, 15, 30}) – interval size in minutes, must be 5, 15, 30 or 60. Must be 60 for typical year requests (e.g., tmy/tgy/tdy).
