### ISSUE TITLE
Adding custom inverter (Kostal Plenticore Plus)

### ISSUE THREAD

**Issue by c0nr3f** [pvlib/pvlib-python#1709]
How can I add an inverter, that is neither present in the database nor on the nhrel website ? I use a Kostal Plenticore plus and besides the typical values like the voltages and max power and current, I don't know where to get C-values from. Any suggestions or some kind of tool that can be used to calculate these?

**Comment by cwhanse** [comment]
@c0n3f can you repost your question in the Discussions section? Happy to answer it there. We use Issues to track bug reports, requested improvements, rather than questions about usage.
