### ISSUE TITLE
Model Chain PVwatt simple typo

### ISSUE THREAD

**Issue by cpullium** [pvlib/pvlib-python#1731]
In the example of the Model Chain the wrong variable is given for inverter parameter. 
![image](https://github.com/pvlib/pvlib-python/assets/17179784/5cfaeccc-4712-445b-9be7-3c5f7265f185)

It should be pdc0... (dc not ac)

**Comment by kandersolar** [comment]
@cpullium want to submit a PR to fix that typo?
