### ISSUE TITLE
Is there interest in implementing a .pan or .ond reader into iotools?

### ISSUE THREAD

**Issue by ckrening** [pvlib/pvlib-python#1747]
I find that .pan or .ond files are the most widely/easily available files containing parameters to use with the existing module and inverter models in PVlib. I have created read and parse functions to streamline getting those parameters into my code. 

Would enough people find this feature useful that I should create a pull request?

**Comment by cwhanse** [comment]
@ckrening there is significant interest in having this capability. Pull requests welcome :)

**Comment by kandersolar** [comment]
Yes!  This has been discussed several times over the years, but nobody has taken the initiative to do it.  Here are some related discussions, for reference:
- PAN and OND readers on the draft roadmap: https://github.com/pvlib/pvlib-python/discussions/1581
- https://github.com/pvlib/pvlib-python/issues/1002#issuecomment-658363265
- https://github.com/pvlib/pvlib-python/issues/1094#issuecomment-1086411784
- https://groups.google.com/g/pvlib-python/c/PDDic0SS6ao/m/Z-WKj7C6BwAJ

**Comment by mikofski** [comment]
Any chance you can reuse our port @frivollier https://github.com/frivollier/pvsyst_tools

**Comment by ckrening** [comment]
Thank you all for the suggestions! I went ahead and created a pull request #1749 using the code I had already created. I took a different approach than the suggested #1002 and #1094. There are trade-offs for either method but, please review and we can discuss what is best!
