### ISSUE TITLE
Changed Inverter. Now results are negative?

### ISSUE THREAD

**Issue by dandelaney22** [pvlib/pvlib-python#1760]
Hi all,

I am looking for an annual energy output form a project. I want to use the correct inverter.

I changed my inverter from ['ABB__MICRO_0_25_I_OUTD_US_208__208V_'] (default) to ['Chint_Power_Systems_America__CPS_SCA60KTL_DO_US_480__480V_'].

This was the only change. 
My annual energy output is now heavily negative. Every hourly data point is negative.
Each non-daylight hour reads a -18 output that may come from the pnt input of 18. 'self consumption' (AC power consumed by inverter at night (night tare) to maintain circuitry required to sense the PV array voltage- from documentation)

Any ideas what is going on? Thanks.

Below are the specs on the two inverters.
![image](https://github.com/pvlib/pvlib-python/assets/101663084/228ec17c-a3b6-49a8-bc92-009b04bbd44c)
![image](https://github.com/pvlib/pvlib-python/assets/101663084/8ac158b7-0704-4d75-a4f5-97b0bff7d327)

**Comment by cwhanse** [comment]
Can you repost this question to the pvlib google group? https://groups.google.com/g/pvlib-python

I am almost certain this isn't an issue with pvlib code, you need to redefine your arrays. The Chint inverter is 60kW, with nominal DC input voltage 730, so you must have sufficient modules in series in the arrays. The ABB inverter is a micro-inverter that is fed by a single module.
