### ISSUE TITLE
Outdated pvpmc.sandia.gov links in user guide.

### ISSUE THREAD

**Issue by reepoi** [pvlib/pvlib-python#1788]
**Describe the bug**
The pvpmc.sandia.gov website was updated, breaking these links in the pvlib docs: the PV_LIB Matlab help webpage [here](https://pvlib-python.readthedocs.io/en/stable/user_guide/comparison_pvlib_matlab.html), and PVPMC single diode page [here](https://pvlib-python.readthedocs.io/en/stable/gallery/iv-modeling/plot_singlediode.html#sphx-glr-gallery-iv-modeling-plot-singlediode-py).

**Comment by kandersolar** [comment]
@jsstein the PVLIB_MATLAB help pages don't seem to have gotten migrated; was that intentional?

For reference, here's an archive.org snapshot of those pages on the old site: http://web.archive.org/web/20230321205806/https://pvpmc.sandia.gov/PVLIB_Matlab_Help/
