### ISSUE TITLE
Dirint application problem

### ISSUE THREAD

**Issue by thokpp** [pvlib/pvlib-python#1805]
Hello Guys, 
I have a problem with the application of dirint which is : 
-> Dirint not give me the right 'DNI' when i use it like this 
<img width="549" alt="image" src="https://github.com/pvlib/pvlib-python/assets/78738099/e60c03aa-53c1-4211-a51c-035a266e3925">
=> dirint = pvlib.irradiance.dirint(ghi, zenith, times, pressure=dataframe['barometric_pressure'],
        temp_dew=dataframe['temp_dew'])
Whereas, erbs gives me the right value.
I don't understand why. If you can help me it will be nice and i will be very thanksfull.
Thank you for your reading guys =)

**Comment by cwhanse** [comment]
Hi @thokpp can you repost this in the Discussions or on the pvlib google group? We use Issues to track problems with the code and I suspect here it's an issue with the input data.

Can you share the first line of your data? Please check that the pressure is in units of Pa, and temperature is in Celsius.
