### ISSUE TITLE
Issue with Data NaN

### ISSUE THREAD

**Issue by Catherine1030** [pvlib/pvlib-python#1835]
Hello, previously I used pvlib to forecast the weather from August 5th to August 10th, and the result showed NaN (Not a Number) in the data source, preventing the data from being exported. What could be the reason for this? Will this be resolved?

**Comment by cwhanse** [comment]
@Catherine1030 can you indicate which version of pvlib you are using? pvlib/forecast.py was deprecated since v0.9 and has been removed with v0.10. I'm afraid it became a burden to maintain.
