### ISSUE TITLE
ST-AR model

### ISSUE THREAD

**Issue by MichelangeloConserva** [pvlib/pvlib-python#1896]
Hello,

How can I use `pvlib` to reproduce the results from the [High-Resolution PV Forecasting from Imperfect Data: A Graph-Based Solution](https://www.mdpi.com/1996-1073/13/21/5763) ?

In the paper, they mention  that the model is implemented in the package but I cannot seem to find it.

Thanks,
Michelangelo

**Comment by cwhanse** [comment]
I believe the author is referring only to calculation of the clear-sky profile using pvlib.clearsky.Ineichen. Pvlib hasn’t ever had a Spatio-temporal forecasting function.
________________________________
From: Michelangelo Conserva ***@***.***>
Sent: Saturday, October 21, 2023 4:18:17 AM
To: pvlib/pvlib-python ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [pvlib/pvlib-python] ST-AR model (Issue #1896)


Hello,

How can I use pvlib to reproduce the results from the High-Resolution PV Forecasting from Imperfect Data: A Graph-Based Solution<https://www.mdpi.com/1996-1073/13/21/5763> ?

In the paper, they mention that the model is implemented in the package but I cannot seem to find it.

Thanks,
Michelangelo

**Comment by MichelangeloConserva** [comment]
Oh I see, thanks for the quick response.
