### ISSUE TITLE
auto tracking solar panel ,

### ISSUE THREAD

**Issue by Akkip07** [pvlib/pvlib-python#1917]
i want a azimuth angle azenith angle and vs time in the matlab by solar position tracking algorithm
 where i need to change only longitude and lattitude for to resolve issue

**Comment by Akkip07** [comment]
i want a matlab script where i need to change only longitude and lattitude for to resolve issue

**Comment by kandersolar** [comment]
Hi @Akkip07, this repository uses Python, not MATLAB.  You can find MATLAB code for solar position and tracking calculations here: https://github.com/sandialabs/MATLAB_PV_LIB
