### ISSUE TITLE
Typo "modelt" in function signature pvlib.irradiance.perez

### ISSUE THREAD

**Issue by mangecoeur** [pvlib/pvlib-python#196]
The function uses `modelt` instead of `model`:

`pvlib.irradiance.perez(surface_tilt, surface_azimuth, dhi, dni, dni_extra, solar_zenith, solar_azimuth, airmass, modelt='allsitescomposite1990')`

should be

`pvlib.irradiance.perez(surface_tilt, surface_azimuth, dhi, dni, dni_extra, solar_zenith, solar_azimuth, airmass, model='allsitescomposite1990')`

http://pvlib-python.readthedocs.io/en/latest/modules.html#pvlib.irradiance.perez

**Comment by wholmgren** [comment]
Yes, I've noticed that before too. Feel free to submit a pull request.

**Comment by mangecoeur** [comment]
PR sent
