### ISSUE TITLE
Update Comparison with PVLIB MATLAB

### ISSUE THREAD

**Issue by AdamRJensen** [pvlib/pvlib-python#2010]
The description contained in the [Comparison with MATALB](https://github.com/pvlib/pvlib-python/blob/main/docs/sphinx/source/user_guide/comparison_pvlib_matlab.rst) section is very outdated.

For example, it is stated that:
> We'd all like to keep the core functionality of the Python and MATLAB projects synchronized,

This makes it sound like the MATLAB and python version are at somewhat similar stages, whereas my impression is that the MATLAB version receives very little maintenance and development and is thus far behind pvlib-python.

@cwhanse are you up for updating this description?

Alternatively, do we even want an entire page dedicated to pvlib MATLAB? Perhaps this section could be replaced by an additional sentence or two in the [History and acknowledgement](https://pvlib-python.readthedocs.io/en/stable/user_guide/package_overview.html) section?

**Comment by cwhanse** [comment]
We should update that. I'll draft a PR. I may end up removing that page and adding a sentence as you suggest.

**Comment by AdamRJensen** [comment]
It'd also be nice to remove the MATLAB comment in the [contributing section](https://github.com/pvlib/pvlib-python/blob/main/docs/sphinx/source/contributing.rst):
> If you have MATLAB experience, you can help us keep pvlib-python up to date with PVLIB_MATLAB or help us develop common unit tests. For more, see https://github.com/pvlib/pvlib-python/issues/2 and https://github.com/pvlib/pvlib-python/issues/3.
