### ISSUE TITLE
Using updated Sam datase 

### ISSUE THREAD

**Issue by apct69** [pvlib/pvlib-python#2018]
Hi, I'm new to using PVlib for master research. 
I was wondering what is the best way to use an updated csv file (regarding modules and inverters, for example). 
My default installation has a 2019 file. 
By downloading the new database from the SAM website. 

[https://raw.githubusercontent.com/NREL/SAM/develop/deploy/libraries/CEC%20Modules.csv](url)
I wanted to add it this way, but the program continues to use the 2019 file. 
`sandia_modules = pvlib.pvsystem.retrieve_sam('CECMod','C:\\Users\XXXXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pvlib\data\CECMod.csv')`

By pasting the new database under the name of the old one, I have the new module references. 

Do you have any more information on how this function works? 
[https://pvlib-python.readthedocs.io/en/v0.4.3/generated/pvlib.pvsystem.retrieve_sam.html](url)

Thanks a lot !

**Comment by echedey-ls** [comment]
Hmm, from looking at the code, when `name=` is given, it ignores `path` silently. Just drop the first argument.

That code line should be `retrieve_sam(path="https://raw.githubusercontent.com/NREL/SAM/develop/deploy/libraries/CEC%20Modules.csv")`

@pvlib/maintainers, I think both the documentation and code need a bit of rework to avoid confusion. In fact, I think this should be a keyword-only function.

**Comment by echedey-ls** [comment]
Btw @apct69 , you were looking at v0.4.3 documentation (from 2016). We are now at v0.10.4 - there are a few things that have changed since then.

Please follow this link: https://pvlib-python.readthedocs.io/en/stable/

**Comment by apct69** [comment]
Thanks for the fast response, i will be able to choose my favorite panels then :)

I will be looking to the new version of the documentation to learn the use of PVLIB!
