### ISSUE TITLE
Python 3.7 not available for macOS v14 in GitHub Actions

### ISSUE THREAD

**Issue by kandersolar** [pvlib/pvlib-python#2023]
Until recently, `macos-latest` referred to version 12.7.4: https://github.com/pvlib/pvlib-python/actions/runs/8786214399/job/24108552235?pr=2006#step:1:4

Now it refers to version 14.4.1: https://github.com/pvlib/pvlib-python/actions/runs/8880987265/job/24382296170?pr=2022#step:1:4

See also this github blog post regarding macOS 14:  https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/

The immediate relevance for us is that python 3.7 is not available in version 14, so the `macos-latest, python 3.7` matrix job is now failing: https://github.com/pvlib/pvlib-python/actions/runs/8880987265/job/24382296170

I see three alternatives:
1) Modify our testing configuration so that we stick with the older version of macOS.
2) Keep the newer version for all macOS jobs except python 3.7, and use the older version only for that.
3) Drop the python 3.7 job (see #1975).

**Comment by cwhanse** [comment]
My vote is for option 3, which I think is what will happen (eventually) if we choose 2 or 1.
