### ISSUE TITLE
Discontinuous Diffuse Sky Irradiance from Perez Model

### ISSUE THREAD

**Issue by jmobrecht** [pvlib/pvlib-python#2043]
**Describe the bug**
Using PVLib functions, I calculate a clear sky irradiance and find small ~1% discontinuities originating from the Perez model.  I have isolated the issue in the source code and can correct the issue with only a few additional lines and without any cost in computational time.

**To Reproduce**
1. Calculate solar position using pvlib.solar_position.get_solarposition
2. Calculate air pressure pvlib.atmosphere.alt2pres
3. Calculate airmass pvlib.atmosphere.get_relative_airmass
4. Calculate Linke Turbidity pvlib.clearsky.lookup_linke_turbidity
5. Calculate DNI_extra pvlib.irradiance.get_extra_radiation
6. Calculate GHI, DNI, DHI from pvlib.clearsky.ineichen

From the above inputs, I calculate the diffuse sky irradiance using the pvlib.irradiance.perez model.  The output results show a sharp discontinuity, which arises from calculation of the F1 & F2 coefficients in the 'perez' function.  When an interpolation is used, the discontinuity is eliminated.

**Expected behavior**
Attached is an image showing the discontinuity of the diffuse sky irradiance from PVLib (blue) and the irradiance from my solution (JMO - red).
![pvlib_error](https://github.com/pvlib/pvlib-python/assets/7855982/38f317fd-abde-49ed-a180-ae9fa6515971)

**Solution**
![image](https://github.com/pvlib/pvlib-python/assets/7855982/dd3f53fb-96bf-4154-89f6-2af2779b0f34)

**Note**
Just spoke with PVLib maintainer Adam who told me that this solution is already solved ([Perez-Driesse model](https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.irradiance.perez_driesse.html))... regardless I'm posting my solution for anyone who wants to use it (see comparison below)

**Comparison**
The edited code runs just as fast as (and sometimes faster than) the original 'perez' code, while the 'perez-driesse' code runs 50% slower than 'perez' (on my laptop).

**Comment by AdamRJensen** [comment]
Thanks for bringing this up @jmobrecht.

Would it be an idea to add a warning admonition on the Perez documentation page, stating that there are small discontinuities and point to the Perez-Driesse model?

**Comment by kandersolar** [comment]
These minor discontinuities in the output of the Perez model are a frequent source of surprise.  I think a brief explanatory note in the docstring is a good idea.
