### ISSUE TITLE
Weird output results (poa_global)

### ISSUE THREAD

**Issue by Typezero-shanxi** [pvlib/pvlib-python#2090]
Why is poa_global greater than ghi?
When I run the official case (https://pvlib-python.readthedocs.io/en/stable/gallery/adr-pvarray/plot_simulate_system.html#sphx-glr-gallery-adr-pvarray- plot-simulate-system-pay), I cannot understand the results.
Is there any physics or maths behind this that can be explained?

![image](https://github.com/pvlib/pvlib-python/assets/156188273/57d38546-6d2c-4bd4-9f9f-a50ad20b67f5)
Best regard!!!!!!!!

**Comment by echedey-ls** [comment]
I think it is a misunderstanding of the terms. You can check out the mini-definitions we have on the [Variables and Symbols page](https://pvlib-python.readthedocs.io/en/stable/user_guide/variables_style_rules.html).

GHI is the global horizontal irradiance, i.e., the irradiance that gets to an horizontal surface (more often the terrain than a PV collector).
https://pvpmc.sandia.gov/modeling-guide/1-weather-design-inputs/irradiance-insolation/global-horizontal-irradiance/

On the other hand, POA_global is all the irradiance that gets to a collector. You would usually tilt a collector to minimize the angle of incidence of the beam component. See https://pvpmc.sandia.gov/modeling-guide/1-weather-design-inputs/plane-of-array-poa-irradiance/ and subsequent sections.

From the equations point of view:

- $GHI = DHI + DNI cos(\theta_Z)$, where $\theta_Z$ is the solar zenith.
- $POA_{global} = POA_{direct} + POA_{sky-and-ground-diffuse}$ where the direct component will be often the most important. $POA_{direct} = DNI cos(AOI)$. A designer will usually try to make AOI, the angle of incidence, as small as possible (face the surface to the Sun essentially) so it gets more irradiance ===> usually, $AOI < \theta_Z$ for the Sun above horizon.

The point of $DHI$ and $DNI$, and/or $GHI$ is that they can be measured in a normalized way everywhere, and POA components depend heavily on the orientation of the collector surface. So translating the former values to POA components has more maths involved (transposition, DNI estimation, ...; depends on input data) than measuring the available irradiance resource (DHI, DNI, GHI).

I suggest you some references:
- https://pvpmc.sandia.gov/modeling-guide/
- https://www.pveducation.org/

Feel free to close if cleared up😃
