### ISSUE TITLE
Unused fixture input in a fixture

### ISSUE THREAD

**Issue by echedey-ls** [pvlib/pvlib-python#2105]
Was the following piece of code supposed to use it's input?

https://github.com/pvlib/pvlib-python/blob/55e0a36fac1e3931b92f5f11508f6c09d903e0cc/pvlib/tests/test_irradiance.py#L61C1-L65C30

My suggestion is to remove the input parameter; I've run the tests without it and that works locally.

I suppose it's not a big deal, and for the same reason, another nice good first contribution.

**Comment by wholmgren** [comment]
I think it's a holdover from when `dni_et` (and other inputs) were calculated inputs rather than fixed inputs to various tests. It was easy to get started with calculated inputs but we eventually realized that led to unhealthy coupling in the test suite. So, safe to remove the unused fixture there.

**Comment by Clemo97** [comment]
Was this issue fixed??

**Comment by echedey-ls** [comment]
Hi @Clemo97 !

No, it hasn't. Would you like to work on this?

I recommend reading the how to contribute page https://pvlib-python.readthedocs.io/en/stable/index.html

And this amazing post from @kurt-rhee https://kurt-rhee.github.io/2024/06/13/how-to-contribute-to-pvlib

We would be happy to help you get involved :)
