### ISSUE TITLE
Create calculate_avg_photon_energy function

### ISSUE THREAD

**Issue by RDaxini** [pvlib/pvlib-python#2135]
I think a function to calculate the average photon energy (APE) using spectral irradiance data as an input would be a useful feature in pvlib.

**Additional context**
This would support PR #2126. While there are some discussions ongoing regarding that PR in Issue #2065, I think this may still be a useful feature in pvlib anyway regardless of the outcome of that PR.

The function would be in `pvlib/spectrum/spectral_irradiance.py` following the resolution of #2125 (I will create a PR for that soon issue soon)

I am wondering what people think about naming this function. Possibilities:

`calculate_avg_photon_energy`
`calculate_average_photon_energy`
`calculate_ape`
Switch "calculate" for "get" or "calc", or just omit this first word entirely?
Alternatives? 

Any other thoughts on this?

**Comment by echedey-ls** [comment]
> or just omit this first word entirely?

+1 for `average_photon_energy`

**Comment by AdamRJensen** [comment]
> > or just omit this first word entirely?
> 
> +1 for `average_photon_energy`

+2
