### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by echedey-ls** [pvlib/pvlib-python#2159]
**Describe the bug**
Here is a hard issue to solve. Harder than solving some implementation details of unused models, changing patterns or so. The hardest issue so far. Please, refrain from solving this before we can talk about what shall be done at PVPMC - this issue is reserved for EU PVPMC attendees in case they want to learn about the contribution process.

There is a typo at https://github.com/pvlib/pvlib-python/blob/599c5d97abd6ed8ba2dec92999cc40ee05083fb7/pvlib/clearsky.py#L944C51-L944C63

**Expected behavior**
I'd like to read `implementation` with all the characters, instead of `implentation`.

**Versions:**
 - ``pvlib.__version__``: v0.11.0

**Additional context**
https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.clearsky.bird.html#pvlib.clearsky.bird

> [!WARNING]  
**THIS ISSUE IS RESERVED FOR THE 2024 EU PVPMC Workshop.
PLEASE DO NOT WORK ON THIS ISSUE WITHOUT PRIOR AGREEMENT.**

**Comment by cardenca** [comment]
Fixing bug - pvpcm conference 2024
