### ISSUE TITLE
irradiadiance.extraradiation() clarification

### ISSUE THREAD

**Issue by adriesse** [pvlib/pvlib-python#216]
The code contains the following cryptic comment:

> Notes
>     -----
>     The Spencer method contains a minus sign discrepancy between
>     equation 12 of [1]. It's unclear what the correct formula is.

I found the minus sign in reference [1], ran both versions of the formula, and found the plus version to give the smaller error with respect to pyephem.  The plus version is also given in Duffie and Beckman, so this comment can be safely removed.

**Comment by wholmgren** [comment]
I'm fine with removing it. I always assumed that it was from the matlab toolbox, but I searched for it and didn't find it in the latest version. Thanks for doing the test, too. Want to make a pull request?

**Comment by adriesse** [comment]
I'm not set up to do that (yet).
