### ISSUE TITLE
Yet another documentation typo

### ISSUE THREAD

**Issue by echedey-ls** [pvlib/pvlib-python#2160]
**Describe the bug**
The typo here described can be considered a task for contributors that may want to work on it during EU PVPMC.

**To Reproduce**
Typo at: https://github.com/pvlib/pvlib-python/blob/599c5d97abd6ed8ba2dec92999cc40ee05083fb7/pvlib/modelchain.py#L1477C51-L1477C59

**Expected behavior**
Not to find a typo 👍 

**Versions:**
 - ``pvlib.__version__``: v0.11.0

**Additional context**
Documentation link: https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.modelchain.ModelChain.prepare_inputs_from_poa.html#pvlib.modelchain.ModelChain.prepare_inputs_from_poa

> [!WARNING]  
**THIS ISSUE IS RESERVED FOR THE 2024 EU PVPMC Workshop.
PLEASE DO NOT WORK ON THIS ISSUE WITHOUT PRIOR AGREEMENT.**

**Comment by mrue-pv** [comment]
I'm going to contribue to this one! :)
