### ISSUE TITLE
Typo in PVSystem.pvwatts_dc

### ISSUE THREAD

**Issue by echedey-ls** [pvlib/pvlib-python#2162]
**Describe the bug**
Typo in the first word, `Calcuates ...`

**To Reproduce**
https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.pvsystem.PVSystem.pvwatts_dc.html
https://github.com/pvlib/pvlib-python/blob/599c5d97abd6ed8ba2dec92999cc40ee05083fb7/pvlib/pvsystem.py#L844

**Expected behavior**
To read `Calculates ...`

**Versions:**
 - ``pvlib.__version__``: 0.11.0

> [!WARNING]  
**THIS ISSUE IS RESERVED FOR THE 2024 EU PVPMC Workshop.
PLEASE DO NOT WORK ON THIS ISSUE WITHOUT PRIOR AGREEMENT.**

**Comment by BernatNicolau** [comment]
I'm fixing it right now!
