### ISSUE TITLE
Typo at pvlib.pvsystem.calcparams_desoto

### ISSUE THREAD

**Issue by echedey-ls** [pvlib/pvlib-python#2163]
**Describe the bug**
There's a typo in the documentation of the "saturation_current" parameter on this line, https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.pvsystem.calcparams_desoto.html
File https://github.com/pvlib/pvlib-python/blob/599c5d97abd6ed8ba2dec92999cc40ee05083fb7/pvlib/pvsystem.py#L1553

**Expected behavior**
The spelling should be `current` instead of `curent` 

**Versions:**
 - ``pvlib.__version__``: 0.11.0

> [!WARNING]  
**THIS ISSUE IS RESERVED FOR THE 2024 EU PVPMC Workshop.
PLEASE DO NOT WORK ON THIS ISSUE WITHOUT PRIOR AGREEMENT.**

**Comment by cwhanse** [comment]
> This issue is very difficult, 

?

**Comment by echedey-ls** [comment]
My bad for the lack of context, I thought many more of you were aware. I'm finding small issues that can be the starting point for a small how-to-contribute to pvlib workshop at EU PVPMC. Added warnings to all of these issues thx to @AdamRJensen .

**Comment by adriesse** [comment]
> My bad for the lack of context, I thought many more of you were aware.

Not your bad. The core team has not been informed about overall plans for GSoC or workshop.

**Comment by EduardoSarquis** [comment]
I'm working on it!
