### ISSUE TITLE
irradiadiance.extraradiation() returned values inconsistency

### ISSUE THREAD

**Issue by adriesse** [pvlib/pvlib-python#217]
The method 'pyephem' returns a pandas.TimeSeries whereas the methods 'asce' and 'spencer' do not.

**Comment by wholmgren** [comment]
Yes, this has bothered me in the past and I meant to fix it in #214 or #215. It also does not accept datetime.date, datetime.datetime, or pandas.Timestamp inputs. I think that regardless of method, pandas input should yield TimeSeries output, and all other input should yield scalar or array output.
