### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by echedey-ls** [pvlib/pvlib-python#2177]
**Describe the bug**
Typo in word, `arugments`

**To Reproduce**
https://github.com/pvlib/pvlib-python/blob/b5e89be2dc7ec761fd1bf6eb21691fc10590c95b/pvlib/singlediode.py#L635

**Expected behavior**
To read `arguments`

**Versions:**
 - ``pvlib.__version__``: 0.11.0

> [!WARNING]  
**THIS ISSUE IS RESERVED FOR THE 2024 EU PVPMC Workshop.
PLEASE DO NOT WORK ON THIS ISSUE WITHOUT PRIOR AGREEMENT.**

**Comment by luizreiscver** [comment]
I am working with this issue
