### ISSUE TITLE
Example gallery suggestion: `spectrum.average_photon_energy`

### ISSUE THREAD

**Issue by RDaxini** [pvlib/pvlib-python#2194]
I am wondering what level of interest there is for an example gallery addition demonstrating the use of `spectrum.average_photon_energy`. 

I think an example calculation of the APE of several spectra could help users understand how to interpret the parameter (high values => blue-shifted spectrum, lower values => red-shifted spectrum) as well as guide users on how to use the function of course.

Since we have the `spectrum.spctrl2` function to simulate spectra, but the output is not usable directly as an input into `spectrum.average_photon_energy`, I think some example code linking the two would also be helpful so that users have a guide on how to simulate and characterise spectral distributions all within pvlib-python.

I'd be happy to create this example if the community thinks it'd be useful.

**Comment by AdamRJensen** [comment]
That sounds great to me!

**Comment by RDaxini** [comment]
I'll start working on this soon then and create a PR once I have something ready 👍
