### ISSUE TITLE
DNI/DHI estimation

### ISSUE THREAD

**Issue by eshnEnergiDanmark** [pvlib/pvlib-python#2233]
I have weather data of GNI, but I need to estimate the DNI and DHI which I have done with the Erbs Drisse model:

from pvlib.irradiance import erbs_driesse, get_total_irradiance

dni_dhi = erbs_driesse(
    ghi=vejr["ghi"].values,
    zenith=sun_pos["zenith"].values,
    datetime_or_doy=pd.DatetimeIndex(sun_pos.index),
)

However I get some wierd output when plotting the data in a very clear sky period. How come? It looks shifted and makes the simulation bad
![wierd](https://github.com/user-attachments/assets/fca9757b-ff20-4a7b-8283-8c85aa0b9237)

**Comment by markcampanelli** [comment]
A quick sanity check would be to run this same data through, say, the
original Erbs model and see if you get a similar artifact. That would
likely catch an error in the solar position calculation or indexing.

Mark Campanelli
LinkedIn <https://www.linkedin.com/in/markcampanelli/>
Intelligent Measurement Systems LLC
<https://intelligentmeasurementsystems.com>
Try PVfit <https://pvfit.app> today!

**Comment by eshnEnergiDanmark** [comment]
I get the same artifact with original Erbs. I also suspect it is an eropr in the solar position calculation, the way the plot looks. I have the following code


from pvlib.location import Location
vejr = pd.read_csv(...)
location = Location(lat, lon, tz="UTC")
sun_pos = location.get_solarposition(vejr.index)

**Comment by AdamRJensen** [comment]
Your weather data is almost certainly in a different timezone than utc. ETC/UTC-1 should be correct

**Comment by eshnEnergiDanmark** [comment]
I'm almost certain that my weather data is UTC. I have tried to play around with the sun_position and change the timezone of this to see how it impacts the outcome of Erbs-Driesse. I use this code: 

sun_pos.index = sun_pos.index.tz_convert("Etc/GMT-8")
sun_pos.index = sun_pos.index.tz_localize(None)

# %%
from pvlib.irradiance import erbs_driesse

dni_dhi = erbs_driesse(
    ghi=vejr["ghi"].values,
    zenith=sun_pos["zenith"].values,
    datetime_or_doy=pd.DatetimeIndex(sun_pos.index),
)

And get this plot, where I still have this wierd sharp rise in the start of every DNI-curve

![wierd2](https://github.com/user-attachments/assets/c4455265-e1f9-44e6-a395-7b1625fd1fa6)

**Comment by eshnEnergiDanmark** [comment]
I am very certain my weather data is in UTC.

**Comment by AdamRJensen** [comment]
> I am very certain my weather data is in UTC. 

I'd be happy to take a lot if you're up for sharing a piece of the data: arajen@dtu.dk

**Comment by cwhanse** [comment]
> Your weather data is almost certainly in a different time zone.

Or the sun position times are not aligned with the weather data times.

**Comment by eshnEnergiDanmark** [comment]
Update. I found that if I shifted +30 min to the weather data, I get nice plot of the estimated DNI/DHI. Here I have the ghi, dni, dhi for both the weather data (y) and clear sky model (x) - and it looks alot more nice
![fix](https://github.com/user-attachments/assets/0c883d4a-3bd2-43a4-8b99-7b6fbecc57d8)
