### ISSUE TITLE
Contributing link on Readme is broken

### ISSUE THREAD

**Issue by matsuobasho** [pvlib/pvlib-python#2239]
**Describe the bug**
Link to the contributing page on Readme is broken
http://pvlib-python.readthedocs.io/en/stable/contributing.html

**To Reproduce**
1. Go to Readme
2. Click on 'Contributing page'
3. See error

**Expected behavior**
Contributing page.

**Comment by mikofski** [comment]
Hi @matsuobasho to whom should I give credit in contributors?
