### ISSUE TITLE
Update top ranking issue test failure

### ISSUE THREAD

**Issue by RDaxini** [pvlib/pvlib-python#2270]
**Describe the bug**
Top ranking issue test fails on a PR

**To Reproduce**
1. Go to #2234
2. See [test log](https://github.com/pvlib/pvlib-python/actions/runs/11419413952/job/31773971024?pr=2234#annotation:5:28)

Error: "Resource not accessible by integration"

**Expected behavior**
Pass?

**Versions:**
 - python: 3.12

**Additional context**
I think this new top ranking issue feature is pretty cool 👍🏾
Not sure what's happening here with the test failure, I do not quite understand the error message.

**Comment by kandersolar** [comment]
Yes, it's not supposed to run on PRs really.  We enabled it on PRs for testing purposes but now it should be removed.  #2269
