### ISSUE TITLE
Typo in klucher irradiance model

### ISSUE THREAD

**Issue by emulbreh** [pvlib/pvlib-python#228]
This change looks like a typo:
https://github.com/pvlib/pvlib-python/commit/1f968a034f74e46f021f3a6b85ea86c5e1ad6cf8#diff-9e2b3ebf5d45c478fee41a88b0e5f44eR671

**Comment by wholmgren** [comment]
Good catch. Can you make a pull request with a fix?

**Comment by adriesse** [comment]
Good catch indeed.  Could there be a test to catch this type of thing?
