### ISSUE TITLE
Parameters missing from ivtools.sdm.fit_desoto_sandia returns statement

### ISSUE THREAD

**Issue by RDaxini** [pvlib/pvlib-python#2315]
**Is your feature request related to a problem? Please describe.**
In addition to the parameters already listed in the returns statement in the docs of [pvlib.ivtools.sdm.fit_desoto_sandia](https://pvlib-python.readthedocs.io/en/stable/_modules/pvlib/ivtools/sdm.html#fit_desoto_sandia), this function also returns `a_ref` and `dEgdT`, which are two parameters required for the [De Soto module performance model](https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.pvsystem.calcparams_desoto.html#pvlib-pvsystem-calcparams-desoto).

**Describe the solution you'd like**
Add descriptions of `a_ref` and `dEgdT` to the returns statement in the docs

**Describe alternatives you've considered**
Have I missed something here...?

**Comment by kandersolar** [comment]
@cwhanse I notice a possible sign error: `fit_desoto_sandia` returns `dEgdT=0.0002677` while `calcparams_desoto` defaults to `dEgdT=-0.0002677`.  Is this a bug?

**Comment by cwhanse** [comment]
> @cwhanse I notice a possible sign error: `fit_desoto_sandia` returns `dEgdT=0.0002677` while `calcparams_desoto` defaults to `dEgdT=-0.0002677`. Is this a bug?

Yes it is. New issue or fix here?
 
> If so, it may affect the matlab version as well: https://github.com/sandialabs/MATLAB_PV_LIB/blob/master/pvl_desoto_parameter_estimation.m#L276

Technically, no, since the Matlab function doesn't return dEgdT.

**Comment by kandersolar** [comment]
Opened #2321 so we can close this one with #2317.
