### ISSUE TITLE
Incorrect units pvlib.ivtools.sdm.fit_desoto

### ISSUE THREAD

**Issue by RDaxini** [pvlib/pvlib-python#2319]
**Is your feature request related to a problem? Please describe.**
Units of `dEg/dT` in [pvlib.ivtools.sdm.fit_desoto](https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.ivtools.sdm.fit_desoto.html#pvlib.ivtools.sdm.fit_desoto) should be 1/K, not eV/K

**Describe the solution you'd like**
Correct the units

**Additional context**
[Comment](https://github.com/pvlib/pvlib-python/pull/2317#discussion_r1868149874)

Marking as good first issue for a new contributor, but I could fix this if no-one does it before 11.2 release if we want it done by then.

**Comment by cwhanse** [comment]
To clarify: the unit in the docstring is given as eV/K, it should be 1/K, per discussion in #2154. No other change is needed.
