### ISSUE TITLE
PVLIB packaging with Pyinstaller

### ISSUE THREAD

**Issue by chetan201** [pvlib/pvlib-python#248]
Hi guys,
This might a little off the topic but has anyone tried packaging PVLIB using Pyinstaller as an exe for easy distribution? Alternatively, if there are any ideas about easy distribution of packages built using pvlib, I'd love to hear them from the community.

Thanks!

**Comment by wholmgren** [comment]
I have not, but it sounds similar to Continuum's constructor tool:

https://www.continuum.io/blog/developer-blog/introducing-constructor

**Comment by chetan201** [comment]
Thanks Will. I will give that a shot. 
Pyinstaller gets stuck on some dependencies that I can't really figure out quickly.
