### ISSUE TITLE
docs: issue linking 

### ISSUE THREAD

**Issue by dacoex** [pvlib/pvlib-python#27]
The issue link does not work:

```
Add What’s New section to docs (:issue:`10`)
```
on page
http://wholmgren-pvlib-python-new.readthedocs.org/en/docfixes/whatsnew.html#new-features

**Comment by wholmgren** [comment]
#22 isn't even merged yet! I want to keep the issues page focused on the code and documentation that is actually in pvlib/pvlib-python. You can reopen the issue if this is not resolved when it is merged.
