### ISSUE TITLE
advice on modeling at high altitudes? 

### ISSUE THREAD

**Issue by jforbess** [pvlib/pvlib-python#285]
I am interested in modeling clear sky irradiance at different altitudes, including the stratosphere. My test run using my current clear sky setup with ineichen at an altitude of 20km produced an answer significantly greater than the dni_et I used. 

I'd appreciate any hints as to whether I need use something other than the default linke turbidities table, or whether there is a better algorithm for clear sky to use for high altitude modeling.

**Comment by mikofski** [comment]
What about taking a ratio of the altitude to to the height of the atmosphere, apply that to precipitable water and AOD and use that either to calculate Linke or in Birds it simplified Solis.

EG: assume the sky is 100,000 meters, and your elevation is 5,000 [m]. So if the precip-water is 1.0[cm] at sea level, at 5km it's 0.95%.

Ditto for AOD. Then to calculate Linke, see #278, or just use either Bird or Solis with water and AOD directly.

**Comment by mikofski** [comment]
BTW: this type of question might be good for the [pvlib-python Google group](https://groups.google.com/forum/m/#!forum/pvlib-python).

**Comment by mikofski** [comment]
Sorry to hijack youre thread, but I've also set up a [pvlib-python slack channel](https://pvlib-python.slack.com). So far I've tried to invite @wholmgren @jforbess @bmeyers @zdefreitas @anomam and @adriesse.

**Comment by cwhanse** [comment]
I found an empirical model for the attenuation of direct and global irradiance as a function of altitude here:
https://hal.archives-ouvertes.fr/hal-00470155/document

The formulas are hard to read (non-standard formatting) but the plots look promising.  I haven't used this model.

**Comment by wholmgren** [comment]
See #297 for a place to discuss @mikofski's google group and slack channel.

**Comment by stephenkaplan** [comment]
@mikofski can you please invite me to the slack channel? stephen.kaplan@firstsolar.com

**Comment by wholmgren** [comment]
@jforbess I'm going to close this to clean up the issues board. I suppose people could continue to comment on it here, but perhaps the google group is a better place for this sort of thing.
