### ISSUE TITLE
Simple analytical Azimuth method

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#291]
From Duffie/Beckman, Seinfeld/Pandis, etc. 1-line, very accurate.

**Comment by wholmgren** [comment]
What's the application? Efficient calculation of solar noon? We already have too many ways to calculation solar position, so I'm reluctant to add more unless there's a good use case for them.

**Comment by mikofski** [comment]
We have used it in the past, so I have to continue to support those calculations. Apples to apples.

It's literally a one liner, so not sure what the concern is. I think of pvlib as not just a tool box but also a single source of truth for PV formulas. Having this 1-liner completes the solar position calculation. Any IE coming across a random equation will need to vet it, whereas _if the analysis uses **pvlib**_, then the vetting has already been done. This saves time and money.

**Comment by wholmgren** [comment]
Now that I've looked at your updated #276 I think I understand what you're proposing. You want the equivalent of ``def solar_zenith_analytical(latitude, hour_angle, declination):`` for azimuth?

**Comment by adriesse** [comment]
Just curious, what line are you referring to?

**Comment by mikofski** [comment]
Yes, thx. I'll probably submit a PR early next week 😀

**Comment by wholmgren** [comment]
closed by #349
