### ISSUE TITLE
Reverse ghi from ipoa

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#292]
Like Bill Marion's paper, only better

**Comment by adriesse** [comment]
Are these just teasers??

**Comment by wholmgren** [comment]
You mean the GTI-DIRINT paper? http://dx.doi.org/10.1016/j.solener.2015.10.024

**Comment by mikofski** [comment]
I emailed two papers to Will H. I will try to implement the gti-dirint, but probably not until q2

**Comment by wholmgren** [comment]
@mikofski can this issue be closed in favor of #396 and #400?

**Comment by mikofski** [comment]
yes, closing now in favor of #396
