### ISSUE TITLE
Forecasting Docs build error

### ISSUE THREAD

**Issue by nparley** [pvlib/pvlib-python#299]
The docs for forecasting need updating http://pvlib-python.readthedocs.io/en/latest/forecasts.html as there are many build errors, Maybe all caused by `netCDF4` import error at the top?

**Comment by wholmgren** [comment]
Yep. https://github.com/pvlib/pvlib-python/pull/180#issuecomment-235935887

**Comment by wholmgren** [comment]
An example of how it fails: https://readthedocs.org/projects/wholmgren-pvlib-python-new/builds/4753267/

**Comment by wholmgren** [comment]
Just tried it again and it works now!

https://readthedocs.org/projects/wholmgren-pvlib-python-new/builds/4913582/

Well, it fails with the known sqllite error and has some other warnings. But the docs still build:

http://wholmgren-pvlib-python-new.readthedocs.io/en/rtdnc/forecasts.html

I will clean up a few things and make a pull request soon.
