### ISSUE TITLE
Port Tutorials 

### ISSUE THREAD

**Issue by Calama-Consulting** [pvlib/pvlib-python#30]
Port of tutorials from sandia labs develop branch.

**Comment by bmu** [comment]
I think we could shift this to 0.2 and release 0.1 of pvlib.

**Comment by wholmgren** [comment]
Agreed.

**Comment by bmu** [comment]
@Calama-Consulting ?

**Comment by bmu** [comment]
I changed the milestone to 0.2

**Comment by wholmgren** [comment]
I'm going to mark this 0.3 since I'm not sure what should be ported into new or existing notebooks and what should be put into the docstrings and sphinx documentation.

**Comment by wholmgren** [comment]
I've had a lot of offline feedback that broken tutorials a big problem and I'd like to do a 0.2.1 release with updated tutorials. I don't plan to make them read any better, just get them to the point that they can run end-to-end without exceptions. #69 is also relevant to this.

**Comment by NelisW** [comment]
Will try to help here. My take on the Sphinx vs notebook issue is that personally I prefer a worked example to get up to speed first and then dig into the API-level docs. Trying to get into a new product just by reading the API docs is just too hard. So, let's fix the notebooks first.
