### ISSUE TITLE
add discussion and examples of Angstrom and Kasten formulas to docs

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#302]
Related to issue #269 and a follow on to PR #278 which adds the Kasten pyrheliometric formula to calculate Linke turbidity factor given broadband AOD and precipitable water, the Bird-Hulstrom broadband AOD correlation and Angstrom formulas to calculate alpha exponent from AOD at two wavelengths and to calculate AOD given one measurement and alpha.

This issue proposes to add a brief discussion and some examples to the clear sky documentation. The discussion can also mention other methods not currently included in pvlib-python.

**Comment by mikofski** [comment]
Any comments on how to approach this? How long of a discussion? What's the main goal? I'd like to close this out, so any pointers would help a lot. thx

Here are some references with links to more:
* [Use of Measured Aerosol Optical Depth and Precipitable Water to Model Clear Sky Irradiance](https://www.researchgate.net/publication/318470239_Use_of_Measured_Aerosol_Optical_Depth_and_Precipitable_Water_to_Model_Clear_Sky_Irradiance)
* [Evaluation and Correction of the Impact of Spectral Variation of Irradiance on PV Performance](https://www.researchgate.net/publication/309648716_Evaluation_and_Correction_of_the_Impact_of_Spectral_Variation_of_Irradiance_on_PV_Performance)

**Comment by wholmgren** [comment]
A paragraph or two in clearsky.rst. Only enough to give people a sense of what’s possible.
