### ISSUE TITLE
Loss Factor Model

### ISSUE THREAD

**Issue by cbirkj** [pvlib/pvlib-python#306]
The Loss Factor Model (LFM) is used to analyze current and voltage (I-V) curves and model system performance ([Stein et al](http://energy.sandia.gov/wp-content//gallery/uploads/4CO-11-1a.pdf)).  

Similar to my last issue post, I am wondering what people's thoughts are on adding LFM parameter estimation to the PVLIB library?

Birk

**Comment by adriesse** [comment]
Seems like a good idea to me.  There are lots of papers on it.

**Comment by thunderfish24** [comment]
+1

**Comment by steve-ransome** [comment]
Hi all
Just to let you know I am working on adding the LFM to PV LIB (also with Juergen Sutterlueti from Gantner Instruments) and hope to have something in a couple of weeks.

**Comment by adriesse** [comment]
Good work!  Python? or Matlab?

**Comment by steve-ransome** [comment]
Python.On 26 February 2017 at 20:27 Anton Driesse <notifications@github.com> wrote:Good work! Python? or Matlab?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cwhanse** [comment]
Hi Steve, any progress on this?

**Comment by wholmgren** [comment]
#925 contains the recent discussion of this topic.
