### ISSUE TITLE
PV Monitoring

### ISSUE THREAD

**Issue by cbirkj** [pvlib/pvlib-python#321]
PV_LIB has packages for system modeling and forecasting.  What does the group think about a monitoring package? 

I have some python code that collects current, voltage, and temperatures from a Modbus device.  Currently, the code is running successfully on a raspberry pi and collecting data at 1 second intervals and storing the data in a MySQL database.

What do you think?

**Comment by thunderfish24** [comment]
Is the idea of the package to help ensure that monitoring data can be integrated with other PV_LIB tools?

**Comment by wholmgren** [comment]
Would pecos be a better fit?

**Comment by cbirkj** [comment]
Good point.  Pecos could be a better fit.

**Comment by djaberpy** [comment]
That great. Which kind of pv panel.

**Comment by wholmgren** [comment]
@cbirkj I saw a pecos pull request with similar functionality. can this issue be closed now?
