### ISSUE TITLE
replace all instances of .ix

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#322]
Pandas 0.20 deprecates the ``.ix`` indexer and we need to make a handful of minor changes to stay current.

https://github.com/pvlib/pvlib-python/search?utf8=✓&q=.ix&type=

http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0200-api-breaking-deprecate-ix

I'd welcome a PR for this.

**Comment by morrme** [comment]
What do you want to change the references to: `.loc `or `.iloc` ?

**Comment by cwhanse** [comment]
Depends whether we want position or label indexing.  The problem with .ix is that it tried to handle both cases.

**Comment by adriesse** [comment]
Are these methods ok?

```
df.column_name.[row_number]
df.column_name.iloc[row_number]
df.iloc[row_number].column_name

```

**Comment by wholmgren** [comment]
In ``timetimezones.rst``, ``tmy3_data.ix[0:3, ['GHI', 'DNI', 'AOD']]`` becomes ``tmy3_data[tmy3_data.index[0:3], 'GHI', 'DNI', 'AOD']``

In ``forecast.py``, I think you can simply use ``[self.output_variables]``.

I think the case in ``irradiance.py`` will work with ``loc``.
