### ISSUE TITLE
Add parameter racking_model to sapm_temp call in modelchain

### ISSUE THREAD

**Issue by jkfm** [pvlib/pvlib-python#323]
I would like to submit the racking_model parameter while using the modelchain approach. 

If I am not mistaken, it could be added as an optional parameter in the ModelChain instantiation and then in the function sapm_temp, right?

I could try doing it myself, but would like to hear your opinion first.

**Comment by wholmgren** [comment]
I think setting the ``racking_model`` attribute of your ``pvsystem`` object will already do what you're looking for.

**Comment by jkfm** [comment]
You're right, thanks for the tip!
