### ISSUE TITLE
Less entries in the sandia modules database

### ISSUE THREAD

**Issue by uvchik** [pvlib/pvlib-python#331]
Issue #224 added the csv files with module and inverter data to the repository. The original module database contained about 14000 entries the new one about 500. Is there a reason for that?

**Comment by cwhanse** [comment]
There are two CSV files with module parameters, one file for the CEC model with 14k entries, a second file for the Sandia model with 500 entries.

**Comment by uvchik** [comment]
Oh, sorry. I mixed it up.
