### ISSUE TITLE
_recolumn function of tmy.py doesn't use passed 'inplace' parameter

### ISSUE THREAD

**Issue by KonstantinTr** [pvlib/pvlib-python#342]
**inplace=True** statement is hard-coded. Should be used **inplace=inplace** statement instead

![image](https://user-images.githubusercontent.com/16244350/27728861-353de098-5d8c-11e7-8b1d-0edb89a06558.png)

**Comment by wholmgren** [comment]
This keyword argument does not do anything in practice, so it should be removed. Feel free to submit a pull request.

**Comment by wholmgren** [comment]
closed by #384.
