### ISSUE TITLE
cloud_cover_to_transmittance_linear function of forecast.py doesn't use passed 'offset' parameter

### ISSUE THREAD

**Issue by KonstantinTr** [pvlib/pvlib-python#343]
Should 'offset' be used instead of 0.75 in the expression?

![image](https://user-images.githubusercontent.com/16244350/27729252-d095e026-5d8d-11e7-8ba9-31452d05445f.png)

**Comment by wholmgren** [comment]
Thanks, good catch. Can you submit a pull request with a new test for this behavior?

**Comment by KonstantinTr** [comment]
Sure. I'm new to git so it'll take some time to get how to do it :)

**Comment by wholmgren** [comment]
closed by #348.
