### ISSUE TITLE
_calc_d function of clearsky.py doesn't use passed argument

### ISSUE THREAD

**Issue by KonstantinTr** [pvlib/pvlib-python#344]
It seem's that **w** is not used within function...

![image](https://user-images.githubusercontent.com/16244350/27731439-93fc2352-5d95-11e7-8830-5f0498f811d7.png)

**Comment by wholmgren** [comment]
True, it can be removed. Feel free to submit a pull request.

**Comment by alainakafkes** [comment]
Hi! I'm doing OpenSourceFriday PRs today, so I'll tackle this. :)
