### ISSUE TITLE
sapm takes 3 positional arguments but 6 were given 

### ISSUE THREAD

**Issue by AmyneTRABELSI** [pvlib/pvlib-python#347]
dc = pvlib.pvsystem.sapm(module, total_irrad['poa_direct'],total_irrad['poa_diffuse'], temps['temp_cell'],am_abs, aoi) 

TypeError: sapm() takes 3 positional arguments but 6 were given

**Comment by wholmgren** [comment]
The ``sapm`` function signature changed about a year ago. http://pvlib-python.readthedocs.io/en/latest/generated/pvlib.pvsystem.sapm.html#pvlib.pvsystem.sapm

**Comment by mikofski** [comment]
You can still use [`sapm_effective_irradiance`](http://pvlib-python.readthedocs.io/en/latest/generated/pvlib.pvsystem.sapm_effective_irradiance.html?highlight=sapm_effective_irradiance) as in the [docs package overview](http://pvlib-python.readthedocs.io/en/latest/package_overview.html#procedural) to use the legacy api:

    effective_irradiance = pvlib.pvsystem.sapm_effective_irradiance(
        total_irrad['poa_direct'], total_irrad['poa_diffuse'],
        am_abs, aoi, module)
