### ISSUE TITLE
Skip tests if optional dependencies are not installed

### ISSUE THREAD

**Issue by bmu** [pvlib/pvlib-python#36]
See #13, #31, #34 

Beside scipy there may be other optional dependencies? spa , ...?
We should first define optional dependencies, test if they are installed, if not skip 
tests that need them.

**Comment by wholmgren** [comment]
@bmu are you ok with this going to 0.3?

**Comment by bmu** [comment]
sure

**Comment by wholmgren** [comment]
I think that #109 closed this, or least it did for scipy, and the solar position tests already skip tests if numba or spa_c are not installed.

**Comment by wholmgren** [comment]
I meant to close this last week this along with #12.
