### ISSUE TITLE
alpha_prime calculated without usage

### ISSUE THREAD

**Issue by KonstantinTr** [pvlib/pvlib-python#366]
Two functions (namely solar_position_numpy and solar_position_loop) of spa module calculate alpha_prime without any usage.

**Should it be passed as a argument later in the code?** I had checked argument names for all following calls and didn't find _topocentric_sun_right_ascension_ among arg names. 

![image](https://user-images.githubusercontent.com/16244350/29965401-1988756e-8f16-11e7-94e8-b360104f8f36.png)

**Comment by wholmgren** [comment]
I don't think it's needed here, but can you check the reference? We should skip the calculation if it's not needed.

**Comment by KonstantinTr** [comment]
I close this issue as far as it was solved with already merged PR #383
