### ISSUE TITLE
total irradiance docs don't show poa_diffuse as a return, but package overview uses it

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#367]
Thought I was going crazy today, when I couldn't find any references of [`total_irrad`](http://pvlib-python.readthedocs.io/en/latest/generated/pvlib.irradiance.total_irrad.html#pvlib-irradiance-total-irrad) returning `poa_diffuse`, but there it is in the [package overview procedural example](http://pvlib-python.readthedocs.io/en/latest/package_overview.html#procedural) and I've been using it my code.

Looking through the code it was changed in #105 to output global, beam, diffuse sum, just sky diffuse and just ground diffuse. To avoid craziness, the docs should probably be updated. Should be an quick, easy fix.

**Comment by wholmgren** [comment]
closed by #376
