### ISSUE TITLE
New user: Memory error?

### ISSUE THREAD

**Issue by Suraj--Peri** [pvlib/pvlib-python#371]
Hey, I just started using the library to get forecasts using a couple different methods. It was working fine until today morning and somehow gives me a memory error when I run it now. The script is below: 

`import datetime
import inspect
import os

import numpy as np
import pandas as pd

from pvlib import solarposition,irradiance,atmosphere,pvsystem
from pvlib.forecast import NDFD, RAP, HRRR
from pvlib import pvsystem

system_frame = pd.read_csv(r'C:\Users\VMItronCandA\Desktop\DER\Raw_Data_Actual\Dashboard_Database_Tracking.csv', header = 0)

demand_frame = system_frame[system_frame['Demand'] == 1]
demand_frame = demand_frame.reset_index()

if not os.path.exists(r'C:\Users\VMItronCandA\Desktop\DER\PV_Simulations\Demand_Sites\%s' % datetime.datetime.now().strftime('%Y-%m-%d_%H')):
    os.makedirs(r'C:\Users\VMItronCandA\Desktop\DER\PV_Simulations\Demand_Sites\%s' % datetime.datetime.now().strftime('%Y-%m-%d_%H'))

forecast_models = [NDFD(), RAP(), HRRR()]
fm_strings = ['NDFD', 'RAP', 'HRRR']
albedo = 0.2
for i in range(0, len(demand_frame)):
    latitude = demand_frame['latitude'][i]
    longitude = demand_frame['longitude'][i]
    tz = system_frame['tz'][i]
    today = pd.Timestamp(datetime.date.today(), tz=tz)
    start = today - pd.Timedelta(days=1)
    end = today + pd.Timedelta(days=7)
    surface_tilt = demand_frame['tilt'][i]
    surface_azimuth = demand_frame['azimuth'][i]
    for j in range(0, len(fm_strings)):
        fm = forecast_models[j]
        forecast_data = fm.get_processed_data(latitude, longitude, start, end)
        time = forecast_data.index
        a_point = fm.location
        solpos = a_point.get_solarposition(time)
        ghi = forecast_data['ghi']
        dni_extra = irradiance.extraradiation(fm.time)        
        airmass = atmosphere.relativeairmass(solpos['apparent_zenith'])
        poa_sky_diffuse = irradiance.haydavies(surface_tilt, surface_azimuth,
                                             forecast_data['dhi'], forecast_data['dni'], dni_extra,
                                             solpos['apparent_zenith'], solpos['azimuth'])
        poa_ground_diffuse = irradiance.grounddiffuse(surface_tilt, ghi, albedo=albedo)
        aoi = irradiance.aoi(surface_tilt, surface_azimuth, solpos['apparent_zenith'], solpos['azimuth'])
        poa_irrad = irradiance.globalinplane(aoi, forecast_data['dni'], poa_sky_diffuse, poa_ground_diffuse)
        temperature = forecast_data['temp_air']
        wnd_spd = forecast_data['wind_speed']
        pvtemps = pvsystem.sapm_celltemp(poa_irrad['poa_global'], wnd_spd, temperature)        
        for k in range(0, len(poa_irrad)):
            if poa_irrad['poa_global'][k] > 1000:
                poa_irrad['poa_global'][k] = poa_irrad['poa_global'][k-1]                
        temperature = forecast_data['temp_air']
        wnd_spd = forecast_data['wind_speed']
        pvtemps = pvsystem.sapm_celltemp(poa_irrad['poa_global'], wnd_spd, temperature)
        dc_out= pvsystem.pvwatts_dc(poa_irrad['poa_global'], pvtemps['temp_cell'], system_frame['dc'][i], -.002)
        if j == 0:
            dc_frame = pd.DataFrame({'NDFD_kWh': dc_out})
        if j == 1:
            dc_frame['RAP_kWh'] =  dc_out
        if j == 2:
            dc_frame['HRRR_kWh'] = dc_out
    dc_frame['Itron_ID'] = demand_frame['ID'][i]
    dc_frame.index = dc_frame.index.tz_localize(None)
    out_name =  datetime.datetime.now().strftime('%Y-%m-%d_%H') + '\\' + demand_frame['ID'][i] + '_Sim'
    dc_frame.to_csv(r'C:\Users\VMItronCandA\Desktop\DER\PV_Simulations\Demand_Sites\%s.csv' % out_name, index_label = 'Datetime')
        `

The error is:

---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py in _new_conn(self)
    140             conn = connection.create_connection(
--> 141                 (self.host, self.port), self.timeout, **extra_kw)
    142 

C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py in create_connection(address, timeout, source_address, socket_options)
     82     if err is not None:
---> 83         raise err
     84 

C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py in create_connection(address, timeout, source_address, socket_options)
     72                 sock.bind(source_address)
---> 73             sock.connect(sa)
     74             return sock

TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    599                                                   body=body, headers=headers,
--> 600                                                   chunked=chunked)
    601 

C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    355         else:
--> 356             conn.request(method, url, **httplib_request_kw)
    357 

C:\ProgramData\Anaconda3\lib\http\client.py in request(self, method, url, body, headers, encode_chunked)
   1238         """Send a complete request to the server."""
-> 1239         self._send_request(method, url, body, headers, encode_chunked)
   1240 

C:\ProgramData\Anaconda3\lib\http\client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1284             body = _encode(body, 'body')
-> 1285         self.endheaders(body, encode_chunked=encode_chunked)
   1286 

C:\ProgramData\Anaconda3\lib\http\client.py in endheaders(self, message_body, encode_chunked)
   1233             raise CannotSendHeader()
-> 1234         self._send_output(message_body, encode_chunked=encode_chunked)
   1235 

C:\ProgramData\Anaconda3\lib\http\client.py in _send_output(self, message_body, encode_chunked)
   1025         del self._buffer[:]
-> 1026         self.send(msg)
   1027 

C:\ProgramData\Anaconda3\lib\http\client.py in send(self, data)
    963             if self.auto_open:
--> 964                 self.connect()
    965             else:

C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py in connect(self)
    165     def connect(self):
--> 166         conn = self._new_conn()
    167         self._prepare_conn(conn)

C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py in _new_conn(self)
    149             raise NewConnectionError(
--> 150                 self, "Failed to establish a new connection: %s" % e)
    151 

NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x000000FC2489EF98>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    437                     retries=self.max_retries,
--> 438                     timeout=timeout
    439                 )

C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    648             retries = retries.increment(method, url, error=e, _pool=self,
--> 649                                         _stacktrace=sys.exc_info()[2])
    650             retries.sleep()

C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\util\retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    387         if new_retry.is_exhausted():
--> 388             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    389 

MaxRetryError: HTTPConnectionPool(host='thredds.ucar.edu', port=80): Max retries exceeded with url: /thredds/ncss/grib/NCEP/NDFD/NWS/CONUS/CONDUIT/Best/dataset.xml (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000FC2489EF98>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-15-5b75aac9c4e6> in <module>()
     13     for j in range(0, len(fm_strings)):
     14         fm = forecast_models[j]
---> 15         forecast_data = fm.get_processed_data(latitude, longitude, start, end)
     16         time = forecast_data.index
     17         a_point = fm.location

C:\ProgramData\Anaconda3\lib\site-packages\pvlib\forecast.py in get_processed_data(self, *args, **kwargs)
    301             Processed forecast data
    302         """
--> 303         return self.process_data(self.get_data(*args, **kwargs), **kwargs)
    304 
    305     def rename(self, data, variables=None):

C:\ProgramData\Anaconda3\lib\site-packages\pvlib\forecast.py in get_data(self, latitude, longitude, start, end, vert_level, query_variables, close_netcdf_data)
    232 
    233         if not self.connected:
--> 234             self.connect_to_catalog()
    235 
    236         if vert_level is not None:

C:\ProgramData\Anaconda3\lib\site-packages\pvlib\forecast.py in connect_to_catalog(self)
    141 
    142         self.datasets_list = list(self.model.datasets.keys())
--> 143         self.set_dataset()
    144         self.connected = True
    145 

C:\ProgramData\Anaconda3\lib\site-packages\pvlib\forecast.py in set_dataset(self)
    163 
    164         self.access_url = self.dataset.access_urls[self.access_url_key]
--> 165         self.ncss = NCSS(self.access_url)
    166         self.query = self.ncss.query()
    167 

C:\ProgramData\Anaconda3\lib\site-packages\siphon\http_util.py in __init__(self, url)
    354         self._base = url
    355         self._session = create_http_session()
--> 356         self._get_metadata()
    357 
    358     def get_query(self, query):

C:\ProgramData\Anaconda3\lib\site-packages\siphon\ncss.py in _get_metadata(self)
     55     def _get_metadata(self):
     56         # Need to use .content here to avoid decode problems
---> 57         meta_xml = self.get_path('dataset.xml').content
     58         root = ET.fromstring(meta_xml)
     59         self.metadata = NCSSDataset(root)

C:\ProgramData\Anaconda3\lib\site-packages\siphon\http_util.py in get_path(self, path, query)
    424 
    425         """
--> 426         return self.get(self.url_path(path), query)
    427 
    428     def get(self, path, params=None):

C:\ProgramData\Anaconda3\lib\site-packages\siphon\http_util.py in get(self, path, params)
    453 
    454         """
--> 455         resp = self._session.get(path, params=params)
    456         if resp.status_code != 200:
    457             if resp.headers['Content-Type'].startswith('text/html'):

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in get(self, url, **kwargs)
    529 
    530         kwargs.setdefault('allow_redirects', True)
--> 531         return self.request('GET', url, **kwargs)
    532 
    533     def options(self, url, **kwargs):

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    516         }
    517         send_kwargs.update(settings)
--> 518         resp = self.send(prep, **send_kwargs)
    519 
    520         return resp

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    637 
    638         # Send the request
--> 639         r = adapter.send(request, **kwargs)
    640 
    641         # Total elapsed time of the request (approximately)

C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    500                 raise ProxyError(e, request=request)
    501 
--> 502             raise ConnectionError(e, request=request)
    503 
    504         except ClosedPoolError as e:

ConnectionError: HTTPConnectionPool(host='thredds.ucar.edu', port=80): Max retries exceeded with url: /thredds/ncss/grib/NCEP/NDFD/NWS/CONUS/CONDUIT/Best/dataset.xml (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000FC2489EF98>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

**Comment by cwhanse** [comment]
Is there a proxy involved?  If so I’d check your proxy settings first.

**Comment by Suraj--Peri** [comment]
I'm sorry, could you tell me how I'd go about checking the proxy? Thanks.

**Comment by wholmgren** [comment]
@Suraj--Peri there are a number of networking errors in your traceback. It is neither a memory issue nor anything to do with pvlib.
