### ISSUE TITLE
DOE request for information

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvlib-python#375]
I'm using this Issue to share a request from DOE for information about PV data and analysis needs, resources and tools.  As DOE's Solar Program is revising their strategic goals, they are requesting information about how the U.S. solar industry uses and values existing PV data resources, needs that can be addressed by data access, research and analysis, and opportunities to better engage stakeholders on the use and development of data resources.

Why do I share here?  Because pvlib originated as a DOE-funded project, and would not exist without that initial sponsorship.

Please consider taking the time to respond to DOE's request, before Oct 6.  

Here's the blog post on the PV Performance Modeling Collaborative, which contains links to DOE's request and instructions on how to respond:

[]https://pvpmc.sandia.gov/us-doe-requesting-feedback-by-oct-6-2017-about-pv-data-and-analysis-needs-resources-and-tools/

Thanks in advance.

**Comment by wholmgren** [comment]
pvlib-ers: please do respond to this request for information! 

Note that you do not have to respond to the entire RFI, so it could take as little as 10 minutes to go from this github thread to a submitted response.
