### ISSUE TITLE
Variables and Symbols extra references not available

### ISSUE THREAD

**Issue by josecyc** [pvlib/pvlib-python#380]
While trying to understand more deeply the variables, symbols and units I tried to go into the further sources at the bottom of this page: `http://pvlib-python-dacoex.readthedocs.io/en/latest/variables_style_rules.html` and was unable to get to any of the so-called further sources, except the one for SoDa Service. These are the issues each one of them has:

**1) Reference Variable List by PVPMC:** Unable to access the site, I need a username and password.
**2) IEC 61724:1998 – Photovoltaic system performance monitoring - Guidelines for measurement, data exchange and analysis:** The document has been withdrawn from this site and the only way to access it is through another link but it costs up to $170 usd!
**3) The Indian Standard referencing the global IEC standard is available online: IS/IEC 61724 (1998):** Link is broken

I also tried to edit the page, with the GitHub button at the top right but that link is also broken.

For new guys like us coming unto the project, it would be greatly appreciated to have these type of references to be working.

If I can be of help in any further way regarding this please tell me.

Thanks,

Jose

**Comment by wholmgren** [comment]
Thanks, those issues are new to me. I'm all for improving the references. I'm sure there are other parts of that page that need updates, too.

Maybe @cwhanse knows something about the login issue with the PVPMC website?

Regarding the editing... first, you linked to the documentation for a fork of this project. Here's the "official" version: http://pvlib-python.readthedocs.io/en/latest/variables_style_rules.html 

The edit link at the top of that page does work. You'll need to fork the library, edit your fork, and then make a pull request. See this page for more info on contributing: http://pvlib-python.readthedocs.io/en/latest/contributing.html

**Comment by dacoex** [comment]
@josecyc 
I was the inital creater of the page. I currently cannot create a PR.

>1) Reference Variable List by PVPMC: Unable to access the site, I need a username and password.

Link was changed upstream:
https://pvpmc.sandia.gov/resources-and-events/variable-list/

>2) IEC 61724:1998 – Photovoltaic system performance monitoring - Guidelines for measurement, data 
>exchange and analysis: The document has been withdrawn from this site and the only way to access it is >through another link but it costs up to $170 usd!

Finally, the standard was improved & published.
I assume the symbols are in:
IEC 61724-1:2017 Photovoltaic system performance - Part 1: Monitoring 
Unfortauntely, we cannot change the publication and copyright policy of IEC :-(
I think IEC should be the reference for symbols.

>3) The Indian Standard referencing the global IEC standard is available online: IS/IEC 61724 (1998):

I found an alternative link:
https://archive.org/details/gov.in.is.iec.61724.1998
