### ISSUE TITLE
irradiance.liujordan function doesn't use pressure arg

### ISSUE THREAD

**Issue by KonstantinTr** [pvlib/pvlib-python#386]
I believe pressure has no usage in this function: 

![image](https://user-images.githubusercontent.com/16244350/31705983-063bed7a-b3f0-11e7-95a0-864b51b86cc5.png)

The only call of liujordan is from cloud_cover_to_irradiance_liujordan of forecast.py doesn't pass pressure
![image](https://user-images.githubusercontent.com/16244350/31706079-66366566-b3f0-11e7-80c9-f50b338e7b57.png)
 
Is there any chance that pressure should be used somewhere within function?

**Comment by cwhanse** [comment]
No, atmospheric pressure is not used in the Liu – Jordan decomposition model.

If you are fixing this, please correct the spelling : tao should be tau.

Thanks!

**Comment by KonstantinTr** [comment]
@cwhanse Thanks for the feedback. I'll fix tau spelling as well.
