### ISSUE TITLE
Tracker rotations reveresed

### ISSUE THREAD

**Issue by caressmedown** [pvlib/pvlib-python#391]
I have been doing a deep dive making pvlib -python emulate pvsyst as close as possible. I think that the pvlib (python) has the tracker thetas swapped, as in the last time stamp rotation should be the first, and so on.  SAM and Pvsyst are in agreement here, pvlib is the outlier, so I suggest we move to their values so more people use pvlib :)

**Comment by cwhanse** [comment]
Can you share your python code that produces the result you describe?

**Comment by caressmedown** [comment]
It's just the single axis function that calculates tracker rotation from sun position as well as aoi. Haven't located the bug yet. Will do tomorrow
