### ISSUE TITLE
disc algorithm location

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#42]
The disc algorithm is currently in ``clearsky``, but I think ``irradiance`` is a better place for it (and the rest of the similar models that still need to be implemented #2 #4).

**Comment by wholmgren** [comment]
Thoughts @bmu @uvchik @Calama-Consulting? Would like to resolve this before we add some of the other matlab functions.

**Comment by bmu** [comment]
Should be moved, I think.
