### ISSUE TITLE
avoid and/or silence common warnings

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#428]
A handful of pvlib functions often cause spit out runtime warnings for things like dividing by 0 or comparing the size of a nan value to a float. We should avoid or silence the warnings that we know are ok. They also make the test output a pain to read.

Here's a possibly incomplete list:

- [x] irradiance.perez divide by 0
- [x] irradiance.perez comparison with nan
- [x] clearsky.simplified_solis comparison with nan
- [x] pvsystem.sapm divide by 0 in log
- [x] pvsystem.ashraeiam comparison with nan
- [x] pvsystem.physicaliam comparison with nan
- [x] pvsystem.adrinverter comparison with nan
- [x] pvsystem.v_from_i overflow

~I have some code ready for addressing the warnings in the perez model implementation. I'll post it soon.~

Checked items are addressed in #429.

**Comment by adriesse** [comment]
I think the readability of the code suffers (in terms of being able to quickly see what math is being done) with some of the changes you propose.  I sometimes disable certain warnings at the start of my scripts when they get on my nerves.  Could that be adequate for other users?  This suggestion could be put in the doc string for functions that are particularly annoying.
