### ISSUE TITLE
Historical GFS forecasts via pvlib

### ISSUE THREAD

**Issue by rivers31334** [pvlib/pvlib-python#438]
I feel forever new to the world of pvlib/python, but I appreciate all the time that is put into it. I have found myself using pvlib to query the GFS model for solar/weather forecasts. I noticed that in using this method via pvlib and python, I can only go up to a few days back when getting a forecast.

Does there exist a way to pull historical GFS forecasts going back in time?  There is a great possibility that I have a fundamental misunderstanding in how pvlib gets the GFS data and cleans it into a nice polished formatted dataframe. But if there exists a way to get that kind of data going back in time, I would love to learn.  Thank you for your help.

**Comment by wholmgren** [comment]
See https://github.com/pvlib/pvlib-python/issues/402#comment-355345988
