### ISSUE TITLE
update sam library files

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvlib-python#440]
We've fallen a few years behind the SAM releases, so I think it's time to update the module and inverter CEC files.

**Comment by wholmgren** [comment]
Good point. I have not looked at the new files. I hope the format is the same.

**Comment by wholmgren** [comment]
Oh, and were you planning to submit a pull request for this? I don't currently need anything from the new files, so I'm not likely to do it myself anytime soon.

**Comment by cwhanse** [comment]
Yes I'll do it.
