### ISSUE TITLE
DISC algorithm air mass

### ISSUE THREAD

**Issue by adriesse** [pvlib/pvlib-python#449]
As far as I can tell from reading the original report, the air mass value required is _not_ the pressure-corrected absolute air mass, but rather the relative air mass.  This affects downstream algorithms like `dirint`, `dirindex` and `gti_dirint`.

**Comment by cwhanse** [comment]
@adriesse you are correct that Maxwell et al report presents AM (air mass) as relative air mass (not adjusted for atmospheric pressure).  However, we based the Matlab function on NREL's coding of the DISC model [https://www.nrel.gov/grid/solar-resource/disc.html](url) which uses AM as absolute air mass.

We could change to relative air mass in `irradiance.disc` to remain strictly consistent with the publication, or leave as is (and add a reference) to remain consistent with NREL's code.  I can see arguments for either option.

**Comment by wholmgren** [comment]
We should at least add a note to the ``disc`` documentation of the ``pressure`` keyword argument. We could also allow ``pressure=None`` to ensure that no correction is applied.

**Comment by cwhanse** [comment]
I propose that we leave the DISC function as using absolute air mass, and enhance by allows `pressure=None` to turn off the conversion from relative to absolute air mass. Agree, or no?

**Comment by adriesse** [comment]
Sure.  The current default value `pressure=101325` effectively already does this, but `None` would represent the situation better.  A sentence or two for posterity in the doc string is probably the most important.
