### ISSUE TITLE
tracking algorithm: projection of the sun vector in the panel oriented coordinate system

### ISSUE THREAD

**Issue by Papayo974** [pvlib/pvlib-python#451]
Hi,
I suspect that for the projection on the y'-axis in the panel oriented coordinate system (x', y', z'), it's not "-z * sind(axis_tilt)" but "+z *  sind(axis_tilt)".

According to the definition of the panel oriented system, if the rotation axis is 90 degrees tilted the y' axis should be coincident with the vertical z axis pointing in the same direction.

Can anyone confirm or explain why it's a minus?

Thanks

**Comment by cwhanse** [comment]
The coordinate system follows that used in the reference (Lorenzo, E et al., 2011, "Tracking and back-tracking", Prog. in Photovoltaics: Research and Applications, v. 19, pp. 747-753.).  Lorenzo's coordinates for a south-oriented axis at 0 tilt are y=south, x=west, z=up, which is not the usual coordinate system  (x = East, y=North, z=up).  In the y=south, x=west coordinates, with a positive tilt meaning a tilt of the z axis towards the positive y axis, a tilt of +90 degrees puts the y' axis in the negative z direction.

We chose to keep Lorenzo's coordinate system to maintain traceability to the reference, hoping that choice would be more transparent than implementing the calculation (without a supporting description) using the conventional system.

If you see that the description and inline comments could be improved to make this clear, we welcome the pull request.
