### ISSUE TITLE
fix whatsnew problems

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#454]
From @cedricleroy comment [here](https://github.com/pvlib/pvlib-python/pull/444#issuecomment-387150524).

>I think f892664 did overwrite a couple of previous things in v0.5.2.rst
>
>There is a "0" here: f892664#diff-2df8cbc501f75a90135963ace8a28f63R1
>
>And the text here has been removed: f892664#diff-2df8cbc501f75a90135963ace8a28f63L15

**Comment by cwhanse** [comment]
Since f892664 was my pull request and it's merged, I should make a new pull request to add those lines back, correct?

**Comment by wholmgren** [comment]
That would be great!
