### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by bmu** [pvlib/pvlib-python#46]
If we agree on it, we could either completely rely on [pandas](http://pandas-docs.github.io/pandas-docs-travis/contributing.html) or give some rules, where we use our own conventions (in the [wiki](https://github.com/pvlib/pvlib-python/wiki/Development-information) or in the docs).

**Comment by wholmgren** [comment]
Most of the stuff I wrote was inspired by pandas (maybe I should have made that more clear), but I felt that we should have something more than just "go look at pandas" since new contributors might not yet understand the scientific python ecosystem. I'm open to changing this, though.

**Comment by bmu** [comment]
Ok, I think this is a good approach. However we could provide the link to pandas, if we agree on all of the thinks that are stated there.

**Comment by wholmgren** [comment]
I added a handful of links to the pandas pages. Feel free to edit anything.

**Comment by bmu** [comment]
Ok, thanks. I'll close this issue.

**Comment by wholmgren** [comment]
The new 0.16.1 pandas release has a new [Contributing to pandas](http://pandas.pydata.org/pandas-docs/stable/contributing.html) page. It's really good. I still think we should have a small wiki, but I'll add and emphasize links to this.

**Comment by wholmgren** [comment]
I renamed the *Development information* wiki to *Contributing to pvlib python* and rewrote some of the text. I hope we can get some other people to add-to/clarify the wiki in the future, so I'm going to leave this open for 0.3. I think @jforbess's perspective would be helpful here. I found it hard to strike a balance between high-level overview with links as opposed to detailed instructions.
