### ISSUE TITLE
Clarify module_parameters['EgRef'] usage, and set a default value

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvlib-python#462]
The CEC module parameters database does not contain the parameters EgRef or dEgdT. In the CEC model, and in the process NREL follows to generate the database from the CEC module data list, values EgRef = 1.121 and dEgdT = -0.0002677 are implicit.  PVLib for Matlab exposed EgRef and dEgdT as a model parameter (which it is) and let the user determine the appropriate value.  pvlib-python does likewise, however, readthedocs.io examples do not inform the user that s/he must specify EgRef and dEgdT nor do we provide default values when they are not specified.

I propose that we:
1) assign default values within `pvsystem.retrieve_sam('cecmod')` and
2) add to the example at [http://pvlib-python.readthedocs.io/en/latest/modelchain.html](url) to illustrate use of the CEC module model, and the opportunity to specify EgRef and dEgdT, if desired.

**Comment by adriesse** [comment]
Would it make sense to lobby NREL to put those parameters into their database?

**Comment by cwhanse** [comment]
It would.  I opened an Issue on the SAM GitHub.

**Comment by wholmgren** [comment]
If I understand your proposal correctly, it doesn't break any conventions. We avoid setting any parameters in the wrapper methods, but we do have some code to gracefully mesh method calls with function keyword arguments. See, for example, ``PVSystem.ashraeiam`` and ``PVSystem.physicaliam``.

So, we can:

1. Change function ``calcparams_desoto`` signature to include ``EgRef = 1.121`` and ``dEgdT = -0.0002677``, then
2. Add ``_build_kwargs`` call within ``PVSystem.calcparams_desoto``.

Open question in my mind as to whether or not step 1 is an appropriate change. I lean towards yes. And yes, there are alternative ways to accomplish the kwarg meshing.

Related but maybe separate... this reminds me that the ``calcparams_desoto`` function has a weird signature. Might be worth rethinking the signature separate from the constraints of the NREL/CEC database. Perhaps every module/cell parameter should be an argument or keyword argument, or every parameter should be wrapped up into a ``module_parameters`` dict (as in ``PVSystem.calcparams_desoto``).

**Comment by cwhanse** [comment]
I agree about the `calcparams_desoto` signature being awkward.  It's a direct transcription of the PVLib Matlab implementation which passed individual parameters and others bundled in a structure.  I'd prefer to see all parameters passed as individual keywords.    If we go with all keywords then we use `PVSystem.calcparams_desoto` to unpack the dict via `_build_kwargs` (thanks for pointing out this function!)  The most common use of `calcparams_desoto` is probably via `PVSystem.calcparams_desoto` where the `module_parameters` dict is very convenient.

**Comment by adriesse** [comment]
While you're at it, I would suggest removing the parameter M.  It's really a generic mismatch factor, which is perhaps better implemented externally to modify effective irradiance.  It doesn't actually become an "airmass modifier" until you use airmass to determine M.  I'm not sure where the proposed polynomial should be placed thought, since the other two spectral correction functions (FS and SAPM) are organized in different ways.  I don't know what the best solution is but I just wanted to draw your attention to this.

**Comment by cwhanse** [comment]
@adriesse I agree.  `pvsystem.calcparams_desoto` should expect effective irradiance as its input, not broadband-plane-of-array-after-reflection-losses which is what 'S' means in Desoto's paper.  We preserved that notation and usage in PVLib-matlab, but I don't think its necessary here. I would prefer the calcparams_xxxxx family of functions to have a common signature, and expect the same quantities as input as `pvsystem.sapm`
