### ISSUE TITLE
remove irradiance parameter from ModelChain.run_model

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#488]
#239 deprecated the irradiance parameter in ``ModelChain.run_model``. It's time to remove it.

**Comment by alamathe1** [comment]
@wholmgren Can I please help on this?

**Comment by wholmgren** [comment]
sure, feel free to make a pull request. I should add that the parameter needs to be removed from ``ModelChain.prepare_inputs`` as well.

**Comment by alamathe1** [comment]
@wholmgren Sure. I have removed the _irradiance parameter_ from ModelChain.run_model and ModelChain.prepare_inputs. Is there any preferred tests to be run for change or shall I go ahead and raise a PR?

**Comment by alamathe1** [comment]
@wholmgren I have removed the irradiance parameter from ModelChain.run_model and ModelChain.prepare_inputs. Is there any preferred tests that needs to be run or shall I raise a PR?

**Comment by wholmgren** [comment]
It looks to me like the ``pvlib/test/test_modelchain.py::test_weather_irradiance_input`` function needs to be removed, but otherwise no changes needed to the tests.

**Comment by alamathe1** [comment]
@wholmgren Raised https://github.com/pvlib/pvlib-python/pull/490 Please let me know if there's any modifications required to the PR.
