### ISSUE TITLE
move lambertw to singlediode-methods module

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#497]
**Problem**
some methods are in singlediode_methods while others are in pvsystem, makes sense for them to be together. also according to [this comment](https://github.com/pvlib/pvlib-python/pull/409#discussion_r199205566)
>this is a lot of lines to read within an if/else...

**Solution**
move lambertw to singlediode_methods

**alternatives**
do nothing

**Additional context**
see #408 , #409 , & #410

**Comment by mikofski** [comment]
@cwhanse and @wholmgren - maybe someone already asked this, but why didn't we just call this module "singlediode" why append `_methods`? seems like a redundant, no? Should we change it before v-0.6.0?

**Comment by wholmgren** [comment]
@mikofski I don't recall a discussion of ``singlediode.py`` vs. ``singlediode_methods.py``. I have a slight preference for ``singlediode.py``.
