### ISSUE TITLE
GitHub doesn't recognize the license

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#503]
**Describe the bug**
There should be a section near the top of the main repo overview page that shows the license
![GitHub Help: Adding a license to a repository](https://help.github.com/assets/images/help/repository/repo-license-indicator.png)
![GitHub Blog: License now displayed on repository overview](https://cloud.githubusercontent.com/assets/731773/18727946/1aa7b2fa-8019-11e6-84bd-178f93bcd8ee.png)

**To Reproduce**
1. Go to 'pvlib/pvlib-python' GitHub repository main page
2. Click on 'license'
3. Scroll down to 'anywhere'
4. See it's not there

**Expected behavior**
Users should be able to see the license immediately without having to look through the LICENSE document

**Screenshots**
Check out the license pages for pandas:
[github pandas repo](https://github.com/pandas-dev/pandas)
[pandas LICENSE file](https://github.com/pandas-dev/pandas/blob/master/LICENSE)
![image](https://user-images.githubusercontent.com/1385621/42664289-cd0e9008-85ee-11e8-9ca9-f68257164c89.png)

**Versions:**
 - ``pvlib.__version__``: any
 - ``pandas.__version__``:  any
 - python: any

**Additional context**
this might not bother some or most people

here are some links from github:
https://help.github.com/articles/licensing-a-repository/#detecting-a-license
https://blog.github.com/2016-09-21-license-now-displayed-on-repository-overview/
https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by wholmgren** [comment]
Any idea why not? It’s standard bsd 3. Maybe the fact that it’s copyrighted Sandia in 2013 and pvlib developers after that?

**Comment by mikofski** [comment]
yes I was comparing it to other bsd-3 licenses like pandas and pvmismatch and there is that difference, and maybe the missing bullets or numbers. Pandas also has line 1: "BSD 3-Clause License". [SunPower/PVMismatch](https://github.com/SunPower/PVMismatch/blob/master/LICENSE) license has no first line, but has numbers instead of bullets. The newlines don't seem to matter.

GitHub says this:
>If your repository is using a license that is listed on the Choose a License website and it's not displaying clearly at the top of the repository page, it may contain multiple licenses or other complexity. To have your license detected, simplify your LICENSE file and note the complexity somewhere else, such as your repository's README file.

**Comment by uvchik** [comment]
You could try to re-create the file using an official github template and adapt it afterwards.

https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by wholmgren** [comment]
Removing the second copyright line allowed github to recognize the license on my fork's master. Github suggests putting extra information in README.md. pandas split the copyright between license and AUTHORS.md. Either would work for me, though I lean towards AUTHORS.md. I think it's worth the effort/complexity so that we can do our part to improve the state of software licensing.

**Comment by wholmgren** [comment]
Some examples of authors files:

https://github.com/pandas-dev/pandas/blob/master/AUTHORS.md
https://github.com/Unidata/MetPy/blob/master/AUTHORS.txt
https://github.com/dask/dask/blob/master/AUTHORS.md

I prefer the pandas model because it sounds like a pain to explicitly keep track of authors, either manually or with a tool. I will make a pull request following this model.

**Comment by mikofski** [comment]
* I like pandas fix too
* IMO putting extra licence info in `AUTHORS.md` sense a little weird but, I don't want to overthink it, as is pvlib isn't using an `AUTHORS.md` file yet so why not
* IMO the way pandas is using `AUTHORS.md` is quite different from Unidata and Dask, since thos are just lists of contributors. In my experience keeping a list of contributors up to date is usually up to each contributor to add themselves, and I guess maintainers/owners police new contributors when merging as needed? Regardless, we as contributors to what's new instead, so, that was more than 2 cents.
