### ISSUE TITLE
Include SAM files in distribution

### ISSUE THREAD

**Issue by Calama-Consulting** [pvlib/pvlib-python#52]
It looks like this is related to the downloads from the NREL website. When I tried to manually download the files, it took about a minute for the first download to happen (and it was fine after that). We might want to consider hosting the files locally? I'm not sure what the limitations are on that.

**Comment by wholmgren** [comment]
The files total only 2 MB, so to me it doesn't seem like a big deal to include them along with the Linke turbidities and eventually the Driesse inverter database. This is what the Matlab version does too.

**Comment by Calama-Consulting** [comment]
I ran it again locally on my machine, and it worked fine. I also re-started the travisCI and we're now passing. So, I think this is fine for now. The advantage of pulling from SAM is that the database is always up to date, however a future addition might be to have a set of files included as a baseline to ensure that a user can use these algorithms without an internet connection, or if the website is down.

**Comment by wholmgren** [comment]
The links are actually to specific versions of the files (see [here](https://github.com/pvlib/pvlib-python/blob/fb7c1c6a2388b04102197825650a578b614a50c4/pvlib/pvsystem.py#L533)).

**Comment by bmu** [comment]
Is this resolved? I am trying to close the 0.1 milestone ;-)

**Comment by wholmgren** [comment]
Well, it's resolved in the sense that the test passes again, but there is still the question of if we should just include the files in the distribution. Another possibility is to remove this test from the standard test suite. Those all seem like 0.2 questions, though.

**Comment by wholmgren** [comment]
The same test failed again, though in a slightly different way and for only one of the builds. 

https://travis-ci.org/pvlib/pvlib-python/jobs/60250664

**Comment by Calama-Consulting** [comment]
I think it would be worthwhile to include the files locally, I'm putting together a PR

**Comment by wholmgren** [comment]
I'm going to push this to 0.3.
