### ISSUE TITLE
pvsystem.sapm_celltemp

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#54]
The ``pvsystem.sapm_celltemp`` function currently returns a dict ``{'tcell':tcell, 'tmodule':tmodule}``. I think it should return a DataFrame with the keys ``temp_cell`` and ``temp_module`` (as described in the [wiki](https://github.com/pvlib/pvlib-python/wiki/Variables-and-style-rules)).

I actually like the simplicity of the function parameter names here, but maybe they too should be changed.

**Comment by bmu** [comment]
I think they should be changed.
