### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by bmu** [pvlib/pvlib-python#55]
This issue is for discussion of the 0.2 release process.

**Comment by bmu** [comment]
For now, the date of the 0.2 milestone is set to April 30 2015. However I think this is not realistic.
Any suggestions?

**Comment by wholmgren** [comment]
Depends on if we want to keep everything currently labelled as 0.2. I think that 4 weeks a good amount of time to accomplish #2, #20, #30, #37, #42, #54, and #47. In addition, the testing issues should be at least partially addressed.

#29, #39, and #17 seem like they're going to require more thought and discussion to do well, so I think we'll need to limit the initial scope of those issues, label those parts of the library as experimental, or push them off.

**Comment by wholmgren** [comment]
We got a lot of positive feedback on the project at PVSC. The most common issue was installation, especially for new users on Windows. I want to capitalize on whatever extra interest we get out of PVSC, so, I'd like to resolve the easier issues and then release 0.2 with a conda package on Monday or Tuesday. I am going to devote some time today and over the weekend, and then we'll go with whatever state the project is in. I think I can knock out the list above except for #2.

Any objections @bmu @Calama-Consulting or others?

If nobody speaks up then I will break the rules and accept my own PRs.

**Comment by wholmgren** [comment]
I went ahead and made conda packages for 0.1 and updated the readme. Here's the process that I stumbled into https://github.com/pvlib/pvlib-python/wiki/Release-procedures

**Comment by bmu** [comment]
I can have a look at your PR's and merge them. However, I have to focus on my PhD in my spare time and it seems, that I won't get any working time to contribute to pvlib. So my own contribution will not be to much. Maybe we can shift some 0.2 issues to "someday" and release it as it is. I will start for some of "my" issues.

**Comment by wholmgren** [comment]
Great thanks @bmu.

**Comment by wholmgren** [comment]
Ok, my suggestion is that we go forward with the 0.2 release. We can make a 0.2.1 with tutorial improvements if @NelisW, @Calama-Consulting, or myself find the time.

**Comment by wholmgren** [comment]
@Calama-Consulting can you upload to PyPI if you think we're ready? I updated the whats new date and the version.

**Comment by wholmgren** [comment]
Closed by 263c90ef26
