### ISSUE TITLE
github dependency graph only shows setup, since no requirements

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#578]
**Describe the bug**
The [github dependency graph](../network/dependencies) only shows a few of pvlib-python's dependencies, for example, it doesn't list any of the optional extras ephem, siphon, netcdf4, scipy, numba, or tables.

**To Reproduce**
Check the [pvlib-python dependency graph](../network/dependencies)
1. Go to the [Insights](../pulse) tab
2. Click on [dependency graph](../network/dependencies) in the sidebar
3. Scroll down
4. See missing dependencies.

**Expected behavior**
Setting up a development environment requires a `requirements.txt` file. If there are optional dependencies, they can be listed in `requirements.txt` and GitHub will list them. You can use comments to separate the different sections, eg: `# docs`, `# testing`, `# optional`.

**Screenshots**
Here's the current dependency graph for pvlib:
![image](https://user-images.githubusercontent.com/1385621/45561658-1adb7900-b7fd-11e8-8b95-d7fd9cf75709.png)

Here's the current dependency graph for pvmismatch, not how there are 2 extra in requirements than in setup:
![image](https://user-images.githubusercontent.com/1385621/45561969-e0261080-b7fd-11e8-9ef5-86567c30066f.png)

**Versions:**
 - ``pvlib.__version__``: master
 - ``pandas.__version__``: any
 - python: any

**Additional context**
I think if pvlib were to add are `requirements.txt` with the following, GitHub would show these dependents, and developers could get start more easily:
```
# required
numpy>=1.10.1
pandas>=0.14.0
pytz
six
# optional
scipy
tables
numba
siphon
netcdf4
ephem
cython
# tests
pytest
pytest-cov
pytest-mock
nose
# docs
sphinx
ipython
sphinx_rtd_theme
numpydoc
matplotlib
jupyter
nbsphinx
```

**Comment by wholmgren** [comment]
My understanding from this Donald Stufft [post](https://caremad.io/posts/2013/07/setup-vs-requirement/) is that a requirements file is not appropriate for a library such as pvlib. 

> Setting up a development environment requires a requirements.txt file.

I don't understand this comment. I have ~20 different conda environments for pvlib development. I configured some of them manually, some with the conda .yml files from the ci directory or docs directory, and some with the new setup.py extras such as ``pip install pvlib[all]`` or ``pip install -e .[all]``. I agree that option 1 and 2 have their limitations, but option 3 works with any modern virtual environment tool. 

I'd say the github graph is a separate but related issue. Somehow github shows many dependencies for pandas despite the lack of a requirements file in that repository. Perhaps github inspects the tox.ini file? I don't know much about tox.

In any case, jupyter and nbsphinx are no longer used in the doc build so you can remove them from your list.

**Comment by mikofski** [comment]
I see what you mean, reading that and a [similar post](https://blog.miguelgrinberg.com/post/the-package-dependency-blues) about web-apps vs. libraries.

But when I am trying to duplicate someone else's environment for hacking on their project, I usually use:

```bash
pvlib $ virtualenv [-p python3] venv  # optionally specify python
pvlib $ . venv/bin/activate  # activate venv
pvlib $ pip install -r requirements.txt  # install requirements
```
and AFAIK many remote environments also do this automatically, when they are trying to infer your environment.

That just works for me, and in my experience it avoids a lot of problems with different versions, because I know that the virtual environment is clean (*). But I guess I can just use `pip install -e .[ALL]`, I think it will work the same way, so I'll close this for now. Thanks!

**Comment by wholmgren** [comment]
Sounds good. I am open to revisiting this if ``[all]`` doesn't end up being a good solution.
