### ISSUE TITLE
MANIFEST.in is incomplete

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#579]
The ``MANIFEST.in`` file is missing ``LICENSE``. It should probably also include ``AUTHORS.md``. Maybe it should include the docs source, though this is a little complicated due to how sphinx generates new source files.

A few examples:

- [python cookie cutter template](https://github.com/NSLS-II/scientific-python-cookiecutter/blob/master/%7B%7B%20cookiecutter.repo_name%20%7D%7D/MANIFEST.in)
- [metpy](https://github.com/unidata/metpy/blob/master/MANIFEST.in)
- [xarray](https://github.com/pydata/xarray/blob/master/MANIFEST.in)
- [pandas](https://github.com/pandas-dev/pandas/blob/master/MANIFEST.in)
- [matplotlib](https://github.com/matplotlib/matplotlib/blob/master/MANIFEST.in)

**Comment by mikofski** [comment]
AFAIK this will only affect the source distribution, from, `python setup.py sdist`, not wheels. See [PVMismatch](https://github.com/SunPower/PVMismatch/blob/master/MANIFEST.in)
