### ISSUE TITLE
update link at pvpmc

### ISSUE THREAD

**Issue by dacoex** [pvlib/pvlib-python#59]
https://pvpmc.sandia.gov/resources-for-members/pv_lib-toolbox/

"Download the PVLIB_Toobox for Python (This sends you to an external GitHub site)"
at the bottom points to 
https://github.com/Sandia-Labs/PVLIB_Python

**Comment by wholmgren** [comment]
@Calama-Consulting do you know who to contact at Sandia about changing this?

**Comment by wholmgren** [comment]
Josh Stein updated the link today.
