### ISSUE TITLE
make new PSM reader for iotools

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#592]
**Problem**:
This new API is not trivial I think I was able to download data once, but it wasn't immediately intuitive to me.

**Proposal**:
Given a user's NREL API key, they can get PSM data and use it for weather and solar resource

**Alternatives**
just figure it out myself, then maybe an iotool to consume whatever is downloaded

**Additional context**
[nrel psm api v2](https://developer.nrel.gov/docs/solar/nsrdb/psm_data_download/)
[new nsrdbsource](https://nsrdb.nrel.gov/current-version)
[download instructions](https://nsrdb.nrel.gov/download-instructions)
related to #272

**Comment by cwhanse** [comment]
Maybe not simpler, but SAM has automated download of NSRDB data, and once we can access SAM methods from pvlib, we could leverage the SAM capability.  That offloads maintaining the connection to the NSRDB websource onto NREL.
