### ISSUE TITLE
solarposition.hour_angle is inefficient and fails on some pandas versions

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#598]
**Describe the bug**
For some reason related to timezone handling, the `solarposition.hour_angle` function fails on pandas versions 0.15-0.18. We test 0.14 and latest. Apparently we were on pandas 0.19 or greater when this function was created.

Also, the loop over datetime values is probably slow.

```python
    hours = np.array([(t - t.tz.localize(
        dt.datetime(t.year, t.month, t.day)
    )).total_seconds() / 3600. for t in times])
```

I think this gives the same result:

```python
hours = (times.astype(int) - times.normalize().astype(int)) / 1e9 / 3600
```

**Versions:**
 - ``pvlib.__version__``: 0.6.0
 - ``pandas.__version__``: 
 - python:

**Additional context**
probably should address #597 first

**Comment by mikofski** [comment]
@wholmgren I believe this may be related to the pandas issues I observed in #583 - I noticed this `hour_angle` code, and I thought I should have addressed it then, but I didn't. It was my bad code from the Bird clear sky model, sorry!

**Comment by wholmgren** [comment]
No worries, Mark. Do you want to address this and #597 in #583? Or do you think we should handle them separately?

**Comment by mikofski** [comment]
I will address them, but I'd rather open a new PR to fix the `hour_angle` issues, unless you would prefer not

**Comment by wholmgren** [comment]
New PR sounds good to me.
