### ISSUE TITLE
Ecmwf reader of AOD and Pwat reader for iotools

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#602]
I have a reader from [pvsc44](../../../mikofski/pvsc44-clearsky-aod/blob/master/all_ecmwf_macc.py) that makes an ["atmosphere" object](https://github.com/mikofski/pvsc44-clearsky-aod/blob/master/pvsc44_clearsky_aod/ecmwf_macc_tools.py). Should something like this be added to `iotools`?

**Comment by cwhanse** [comment]
I'm not opposed to adding functions that read from ECWMF files, but @wholmgren do we want a new object, or a `iotools.ecmwf` module?

**Comment by wholmgren** [comment]
Sorry I missed this until now. That seems like a useful thing to add to `iotools`. I would quickly merge a PR with a scope limited to reading AOD data from MACC. `iotools.ecmwf` sounds like a bigger design/scope challenge. In a similar spirit, I'd prefer a more specific class name such as `ECMWF_AOD_PW`.

**Comment by mikofski** [comment]
Okay, I thinking I can do that, and quite frankly I'd rather limit this to AOD and Pwat, because the amount of data at soda pro and ecmwf is staggering, and I wouldn't know where to start.

>In a similar spirit, I'd prefer a more specific class name such as `ECMWF_AOD_PW`

I wasn't sure what you meant. It's all caps, it's this a constant? In lieu of `Atmosphere`?

**Comment by wholmgren** [comment]
Class name, not a constant. How do you name python class that’s an
acronym???

Atmosphere could mean a lot of things if it’s associated with weather model
data.

**Comment by mikofski** [comment]
Q: should iotools assume that the user has already obtained the data from the ecmwf API and just parse the files? Navigating their API is a challenge, at least for me. Is it okay to include downloading the data in iotools too somehow? Like `download_ecmwf_aod_pwat()`?

**Comment by wholmgren** [comment]
Up to you - I’m trying to take a more flexible approach to iotools. You can
check out our recent iotools additions for some examples of how we tried to
decouple the core parsing features from the api navigation features.

**Comment by mikofski** [comment]
FYI: I was queued for an hour on their server, even using the API, before my data finally downloaded.
