### ISSUE TITLE
add Shading, Soiling, and Reflection Losses

### ISSUE THREAD

**Issue by dacoex** [pvlib/pvlib-python#61]
These seem to miss on the environmental input side:
https://pvpmc.sandia.gov/modeling-steps/1-weather-design-inputs/shading-soiling-and-reflection-losses/

Maybe this meta issue can track this as mentioned in 
https://github.com/pvlib/pvlib-python/issues/2#issuecomment-74643819

**Comment by wholmgren** [comment]
PRs for shading and soiling models are welcome. To my knowledge, this is not something that's currently in the Matlab project.

There are already two reflection loss functions: ``pvsystem.physicaliam`` and ``pvsystem.ashraeiam``. Did you want something different?

**Comment by cwhanse** [comment]
I think this can be closed as a general issue, with #860 #669 #1017 and all of `pvlib.iam`.
