### ISSUE TITLE
Release 0.6.1

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#613]
Here's the list of issues/PRs marked with the 0.6.1 milestone: https://github.com/pvlib/pvlib-python/milestone/22

I think we should push the harder items to 0.7 and try to finish 0.6.1 in the next few weeks.

**Comment by cedricleroy** [comment]
https://github.com/pvlib/pvlib-python/pull/600 should be ready too.

**Comment by wholmgren** [comment]
Are we finally ready to release 0.6.1? I think we only need to finalize the what's new.

**Comment by adriesse** [comment]
No, I would like to make changes to pvsyst_celltemp.

**Comment by adriesse** [comment]
Done!

**Comment by wholmgren** [comment]
thanks @cwhanse for the release! closing...
