### ISSUE TITLE
improve ground reflection when sun is behind panels

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#617]
**Is your feature request related to a problem? Please describe.**
I think that the ground reflection is over-estimated when the sun is behind the panels.

The following image shows a panel facing the ground, tilted 160&deg; down and facing northeast at 70&deg; on Jan-1 from 8AM to noon in Oakland, CA.
![back_side_diffuse](https://user-images.githubusercontent.com/1385621/48378463-8cad3300-e685-11e8-87f3-b707643fbee4.png)

The ground reflection on this panel seems quite high when you consider the diffuse sky for a similar panel, tilted 20&deg; and facing southeast at 250&deg;
![front_side_diffuse](https://user-images.githubusercontent.com/1385621/48378560-de55bd80-e685-11e8-9346-6f613dac3577.png)

Another way to think of these panels are as the backside and frontside of the same panel.

I think the reason the backside ground reflection is over-estimated is because the it is not considering that a portion of the ground it sees is shaded, so the GHI should not include the direct component. If I remove the beam and re-calculate I get what seems like a more reasonable value.

But the actual backside ground POA would be in between these because some of the ground visible to the backside is in shade and some is not.

**Describe the solution you'd like**
This may just be a continuation of #421 or some other bifacial issue or PR. But I still think it would be relevant for the `get_ground_diffuse` function anyway.

I think we should calculate where the shadow would be on a flat surface, divide the ground into two regions, and add the view factors algebraically.

**Describe alternatives you've considered**
Well for the front side this delta is obviously nearly zero and probably not measurable, so maybe just wait for #421 or some other bifacial solution to be completed.

**Additional context**
Probably related to #421

**Comment by cwhanse** [comment]
> I think that the ground reflection is over-estimated when the sun is behind the panels.

I agree, if we're comparing model to reality.  The ground-reflected irradiance model in use assumes:
1) the ground visible to the panel is the half-plane extending to the horizon (no obstructions), and
2) the irradiance on this half-plane is GHI (no shadows).

A better model requires accounting for shadows on the ground that reduce reflected irradiance to the panel. That's the essence of the rear-side irradiance model anticipated by #421.  Our analysis and measurements have shown that the rear-side irradiance is ~80% from ground reflections.

**Comment by kanderso-nrel** [comment]
With infinite_sheds and pvfactors available now, shall we close this?  I suppose we could note the simplifying assumptions (Lambertian surface reflectance, also) in `get_ground_diffuse`'s docstring.

**Comment by mikofski** [comment]
yes, I agree! Thanks Kevin for keeping tabs on stale issues 👍
