### ISSUE TITLE
irradiance.get_total_irradiance

### ISSUE THREAD

**Issue by LorenzoBottaccioli** [pvlib/pvlib-python#627]
Hi All,

I need clarification of the value of  ``surface_azimuth` from my test I see that south is 0° nord is 180°. from the web page of the documentation I read:

[surface_azimuth:numeric
Panel azimuth from north.](https://pvlib-python.readthedocs.io/en/latest/generated/pvlib.irradiance.get_total_irradiance.html)

Wich is the correct way of specifing the surface azimuth?

Best

**Comment by cwhanse** [comment]
Hi Lorenzo, can you share some code so I can see where the result `surface_azimuth = 0` comes from?  

We prefer that usage questions are asked on StackOverflow or googlegroups, see the Getting Support section of [pvlib-python](https://github.com/pvlib/pvlib-python)
