### ISSUE TITLE
Happy birthday :-)

### ISSUE THREAD

**Issue by uvchik** [pvlib/pvlib-python#647]
![pvlib_birthday](https://user-images.githubusercontent.com/4760584/51427848-978fc100-1bfc-11e9-8c19-e6223271500d.png)

Happy birthday pvlib

I found, that the first code commit (45446774) was on January 19th, 2014. This is more than 1000 commits ago.

Thank you for 5 years of open pv simulation tools.

For me the pvlib is one of the most inspiring community projects. Many time I thought in my own projects: "Let's have a look how the pvlib did it...."

The greatest credit for this, however, is due to @wholmgren, who always gives a friendly feedback, even to the most stupid issues :smirk:

Keep on coding...

**Comment by wholmgren** [comment]
Thanks @uvchik for the kind words. I give the greatest credit to the founders of the pvlib projects (Josh Stein, Cliff Hansen, Dan Riley, Rob Andrews, probably more) and to the community that has improved the project and kept it interesting!
