### ISSUE TITLE
ValueError: spa.py

### ISSUE THREAD

**Issue by BlevinsGagarin** [pvlib/pvlib-python#671]
While profiling a script, which uses pvlib, I got a ValueError in spa.py -> line 259 .. 270

I found a StackOverFlow topic, that fixed the problem: "You cannot resize NumPy arrays that share data with another array in-place using the resize method by default. Instead, you can create a new resized array using the np.resize function:"

I changed the lines 259 .. 270 to

np.resize(TABLE_1_DICT['L1'], (64, 3))
np.resize(TABLE_1_DICT['L2'], (64, 3))
np.resize(TABLE_1_DICT['L3'], (64, 3))
np.resize(TABLE_1_DICT['L4'], (64, 3))
np.resize(TABLE_1_DICT['L5'], (64, 3))

np.resize(TABLE_1_DICT['B1'], (64, 3))

np.resize(TABLE_1_DICT['R1'], (64, 3))
np.resize(TABLE_1_DICT['R2'], (64, 3))
np.resize(TABLE_1_DICT['R3'], (64, 3))
np.resize(TABLE_1_DICT['R4'], (64, 3))

**Comment by wholmgren** [comment]
@BlevinsGagarin please specify the versions of python, pvlib, and numpy that you're using. I suspect that this was fixed by #634 and updating pvlib will fix your problem.

**Comment by cwhanse** [comment]
@BlevinsGagarin did an update to pvlib v0.6.1 fix the problem?

**Comment by BlevinsGagarin** [comment]
Thanks for your reply. The update fixed them problem!

**Comment by cwhanse** [comment]
Glad to hear it.
