### ISSUE TITLE
Might be of interest: duecredit

### ISSUE THREAD

**Issue by yarikoptic** [pvlib/pvlib-python#673]
https://github.com/duecredit/duecredit
Disclaimer: I am involved

Ran into pvlib for possible integrations of asv into GitHub workflow, saw that you take citations seriously, cared to chime in

Cheers!

**Comment by wholmgren** [comment]
Thanks for the suggestion. duecredit looks interesting. I'll keep an eye on the project and adoption and consider adding in the future.
