### ISSUE TITLE
Add function for interpolated IAM model

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvlib-python#679]
**Describe the solution you'd like**

A commonly used model for IAM is to interpolate along a user-supplied list of (AOI, IAM) points, e.g., pvsyst offers this model option.

Implement a function `iam_interpolated` with parameters being a list of (AOI, IAM) points.

**Additional context**
pvsyst uses linear interpolation.

**Comment by wholmgren** [comment]
I'm not entirely opposed to adding a one-line wrapper around numpy or scipy interpolate 1D functions. An alternative to consider is only a documentation example that demonstrates using those functions for this purpose. Or ask and answer the question on stackoverflow.

**Comment by cwhanse** [comment]
Good point.  I think it would be useful as a PVSystem method, when the (AOI, IAM) points are packaged with module_parameters.

**Comment by mikofski** [comment]
Or perhaps in the model chain? Is there a pvsyst model chain for user supplied IAM lookup?

**Comment by cwhanse** [comment]
closed by #752
