### ISSUE TITLE
Naming pattern for IAM functions

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvlib-python#680]
**Is your feature request related to a problem? Please describe.**
It may be easier for users to find and select IAM functions if the function names start with the prefix `iam`, e.g., `iam_ashrae` rather than the current pattern placing `iam` as a suffix `ashraeiam`

**Describe the solution you'd like**
Rename `physicaliam`, `ashraeiam`, etc. and deprecate old names.

**Comment by wholmgren** [comment]
Related to https://github.com/pvlib/pvlib-python/issues/436... I currently prefer to see a new module `iam.py` with functions `physical`, `ashrae`, etc.

**Comment by cwhanse** [comment]
Starting on a PR for this.  `iam.py` conflicts with the often-used variable `iam`, e.g., `iam = pvsystem.ashraeiam()` in the current code.  Suggestions? Seems like a good idea to keep `iam` available for users to name the output of these functions.

**Comment by wholmgren** [comment]
I don't have a better idea, but I don't think we need to worry about what variables might exist in user code. There's only a name conflict when the module is imported as `from pvlib import iam`. While that's a common pattern, I don't think it's frequent enough to justify choosing a worse name for our module.
