### ISSUE TITLE
docs: broken link from SingleAxisTracker to PVSystem

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#684]
**Describe the bug**
https://pvlib-python.readthedocs.io/en/latest/api.html#singleaxistracker

>Inherits the PV modeling methods from :ref:PVSystem:.

link isn't rendering , not sure why, there is a document called `_pvsystemdoc` with a subsection called ["pvsytem"](https://pvlib-python.readthedocs.io/en/latest/pvsystem.html#pvsystem) but maybe there are too many "pvsystem" references? or maybe it's case sensitive?

Or was this link supposed to be to the API class definition, that seems more likely to me.

**Comment by wholmgren** [comment]
> Or was this link supposed to be to the API class definition, that seems more likely to me.

this.
