### ISSUE TITLE
Error message 'erbs() got an unexpected keyword argument 'min_cos_zenith''

### ISSUE THREAD

**Issue by kkoen** [pvlib/pvlib-python#689]
On Python 3.7.3, PVLIB 0.6.1, Pandas 0.24.2, the following code:
`df= pvlib.irradiance.erbs(df.ghi, sun.zenith, df.index, min_cos_zenith=0.065, max_zenith=85)`
returns 
> erbs() got an unexpected keyword argument 'min_cos_zenith'.

Maybe this is because I use PVLIB 0.6.1 while `min_cos_zenith=0.065, max_zenith=85` were introduced in PVLIB 0.6.2. But, how to upgrade PVLIB to the newest version? In my machine, none of the following works: `pip install pvlib`, `pip install --upgrade pvlib`, `pip install pvliv ==0.6.2`. 

Any help is appreciated.

**Comment by wholmgren** [comment]
> Maybe this is because I use PVLIB 0.6.1 while min_cos_zenith=0.065, max_zenith=85 were introduced in PVLIB 0.6.2.

Yes.

>how to upgrade PVLIB to the newest version?

pvlib 0.6.2 has not yet been released. You can install the unreleased code using pip install git+[protocol][repository] https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support
