### ISSUE TITLE
PVWatts_loss was applied on AC calculation

### ISSUE THREAD

**Issue by yxh289** [pvlib/pvlib-python#696]
Hi, 
    In the description of pvwatts_losses function, the losses are applied on DC side:
'Calculates DC power losses according the PVwatts model using pvwatts_losses() and self.losses_parameters.`' 
    However I found that in pvlib.modelchain.ModelChain.pvwatts_losses, PVwatts loss was applied to AC. 
'def pvwatts_losses(self):
        self.losses = (100 - self.system.pvwatts_losses()) / 100.
        self.ac *= self.losses
        return self'
   When system have high DC/AC ratio, AC power output clips at a lower level as a result of these losses applied on the AC side.

**Comment by wholmgren** [comment]
thanks @yxh289. pull request welcome.

**Comment by cwhanse** [comment]
Concur with the bug report.  May have been due to coding following the older PVWatts description, rather than the v5 document.  Or a simple typo.

**Comment by pasquierjb** [comment]
The post-inverter losses such as the AC wiring losses and AC Availability should in theory only apply to the AC power and not be subjected to inverter clipping.

**Comment by kanderso-nrel** [comment]
@pasquierjb conceptually that might be true, but in this case we're just sticking with the original spec: per Section 11 of the [PVWatts Version 5 Manual](https://www.nrel.gov/docs/fy14osti/62641.pdf), "Losses in the system that are not explicitly modeled are provided by the user as a percentage of DC energy."

See also #1350
