### ISSUE TITLE
pvfactors 1.0.0 breaks bifacial.pvfactors_timeseries

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#699]
**Describe the bug**
Running `bifacial.pvfactors_timeseries` with pvfactors 1.0.0 results in `ModuleNotFoundError: No module named 'pvfactors.timeseries'`

**To Reproduce**
Install pvfactors 1.0.0. Run `pytest test_bifacial.py`

**Expected behavior**
No error.

**Screenshots**

**Versions:**
 - ``pvlib.__version__``: 0.6.1
 - ``pandas.__version__``: n/a
 - python: n/a

@anomam thoughts?

**Comment by anomam** [comment]
hey sorry I've been falling behind on a lot of things including updating the pvfactors version in pvlib, I should be able to get to it in the next few days. My apologies!
