### ISSUE TITLE
appveyor builds failing due to solarposition with numba warnings

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#713]
#698 introduced a few new checks for warnings with the numba solar position method. These checks seem to fail at random on the appveyor tests.

Options:
* fix/change the test
* add an xfail decorator to the test when on windows

Ideally, someone that uses Windows could reproduce and fix on their machine. @mikofski can you reproduce?

**Comment by mikofski** [comment]
Sorry for delay ...

**Comment by wholmgren** [comment]
@mikofski no problem. The new windows tests on azure pipelines in #715 don't error, so I give up.
