### ISSUE TITLE
v0.6.4

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvlib-python#736]
Given other demands and the anticipated scope of 0.7.0, we should have at least one more minor release before 0.7.0.  Opening this issue to discuss what goes in 0.6.4, beyond issues/PRs with the milestone label.

#718 ?  Will provide one way to close #587 and closes #511.  #708 also?  belongs in the same family.

Other issues to close with v0.6.4?

**Comment by mikofski** [comment]
OK, sounds good. I'll put some effort into closing #708 and making sure it will work with #718. Any guidance would be appreciated.

**Comment by cwhanse** [comment]
Happy to help with #708 what issues are still outstanding?

**Comment by wholmgren** [comment]
Looks like a 0.6.4 tag was accidentally created and pushed so a pypi release was triggered. Does it need to be deleted? If so I will find time to do it next week. 

https://pypi.org/project/pvlib/

**Comment by cwhanse** [comment]
Please delete. I confused a tag with a milestone, wanted the latter.

**Comment by wholmgren** [comment]
I deleted 0.6.4 from pypi. The next release must be 0.6.5 or greater.

**Comment by wholmgren** [comment]
On the merits of this... I suggest that we move ahead with 0.7 rather than make another 0.6.x release. We can reduce the scope of 0.7.0 if we want to. The next release is the first that is python 3 only, which also argues in favor of a 0.7 release rather than 0.6.5. It would be possible to create an 0.6 maintenance branch for parallel development but that is not something I'm willing to put time into.

**Comment by cwhanse** [comment]
I'm OK reducing the scope if we're ready to drop python 2 coverage. I don't think a parallel branch is worth the effort until we hear from someone that they need it.

We planned some API-breaking changes e.g. #682 for 0.7. Do we want to keep those in scope, or push them down the calendar?

**Comment by wholmgren** [comment]
I suggest keeping #682 in scope. From a quick look, I think it only needs minor updates to the deprecation wrappers to indicate that user code will break starting with 0.8.

**Comment by cwhanse** [comment]
We are skipping v0.6.X and moving to v0.7.0 as the next release
