### ISSUE TITLE
`forecast.get_data` doesn't allow extra kwargs

### ISSUE THREAD

**Issue by odow** [pvlib/pvlib-python#745]
**Describe the bug**

`forecast.get_processed_data` accepts `**kwargs` (good) and passes these to `get_data` (good) and `process_data` (good):
https://github.com/pvlib/pvlib-python/blob/91c6a559feab740a346099f020fedf828ad9a557/pvlib/forecast.py#L306-L306
but `get_data` doesn't allow superfluous keyword arguments (bad):
https://github.com/pvlib/pvlib-python/blob/91c6a559feab740a346099f020fedf828ad9a557/pvlib/forecast.py#L202-L204

Is the fix just to add `**kwargs` as the last argument to `get_data`? If so, you can assign this issue to me and I'll make a PR.

**To Reproduce**

```python
import datetime
import pandas
from pvlib import forecast

forecast.NDFD().get_processed_data(
    38.238875, -117.363598, 
    pandas.Timestamp(datetime.datetime.now(), tz='US/Central'),
    pandas.Timestamp(datetime.datetime.now(), tz='US/Central') + pandas.Timedelta(hours = 12),
    how = 'liujordan'
)
```
Yields
```python
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/anaconda3/envs/tonopah/lib/python3.7/site-packages/pvlib/forecast.py", line 306, in get_processed_data
    return self.process_data(self.get_data(*args, **kwargs), **kwargs)
TypeError: get_data() got an unexpected keyword argument 'how'
```

**Expected behavior**

I expect that `get_processed_data` is equivalent to:
```python
model = forecast.NDFD()
data = model.get_data(
    38.238875, -117.363598, 
    pandas.Timestamp(datetime.datetime.now(), tz='US/Central'),
    pandas.Timestamp(datetime.datetime.now(), tz='US/Central') + pandas.Timedelta(hours = 12)
)
model.process_data(data, how = 'liujordan', extra_kwarg=False)
```
Note how I can pass `extra_kwarg` without any problem.

**Versions:**
 - ``pvlib.__version__``: 0.6.3
 - ``pandas.__version__``:  0.24.2
 - python: 3.7.3

**Comment by wholmgren** [comment]
Good catch. I'm surprised that we've not seen this until now. 

I agree that adding `**kwargs` to `get_data` is the cleanest way forward. I try to avoid using `kwargs` in the pvlib API, but we're already using it extensively within `forecast.py` and I don't see another good option.
