### ISSUE TITLE
New SAM csv files available

### ISSUE THREAD

**Issue by jforbess** [pvlib/pvlib-python#75]
SAM just released new equipment CSVs dated 2015-06-30. Not sure if there is a better fix for the retrieve_sam function than just to update the URL. Probably worth updating for 0.2.1.

**Comment by jforbess** [comment]
Also, they are in a slightly different format. Of course.

**Comment by wholmgren** [comment]
Thanks for pointing that out. I agree that this should be fixed in 0.2.1. Can you make the fix and pull request?

**Comment by jforbess** [comment]
Yes, I'll do it this weekend.

**Comment by wholmgren** [comment]
Closed in #80
