### ISSUE TITLE
Rounding issue in clearsky.py _linearly_scale method

### ISSUE THREAD

**Issue by alexandermorgan** [pvlib/pvlib-python#754]
**Describe the bug**
In the _linearly_scale method, there are two logic statements (lines 316 and 321) that first round values to one decimal place, then compare if <= .5. Since they're being rounded first, values like .54 would become .5, then the check <= .5 would actually be true. Also, from a performance standpoint, there is no reason to round first, we could instead just do the comparison immediately. If you actually want to check if values are < .55, then write that explicitly and modify the comment on line 314. Or keep <= .5 and the leave the comment as is, but either way, there's no need to round and compare to a float. I can make a pull request for either approach, please just let me know what's preferred.

**To Reproduce**
```
>>> import numpy as np
>>> arr = np.array([.49, .50, .54, .55, .56])
>>> np.around(arr, 1) <= .5  # current behavior
array([ True,  True,  True, False, False])
>>> arr <= .5  # intended behavior and also much faster
array([ True,  True, False, False, False])
>>> arr < .55  # equivalent to current behavior but much faster
array([ True,  True,  True, False, False])

```
**Expected behavior**
I would have expected values like .54 to raise an error in this if block, but they don't.

**Screenshots**

**Versions:**
 - ``pvlib.__version__``: 0.6.3
 - python: 3.5.2

**Additional context**
Removing the unnecessary rounding operation reduces the runtime of these logic checks by about 60%.

**Comment by wholmgren** [comment]
@mikofski you added this code in #264. Thoughts?

**Comment by mikofski** [comment]
No, I can't remember what my thinking was here. I believe @alexandermorgan is correct, and the call to `np.around()` is unnecessary. Thanks for the catch!

**Comment by alexandermorgan** [comment]
Ok, I'll make a PR that removes the np.around calls and uses <= .5 comparisons (the intended, but not current, behavior).

**Comment by alexandermorgan** [comment]
@mikofski I made a patch with these changes, but it fails pvlib/test/test_clearsky.py -> test_likne_turbidity_corners(). It fails because the current approach basically rounds anything below .55 to .5. So one of the test cases has these values:
outputmin = 0
outputmatrix = -0.5000000000000568
So in line 320 of clearsky:
        if np.around(output - outputmatrix, 1) <= .5:
This evaluates to true, because it rounds the value that's slightly above .5, down to .5 first, before checking if it's <= .5. Do you want to preserve this behavior? If so, then I'll just change the comparison to <= .55. I think I should change the test though, to assert that it raises an error with this value. If you're worried about floating point inaccuracies, I could make the comparison <= .50000001 or something like that.

**Comment by mikofski** [comment]
Aha, yes this explains why I had originally rounded, because of the issue in comparing floats.

    # If the index is still out of bounds after rounding, raise an error.
    # 0.500001 is used in comparisons instead of 0.5 to allow for a small
    # margin of error which can occur when dealing with floating point numbers.

Good catch, I agree with good
