### ISSUE TITLE
loading bifacial module

### ISSUE THREAD

**Issue by toddkarin** [pvlib/pvlib-python#766]
The __init__.py should have a line
```python
from pvlib import bifacial
```
to import the bifacial module. Otherwise it can't be used!

**Comment by markcampanelli** [comment]
While I'm not sure if there are criteria for adding this line (e.g., stability of the automatically imported module), there is definitely a work around in the meantime. This works at a terminal:
```terminal
python -c "import pvlib.bifacial as bifacial; print(type(bifacial)); print(bifacial.PVFactorsReportBuilder())"
```

**Comment by toddkarin** [comment]
Yes, that's a workaround -- it just took me a moment to figure this out since the pvlib documentation says there is a bifacial module, but it is not loaded by default (unlike all the other modules). Someone with less python experience might not be able to figure this out.

**Comment by wholmgren** [comment]
Thanks @toddkarin and sorry for missing this until now.
