### ISSUE TITLE
fix documentation references to inverter/module data

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#786]
The CEC data update in #767 broke the documentation. At least the [ModelChain](https://pvlib-python.readthedocs.io/en/latest/modelchain.html) page is broken, maybe more.

**Comment by cwhanse** [comment]
Scanning the pages, these are also broken:
[PVSystem attributes](https://pvlib-python.readthedocs.io/en/latest/pvsystem.html#pvsystem-attributes)
[PV Power Forecast](https://pvlib-python.readthedocs.io/en/latest/forecasts.html#pv-power-forecast)

**Comment by birgits** [comment]
In the course of fixing this it would also be nice to [fix the link](https://github.com/pvlib/pvlib-python/blob/master/pvlib/pvsystem.py#L1803) to where the original files are downloaded from. I would have fixed it but could not find where the data sets are hosted. 
Further, it would be great to provide a link to some documentation of the data sets in order for a user to figure out the meaning and units of the provided parameters. I think this link would be helpful:
https://sam.nrel.gov/photovoltaic/pv-sub-page-2.html

**Comment by cwhanse** [comment]
> In the course of fixing this it would also be nice to fix the link to where the original files are downloaded from. I would have fixed it but could not find where the data sets are hosted.

Thanks for pointing out this old link. The current [link](https://github.com/NREL/SAM/tree/develop/deploy/libraries).

> Further, it would be great to provide a link to some documentation of the data sets in order for a user to figure out the meaning and units of the provided parameters. I think this link would be helpful:
> https://sam.nrel.gov/photovoltaic/pv-sub-page-2.html

Agree, and again, thanks!
