### ISSUE TITLE
rethink module-level model parameters dictionaries

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#789]
#783 is adding a `iam.IAM_MODEL_PARAMS` dict that's simply sets of required parameters for IAM models. 

#682 added `temperature.TEMPERATURE_MODEL_PARAMETERS` that includes default values.

#548 added `pvsystem.DC_MODEL_PARAMS` that's also only sets of required parameters.

We should reconsider if we want to expose these dictionaries to users.

These dictionaries are used by methods in `PVSystem` and `ModelChain` to automagically determine what functions to call. In principle, user code might do something similar with them, but I doubt that happens.

The `TEMPERATURE_MODEL_PARAMETERS` dictionary with default values is probably the most useful to an end user because the default parameters are useful when calling `temperature` module functions directly (i.e. not through ModelChain/PVSystem).

My short term recommendation is to:

* deprecate `pvsystem.DC_MODEL_PARAMS` into `pvsystem._DC_MODEL_PARAMS`. I'd also be ok with just changing it without deprecation because 1. 0.7 is a big release and 2. this change won't effect many people and 3. My time is limited.
* change `iam.IAM_MODEL_PARAMS` to `iam._IAM_MODEL_PARAMS` to prevent problems before they start
* leave `TEMPERATURE_MODEL_PARAMETERS` alone

**Comment by veronicaguo** [comment]
Hi Will, I opened a short PR to make `DC_MODEL_PARAMS` and `IAM_MODEL_PARAMS` private. Please let me know what you think and if I missed anything. Thanks!

**Comment by wholmgren** [comment]
Thanks @veronicaguo! I'm hoping that others will let us know what they think of these API choices and if the public dictionaries are actually useful to them or not...
