### ISSUE TITLE
tmy_to_power commited? could not find it

### ISSUE THREAD

**Issue by NelisW** [pvlib/pvlib-python#79]
>>I wrote a new tmy_to_power notebook that replaces Test_Scripts. 

I have great difficulty with this upstream - pull request thing.  I spend more time correcting mashups than doing worthwhile coding.

Perhaps the tmy_to_power notebook was committed, but I did not find it after fetch upstream & merging to my branch. Test_Scripts is still there.

**Comment by wholmgren** [comment]
Not yet, it's still in PR #74. We have a policy of administrators not merging their own pull requests. 

If you're using the command line interface you can get it by doing something like

```
git checkout -b wholmgren-tutorials master
git pull https://github.com/wholmgren/pvlib-python.git tutorials
```

If you're using the github GUI client then you can lookup how to add my fork as a new remote.
