### ISSUE TITLE
use `xfail` decorator on `test_get_psm3`

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#802]
The ongoing failure of `test_get_psm3` is conditioning us (or at least me*) to accept PRs with failing tests. We've been told NREL is going to fix their API, but it keeps not happening, so I really think we should go ahead and mark this test with `pytest.xfail`. Perhaps `pytest.xfail(strict=True)` so that the test suite alerts us to when NREL does fix it. 

@CameronTStark can you fix this if you agree it makes sense?

* I wrongly approved #800 and I've not been checking #793 because I've been thinking that the test failures were only because of `test_get_psm3`.

**Comment by mikofski** [comment]
So sorry all for any inconveniences or issues as a result of the continued `test_get_psm3` failure!
Thanks @CameronTStark and @wholmgren for cleaning up after my PR puppy!

![image](https://user-images.githubusercontent.com/1385621/67796604-8b634a80-fa3d-11e9-87b2-ce287924aab4.png)
