### ISSUE TITLE
Pre-release announcement: pvlib-python v0.7

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvlib-python#809]
We're close to release of pvlib-python v0.7. This will be a **major** release including (but not limited to):

- refactor temperature models to a new module `temperature.py` (API changes)
- refactor incidence angle modifier models to a new module `iam.py` (API changes)
- update module and inverter parameter files (new files have a different format)
- add a new module `ivtools.py` with functions for fitting diode models to data
- removal of some deprecated functions.

A full list of changes to date is [here](https://github.com/pvlib/pvlib-python/blob/master/docs/sphinx/source/whatsnew/v0.7.0.rst).  

We plan to merge several open PRs for v0.7: #807, #805, #808, #804.  We may clean up some of the open issues that are currently marked for v0.7.

If you have an open pull request that still needs work, or are considering a pull request in the near future, please respond so that we can plan accordingly.

**Comment by wholmgren** [comment]
Some of those PRs and associated issues are missing 0.7 milestone markers. 

Looking at [the 0.7 issues/PRs](https://github.com/pvlib/pvlib-python/milestone/23)... I'm ok punting all of these to a future release. #472 might be a good one to do sooner than later, though.

Looking at [the untagged issues](https://github.com/pvlib/pvlib-python/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone)... Maybe add #785 and #768.

What's a realistic release date?

**Comment by wholmgren** [comment]
I cleared a lot of stale issues/PRs from the 0.7.0 milestone. #807 is currently the only unfinished item marked for 0.7.0. I'm ok holding for that if it's going to be fast. I'm also ok with pushing 0.7.0 now and following up with 0.7.1 and maybe 0.7.2 over the next month or two before introducing breaking changes that mark the start of the 0.8 development cycle.

**Comment by wholmgren** [comment]
@cwhanse this is the last issue labeled 0.7.0, but #821 is unlabeled and close to completion. Anything else?

**Comment by cwhanse** [comment]
Let's move on releasing v0.7 once #821 is merged.
