### ISSUE TITLE
Please add a download counter to the GitHub readme

### ISSUE THREAD

**Issue by jsstein** [pvlib/pvlib-python#813]
**Is your feature request related to a problem? Please describe.**
Not a problem, but an opportunity

**Describe the solution you'd like**
Add download shield to Readme.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by CameronTStark** [comment]
Josh asked me about this  and I found a source for PyPI and conda-forge.

Here are examples from each:
PyPI Downloads: ![PyPI Downloads](https://img.shields.io/pypi/dm/pvlib)
conda-forge Downloads:  ![conda-forge Downloads](https://anaconda.org/conda-forge/pvlib-python/badges/downloads.svg)

I'd also suggest tabularizing these shields to organize them [like pandas does](https://github.com/pandas-dev/pandas#pandas-powerful-python-data-analysis-toolkit). This would help the uninitiated to be clear about what each of these might mean. Certain people will be primarily concerned with code quality while others might be interested in publications or impact based on raw download counts.

I can make a PR for this as an example if there's no objections.

**Comment by wholmgren** [comment]
Sounds great, thanks!
