### ISSUE TITLE
ModelChain.dc and ModelChain.ac aren't described in documentation

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvlib-python#835]
[Documentation ](https://pvlib-python.readthedocs.io/en/stable/generated/pvlib.modelchain.ModelChain.html) for the ModelChain class doesn't describe the `dc` and `ac` attributes.

**Comment by wholmgren** [comment]
Should address as part of documentation changes in #1076

**Comment by wholmgren** [comment]
closing in favor of #1126
