### ISSUE TITLE
Expose temperature.faiman at PVSystem and ModelChain

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvlib-python#836]
`ModelChain.temperature_model` accepts `pvsyst` and `sapm` but not `faiman`.

Add `faiman` as an option for `ModelChain.temperature_model`.
Create `PVSystem.faiman_celltemp`

**Comment by wholmgren** [comment]
what's the milestone for this?

**Comment by cwhanse** [comment]
Don't hold v0.7 for this
