### ISSUE TITLE
pvlib.solarposition.equation_of_time_spencer71 / A coefficient is wrong

### ISSUE THREAD

**Issue by IntiPic** [pvlib/pvlib-python#847]
There's a difference between Iqbal's equation of time and the code. The 0.0000075 coefficient in the code has one more zero than Iqbal's. It should be changed into 0.000075.
I'm new at github so I don't know how is the process for reporting these issues.

Thanks, bye!

**Comment by cwhanse** [comment]
@IntiPic this is where issues are raised, thank you. In this case, the coefficient 0.0000075 (five '0's) is a correction as described in the [documentation ](https://pvlib-python.readthedocs.io/en/stable/generated/pvlib.solarposition.equation_of_time_spencer71.html#pvlib.solarposition.equation_of_time_spencer71) for that function.

**Comment by cwhanse** [comment]
Leaving this open since I think the docstring for `pvliv.solarposition.equation_of_time_spencer71` can be improved, in particular, the link to the email archive describing the correction is not referenced and so doesn't appear on the documentation page.

**Comment by IntiPic** [comment]
Thanks a lot. I should've read it better.
This is a big help. Been using the four 0's version for quite a while without knowing this.

**Comment by mikofski** [comment]
You may click the link in the documentation to be redirected to the [Fourier paper](https://www.mail-archive.com/sundial@uni-koeln.de/msg01050.html) post by Mac Oglesby in the Sundial mailing list

![image](https://user-images.githubusercontent.com/1385621/71839712-a4592f00-3070-11ea-8e1f-493c1d761302.png)

I wonder if we should just copy this letter into either PVPMC archive or this git repo for posterity in case it is lost or removed?

**Comment by wholmgren** [comment]
@cwhanse do you still want to improve the documentation of this function or can we close this?

**Comment by cwhanse** [comment]
Ok to close, the docstring is sufficient.
