### ISSUE TITLE
ENH: MAINT: STY: group iotool tests into folder

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#848]
**Is your feature request related to a problem? Please describe.**
there are so many tests now, would it be okay to group some of them, eg iotools into a folder?

**Describe the solution you'd like**
move all of the iotools tests into a folder called `iotools_tests` inside the `pvlib/test` folder

**Describe alternatives you've considered**
just keep letting the number of files in test grow until someone else thinks it might be useful to group them

**Additional context**
[pandas/tests](https://github.com/pandas-dev/pandas/tree/master/pandas/tests) are grouped in folders, but forgo the `_tests` suffix, it does seem redundant, but will pytest still work without it? I'm not set on any particular convention, as long as it's consistent

so what do folks think? OK to post here? Should I have posted in pvlib-python google group instead? thx!

**Comment by wholmgren** [comment]
I’m ok with any of these reorganizations of the tests. I have a mild preference for a pattern like pvlib/iotools/tests. 

And this is the right place to discuss.

**Comment by mikofski** [comment]
I'm not completely sure, but I think all of the tests need/should to be in the same top level folder, or at least in the past, I've had problems with VSCode, so maybe it's not a pytest problem per sé.

So like `pvlib/test/iotools/test_tmy3.py` etc. would that be okay?

**Comment by wholmgren** [comment]
Ok but I can assure you that pytest and vscode work just fine using the
pattern I suggested. There is something to be said for putting all the test
code in one place and something to be said for keeping it closer to the
code it tests.

**Comment by cwhanse** [comment]
> I’m ok with any of these reorganizations of the tests. I have a mild preference for a pattern like pvlib/iotools/tests.

I would prefer pvlib/iotools/test over pvlib/test/iotools/, but not a strong preference.

**Comment by mikofski** [comment]
The internet has spoken?

![Screenshot_20200113-234243_Twitter](https://user-images.githubusercontent.com/1385621/72323867-93a34d00-365e-11ea-891a-bf02f496d6a4.jpg)
