### ISSUE TITLE
Deprecation warning due to invalid escape sequences.

### ISSUE THREAD

**Issue by tirkarthi** [pvlib/pvlib-python#875]
**Describe the bug**

Deprecation warning due to invalid escape sequences.

**To Reproduce**

```
find . -iname '*.py'  | xargs -P 4 -I{} python3.8 -Wall -m py_compile {}

./pvlib/iotools/ecmwf_macc.py:58: DeprecationWarning: invalid escape sequence \.
  """
./versioneer.py:485: DeprecationWarning: invalid escape sequence \s
  LONG_VERSION_PY['git'] = '''
```

**Comment by mikofski** [comment]
Thanks! It's in the docstring, there's a backwards path separator, you can see in the documentation, it doesn't render correctly, easy fix

**Comment by mikofski** [comment]
@tirkarthi seems okay now, can you please check again? Thx!
![Screenshot_20200201-083508_Chrome](https://user-images.githubusercontent.com/1385621/73595468-f8b7c900-44cd-11ea-9499-b726215958ca.jpg)

**Comment by tirkarthi** [comment]
versioneer file also needs usage of raw strings prefix.

**Comment by mikofski** [comment]
Versioneer is automatically generated, I think this issue has already been reported over there, [Warner/python-versioneer: flake8 complaint #201](https://github.com/warner/python-versioneer/issues/201)
