### ISSUE TITLE
test_forecast failures with pandas 1.0.0

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvlib-python#877]
Pandas has released v1.0.0.  With pandas 1.0.0, `test_forecast.test_datetime` fails, as #872 shows in the test log.  It is not clear if the test itself is the problem: [these lines](https://github.com/pvlib/pvlib-python/blob/fb1ab533ab9a4b87a3161d577215ef3d8f12ed74/pvlib/tests/test_forecast.py#L117) do not set a timezone.

```
    start = datetime.now()
    end = start + timedelta(days=1)
```

**Should `start` and `end` be timezone-aware?**  The intent of the test is not clear to me.

**To Reproduce**

1. Install pandas 1.0.0
```
import pandas as pd
from datetime import datetime, timedelta
from pvlib.forecast import NAM

_latitude = 32.2
_longitude = -110.9
_tz = 'US/Arizona'
_start = pd.Timestamp.now(tz=_tz)
_end = _start + pd.Timedelta(days=1)

amodel = NAM()
start = datetime.now()
end = start + timedelta(days=1)
try:
    amodel.get_processed_data(_latitude, _longitude, start, end)
    print("Success with {}".format(pd.__version__))
except:
    print("Failed with {}".format(pd.__version__))
```

Now run with pandas < 1.0.0 (e.g., 0.22.0)

**Comment by wholmgren** [comment]
The test ensures that the function works if you use a python datetime object instead of pandas datetime object. We should check that start/end are localized and, if not, raise `TypeError` before issuing the query.

**Comment by cwhanse** [comment]
Want to correct this in conjunction with #878? Or I can do it. The test failures will repeat for every PR unless we pin pandas <= 1.0.0.

**Comment by wholmgren** [comment]
Yes, I should have said I'll provide a fix as soon as I get out of conda hell. Apparently I should not have run `pip install pandas -U` in an environment with conda-provided numpy/netcdf/hdf5. Yay python packaging.
