### ISSUE TITLE
access private _parse_pvgis_tmy_csv() function as read_pvgis_tmy_csv()

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#880]
**Is your feature request related to a problem? Please describe.**
someone sent me a csv file they downloaded from pvgis, and I needed to parse it, so I had to call the private methods like this:

```python
>>> from pvlib.iotools.pvgis import _parse_pvgis_tmy_csv
>>> with (path_to_folder / 'pvgis_tmy_lat_lon_years.csv').open('rb') as f:
        pvgis_data = _parse_pvgis_tmy_csv(f)
```

**Describe the solution you'd like**
If I need this, others may also. I think a public method that takes either a string or a buffer could be useful? Something called `read_pvgis_tmy_csv()`

**Describe alternatives you've considered**
I was able to do it by just calling the private function and it worked, so that's an alternative also

**Additional context**
related to #845 and #849

**Comment by cwhanse** [comment]
OK with me to refactor to the same pattern as #842 in particular the get / read / parse [trio](https://github.com/pvlib/pvlib-python/pull/842#issuecomment-570309454).

**Comment by mikofski** [comment]
I just started in this, but didn't push it yet, sorry. Kinda important now to have a static/remoteless test that checks parsing, since all of the tests are decorated
