### ISSUE TITLE
Increase minimum pandas/numpy versions in v0.8.0

### ISSUE THREAD

**Issue by CameronTStark** [pvlib/pvlib-python#887]
A need to increase the pandas version has been identified via the work in #885 that sought to remove the `needs_pandas_0_22` and `needs_pandas_0_17` decorators. For example, the function pvlib.irradiance.perez() specifically outputs different components whether it uses pandas>=0.18 or before and the tests are required to deal with this difference. From this perspective the goal is to simplify tests and avoid different functionality within supported versions of pandas. 

A good guideline for the process of increasing versions is proposed by @wholmgren in #828 where he outlines the criteria as:
> I suggest that we instead aggressively drop numpy/python versions when 1. there is a reason to do so and 2. the versions are outside the NEP-29 windows

The simplification of the testing suite and standardizing outputs certainly fall into 1. above as a criteria for deciding on the minimum pandas versions.

**Comment by wholmgren** [comment]
done in some recent PRs
