### ISSUE TITLE
add python 3.8 to CI configuration

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#903]
@CameronTStark you want to take this on? I think it's just a matter of copy `requirements-py37.yml` and paste into `requirements-py38.yml`. Then add the `python.version: '38'` to all of the azure jobs. 

I don't see a need to add it to travis (we could probably remove the travis `CONDA_ENV=py37` build too).

We can discuss dropping 3.5 for 0.8, but let's keep it in the test suite for now.

**Comment by CameronTStark** [comment]
Yes, I'll put implementing 3.8 on my list. I've been wondering what you thought about it. There's a few creature comforts in 3.6 that would be nice to have around like f-strings so I've been thinking about bumping the minimum Python as well. 

We should keep in mind default versions of Python that come with commonly used Linux LTS distros like Ubuntu/Red Hat; Ubuntu LTS 16.04 comes with Python3.5 for instance. That's almost four years old now so maybe that's not so important but could influence our decision.
