### ISSUE TITLE
Rename ModelChain test fixture `system`

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvlib-python#908]
[This](https://github.com/pvlib/pvlib-python/blob/6a5b8f886b2f505bec33087370c86832161f2a81/pvlib/tests/test_modelchain.py#L20) should be renamed to `sapm_dc_snl_ac_sapm_temp_system` follow the pattern for other fixtures.

**Comment by veronicaguo** [comment]
@cwhanse I'm happy to take a stab at this. Also, what do you think about naming it to `sapm_dc_snl_ac_system`? it seems to be more consistent with the other fixture names. Thanks!

**Comment by cwhanse** [comment]
Ok with me to be `sapm_dc_snl_ac_system` and only have the temperature model terms added when that's important for the fixture.
