### ISSUE TITLE
Error on Klucher's transposition model equation

### ISSUE THREAD

**Issue by IntiPic** [pvlib/pvlib-python#923]
I noticed on the documentation that the modulating term F' in the Klucher expression for the transposition factor is missing an exponent of 2 ( https://pvlib-python.readthedocs.io/en/stable/generated/pvlib.irradiance.klucher.html )

It should read F' = 1-(DHI/GHI)^2 instead of F' = 1-(DHI/GHI)

The error appears only on the docs, the code is correct.

Can someone corroborate that?

Thanks a lot!

**Comment by cwhanse** [comment]
You are correct, the docstring is missing the "^2". Thanks for reporting!
