### ISSUE TITLE
Mismatch between real Ghi and ineiChen computed

### ISSUE THREAD

**Issue by nicolabortignon** [pvlib/pvlib-python#952]
**Describe the bug**
You can see the working code here:
https://github.com/SeedLabs-it/PVPowerCalculation/blob/ReviewPowerComputation/genericPowerCalculationModel.py

I'm getting the Ghi for lat/long of an European location here: https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html#TMY 
The Ghi values is reported in [W/m2]

I also compute the Ghi from the ineiChen model, just for comparison.
Here you can see the two curves compared over a yearly period

![Screen Shot 2020-04-14 at 8 39 05 AM](https://user-images.githubusercontent.com/883459/79193910-d9bda780-7e2b-11ea-916a-aa0d877e2848.png)

And zooming into the ineiChen Ghi graph, only, it's clear that the pattern is the same
![Screen Shot 2020-04-14 at 8 39 33 AM](https://user-images.githubusercontent.com/883459/79193947-ed690e00-7e2b-11ea-961e-09e0156826a2.png)

There is a ~42 ratio difference between the 2 values.
I didn't find any reference of what is the unit of measurement produced by the ineiChen model.
How do I reconcile the two values?

**Comment by cwhanse** [comment]
It appears you have switched `altitude` and `dni_extra` [here](https://github.com/SeedLabs-it/PVPowerCalculation/blob/7e437c73b234b242863bb2e754fd19e60d845176/genericPowerCalculationModel.py#L147).

**Comment by nicolabortignon** [comment]
Thank you @cwhanse, turns out I was looking at an outdated documentation. 
For completeness, here the new graph.
![Screen Shot 2020-04-15 at 12 41 55 PM](https://user-images.githubusercontent.com/883459/79328877-0995a980-7f17-11ea-9fe4-a72052b1874e.png)
