### ISSUE TITLE
Refactor CEC SDM fit test

### ISSUE THREAD

**Issue by Peque** [pvlib/pvlib-python#956]
It feels like `test_fit_sdm_cec_sam()` could be split into two:

- Check for expected vs. actual output
- Check for exception when the parameters cannot be estimated

The code under the `with` statement has no relation with the code above.

**Comment by cwhanse** [comment]
This is a good suggestion. I'll roll the changes in #956 into #708 which refactors all of `pvlib.ivtools`.  Please leave both #956 and #957 open for now.

**Comment by cwhanse** [comment]
Closed via #708, test function split into `test_fit_cec_sam` and `test_fit_cec_sam_estimation_failure`
