### ISSUE TITLE
remove pvsystem.systemdef function

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#965]
Does anyone use this function? Does anyone have use case for it? I'm inclined to remove it without deprecation in 0.8.

Another option is to move it to `pvlib.iotools.tmy`.

**Comment by mikofski** [comment]
https://github.com/pvlib/pvlib-python/blob/f8921bd3879c4bcd9c0242005319729ab04ce7f6/pvlib/pvsystem.py#L894

relevant issues:
* https://github.com/pvlib/pvlib-python/issues/17

relevant tests:
* https://github.com/pvlib/pvlib-python/blob/03d6180f00283600029b56c437b7861e853ddf26/pvlib/tests/test_pvsystem.py#L22
* https://github.com/pvlib/pvlib-python/blob/03d6180f00283600029b56c437b7861e853ddf26/pvlib/tests/test_pvsystem.py#L39
* https://github.com/pvlib/pvlib-python/blob/03d6180f00283600029b56c437b7861e853ddf26/pvlib/tests/test_pvsystem.py#L57

[search pvlib for `systemdef`](https://github.com/pvlib/pvlib-python/search?q=systemdef&unscoped_q=systemdef)
