### ISSUE TITLE
pvlib.soiling.hsu model implementation errors

### ISSUE THREAD

**Issue by jsstein** [pvlib/pvlib-python#970]
**Describe the bug**
I ran an example run using the Matlab version of the HSU soiling function and found that the python version did not give anywhere near the same results.  The Matlab results matched the results in the original JPV paper.  As a result of this test, I found two errors in the python implementation, which are listed below:

1.  depo_veloc = {'2_5': 0.004, '10': 0.0009} has the wrong default values.  They are reversed.
The proper dictionary should be: {'2_5': 0.0009, '10': 0.004}.  This is confirmed in the JPV paper and the Matlab version of the function.

2. The horiz_mass_rate is in g/(m^2*hr) but should be in g/(m^2*s).  The line needs to be multiplied by 60x60 or 3600.
The proper line of code should be: 
horiz_mass_rate = (pm2_5 * depo_veloc['2_5']+ np.maximum(pm10 - pm2_5, 0.) * depo_veloc['10'])*3600

When I made these changes I was able to match the validation dataset from the JPV paper, as shown below.
![image](https://user-images.githubusercontent.com/5392756/82380831-61c43d80-99e6-11ea-9ee3-2368fa71e580.png)

**Comment by mikofski** [comment]
nice sleuthing Josh! Is a PR forthcoming? 🎉

**Comment by jsstein** [comment]
Hi Mark,
                Yes, a PR is in the works.  I need to improve the testing first.

-Josh

**Comment by cwhanse** [comment]
Now I need to go back and figure out where I missed these errors in the review.

**Comment by mikofski** [comment]
> Now I need to go back and figure out where I missed these errors in the review.

Nah, IMHO this right here is why I :heart: open science. Everyone makes a mistake, even the best, and it may go unnoticed perhaps for a long time, but when used in earnest by many, important issues are caught & fixed more quickly. This right here is the proof!

**Comment by cwhanse** [comment]
Some improvements are needed in #977
