### ISSUE TITLE
Make building docs on windows slightly easier

### ISSUE THREAD

**Issue by kanderso-nrel** [pvlib/pvlib-python#978]
**Is your feature request related to a problem? Please describe.**
Running `make html` on a Windows system that doesn't have `make` installed fails.

**Describe the solution you'd like**
Would be nice to be able to run `make html` without having to install make on Windows.  Newer versions of `sphinx-quickstart` create a `make.bat` file that invokes `sphinx-build`'s [make-mode](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-M).  Here's a copy of it in RdTools: https://github.com/NREL/rdtools/blob/development/docs/sphinx/make.bat.  I think just copying that file into `docs/sphinx` would make it work.

**Describe alternatives you've considered**
Can also just run `sphinx-build -M html source build` manually instead of using `make.bat` as a shortcut, it's a little more typing but not a huge deal.

Side note:  is it mentioned anywhere in the docs how to build the docs?  I'd expect to see it on the Contributing page, or maybe the Installation page, but I'm not finding it.

**Comment by wholmgren** [comment]
Sounds good. Pull request welcome. 

I agree that we should document how to build the docs. Maybe here: https://pvlib-python.readthedocs.io/en/stable/contributing.html#documentation
