### ISSUE TITLE
benchmark with other simulation tools

### ISSUE THREAD

**Issue by PKMendes** [pvlib/pvlib-python#985]
Hello,

Hi used modelchain together with PVGis database in order to calculate the yearly irradiance and AC output of a 10x290W LG + Fronius 3kW inverter on a specific location. Using the software and running: [mc.run_model(tmy_data)](url)

I got the following results: 
yearly effective_irradiance: 1716kWh/m2
yearly AC output: 3.06 MW

Comparing those results with other simulation tools (same location, azimuth, tilt, mounting type, pv modules) I see quite different results, moreover while the effective_irradiance is higher in my case, I get a lower ac output.

Sunny Design:   
yearly AC output: 3,971.17 kWh

PVGIS:   
Yearly in-plane irradiation: 1557.51 kWh/m2
yearly AC output: 3.413 MW

PVSol:   
Annual global irradiation: 1581.2 kWh/m2
yearly AC output: 4.138 MW

I used 2015 as reference data for my meteo inputs, nevertheless changing to other years, it has an impact of max 5% on the AC output.

I notice that for surface_azimuth=244, I get a different output with -84 or 244 degrees. Which one is correct?

I used as inputs for the system the following:

[location = Location(pvGis.latitude, pvGis.longitude,'UTC',altitude)

system = PVSystem(surface_tilt=10, surface_azimuth=244,
                  module_parameters=sandia_module,
                  inverter_parameters=cec_inverter,
                  temperature_model_parameters=temperature_model_parameters,
                  modules_per_string=10, strings_per_inverter=1)

mc = ModelChain(system, location,  orientation_strategy=None)](url)

Could I have your feedback on your experience regarding those results?

**Comment by cwhanse** [comment]
Hi @PKMendes, this is a discussion about pvlib usage, could you move it to either https://groups.google.com/forum/#!forum/pvlib-python or to https://stackoverflow.com/ tag pvlib?

To answer the question about surface_azimuth, I'd use 244. I don't know if -84 would give correct results, I would like to think so, but it may not be tested.

It's not clear that the irradiance quantities listed above are comparable. Is "global irradiation" (from PVSol) in the system plane, or is this horizontal?  The output from pvlib that you want to compare with PVGIS is 'poa_global'.

I have no idea how Sunny Design, PVGIS or PVSol are modeling AC power, there must be a sequence of models starting from GHI, and different models/assumptions will produce different results. 

I will leave this issue open for you to move the discussion and then close it.
